#!/bin/sh
# inkVerb updater for Verber™, verb.ink

# This updates the Verber
## This contains many version updaters to update a Verber™ sequentially, one version at a time.
## This is run at the path: /var/local/verb/${VUPDATE_REPO}/update

# DEV NOTE: Larger versions must be at the bottom, smaller versions at the top, so "descending"

# DEV INSTRUCTIONS: Put all related files for each patch in a folder named by the version number, ie 0.805

# DEV NOTE: Serfs are automatically copied & updated from ${VUPDATE_REPO}/serfs to the Verber before any patches run, after the verno check.


MIN_VERNO=0.811
VUPDATE_REPO="verb-update-dev"

## Sample version updater:
#UPDATE_PATCH_VERNO=
#if [ $(echo ${UPDATE_PATCH_VERNO} | sed -e "s/\.//" | sed -e "s/^0*//") -gt $(echo ${VERNO} | sed -e "s/\.//" | sed -e "s/^0*//") ] ; then
## Run the update scripts for this patch
#
###### SCRIPTS GO HERE #####
#
## eg: echo "I would update the serfs here, but that happens automatically."
#
############################
## Set and refresh the current version into inklists
#sed -i "s/VERNO=.*/VERNO=${UPDATE_PATCH_VERNO}/g" /var/local/verb/configs/inklists/verberverno
#. /var/local/verb/configs/inklists/verberverno
#echo "Verber updated to v${VERNO}"
#else
#echo "${UPDATE_PATCH_VERNO} patch not necessary..."
#fi
###############END#UPDATE#PATCH#


## Version Check ##
### The minimum version that can use this updater
## Include the configs
. /var/local/verb/configs/sitenameip
#. /var/local/verb/configs/siteurilist # Include this after MIN_VERNO=0.812
. /var/local/verb/configs/inklists/verberverno
## Check minimal updateable version
if [ $(echo ${MIN_VERNO} | sed -e "s/\.//" | sed -e "s/^0*//") -gt $(echo ${VERNO} | sed -e "s/\.//" | sed -e "s/^0*//") ] ; then
echo "Current Verber™ version is ${VERNO}, minimum ${MIN_VERNO} to use this updater.
Run updateverberlegacy for older versions."
exit 0
fi

# Update Serfs
rm -f /var/local/verb/serfs/*
cp /var/local/verb/${VUPDATE_REPO}/serfs/* /var/local/verb/serfs/
echo "Serfs have been updated."

# Run version-by-version updates


UPDATE_PATCH_VERNO=0.812
if [ $(echo ${UPDATE_PATCH_VERNO} | sed -e "s/\.//" | sed -e "s/^0*//") -gt $(echo ${VERNO} | sed -e "s/\.//" | sed -e "s/^0*//") ] ; then
# Run the update scripts for this patch

##### SCRIPTS GO HERE #####

# eg: echo "I would update the serfs here, but that happens automatically."

# Create the siteurllist config
echo "#!/bin/sh
## This is a config file for other verb scripts

# Determine the site urls, whether they are active or not

nameURI=${SITENAME}.verb.${SITETLD}
hostURI=${SITEHOST}.${SITENAME}.verb.${SITETLD}
emailTLDURI=${SITENAME}.verb.${SITETLD}
emailURI=${SITENAME}.verb.email
oneURI=${SITENAME}.verb.one
inkURI=${SITENAME}.verb.ink
blueURI=${SITENAME}.verb.blue
guruURI=${SITENAME}.verb.guru
kiwiURI=${SITENAME}.verb.kiwi
pinkURI=${SITENAME}.verb.pink
redURI=${SITENAME}.verb.red
rocksURI=${SITENAME}.verb.rocks
unoURI=${SITENAME}.verb.uno
" > /var/local/verb/configs/siteurilist
. /var/local/verb/configs/siteurilist

# site-files
## Copy new files
rm -f /var/local/verb/configs/site-files/*.conf*
cp -rf /var/local/verb/${VUPDATE_REPO}/${UPDATE_PATCH_VERNO}/site-files/conf /var/local/verb/configs/site-files/
## Replace
sed -i "s/emailURI286/${emailURI}/g" /var/local/verb/configs/site-files/conf/*
sed -i "s/oneURI286/${oneURI}/g" /var/local/verb/configs/site-files/conf/*
sed -i "s/inkURI286/${inkURI}/g" /var/local/verb/configs/site-files/conf/*
sed -i "s/blueURI286/${blueURI}/g" /var/local/verb/configs/site-files/conf/*
sed -i "s/guruURI286/${guruURI}/g" /var/local/verb/configs/site-files/conf/*
sed -i "s/kiwiURI286/${kiwiURI}/g" /var/local/verb/configs/site-files/conf/*
sed -i "s/pinkURI286/${pinkURI}/g" /var/local/verb/configs/site-files/conf/*
sed -i "s/redURI286/${redURI}/g" /var/local/verb/configs/site-files/conf/*
sed -i "s/rocksURI286/${rocksURI}/g" /var/local/verb/configs/site-files/conf/*
sed -i "s/unoURI286/${unoURI}/g" /var/local/verb/configs/site-files/conf/*
## Rename
rename "s/emailURI286/${emailURI}/" /var/local/verb/configs/site-files/conf/*
rename "s/oneURI286/${oneURI}/" /var/local/verb/configs/site-files/conf/*
rename "s/inkURI286/${inkURI}/" /var/local/verb/configs/site-files/conf/*
rename "s/blueURI286/${blueURI}/" /var/local/verb/configs/site-files/conf/*
rename "s/guruURI286/${guruURI}/" /var/local/verb/configs/site-files/conf/*
rename "s/kiwiURI286/${kiwiURI}/" /var/local/verb/configs/site-files/conf/*
rename "s/pinkURI286/${pinkURI}/" /var/local/verb/configs/site-files/conf/*
rename "s/redURI286/${redURI}/" /var/local/verb/configs/site-files/conf/*
rename "s/rocksURI286/${rocksURI}/" /var/local/verb/configs/site-files/conf/*
rename "s/unoURI286/${unoURI}/" /var/local/verb/configs/site-files/conf/*

# inkNet
cp -f /var/local/verb/${VUPDATE_REPO}/${UPDATE_PATCH_VERNO}/donjon/* /var/local/verb/donjon/
echo "#!/bin/sh
## This is a config file for inkNet information


INKNET_REPO=NOT_SET
INKNETSSLCA=NOT_SET
INKNETSSHCA=NOT_SET" > /var/local/verb/configs/inknet/inknetinfo


###########################
# Set and refresh the current version into inklists
sed -i "s/VERNO=.*/VERNO=${UPDATE_PATCH_VERNO}/g" /var/local/verb/configs/inklists/verberverno
. /var/local/verb/configs/inklists/verberverno
echo "Verber updated to v${VERNO}"
else
echo "${UPDATE_PATCH_VERNO} patch not necessary..."
fi

## INCLUDE AFTER 0.812, even if already at 0.812 !!
. /var/local/verb/configs/siteurilist
##############END#UPDATE#PATCH#





# Finish
echo "Verber at v${VERNO} framework from ${SITEUPDATEREPO}."

