#!/bin/sh
#IVapp dragon installer! verb.ink
set -e

# This installs the IVapp submodule with settings as specified

# IVapp is a medium-security "user jail" framework for login users that manage tasks in various inkVerb modules, such as inkNet, Vallpaper, PinkWrite, et cetera.
# Generally, file structure is: ivapp/MODULE/USERS, usually with at least two types of users: one for the master-craftsmen and one for the consumers

# How to use:
## ./installivapp [/path/to/ivapp/settings/file.conf]


# Check variables
## Entered
if [ -z "$1" ]; then
echo "Specify a settings file according to instructions."
exit 55; fi
## Exists
if [ ! -f "$1" ]; then
echo "That settings file does not exist."
exit 55; fi

CONF=$1

# Include config
. ${CONF}


# Check status
if [ -f "${STATUSFILE}" ]; then
. ${STATUSFILE}
 if [ "${IVAPPSTATUS}" = "INSTALLED" ]; then
echo "${MODULENAME} is already installed."; exit 0
 else
echo "${IVAPPSTATUS}"
 fi
fi

# Verify directory structure
mkdir -p ${IVAPPBASE}/${IVAPPDIR}
cd ${IVAPPBASE}/${IVAPPDIR}
mkdir -p ${IVAPPGRPDIRS}

# Directory ownership
chmod 751 -R ${IVAPPBASE}

# Create the user groups
echo "${IVUSERGROUPS}" | xargs -n1 groupadd ${g};

# Write the configs
## For the module
echo "#!/bin/sh
# inkVerb's ${MODULENAME} config file, verb.ink

IVAPPSTATUS=\"INSTALLED\"" > ${STATUSFILE}
## For IVapp reference
echo "#!/bin/sh
# inkVerb's ivApp config for ${MODULENAME}

CONFIG_LOCATION=\"${CONF}\"
" > ${IVAPPBASE}/${IVAPPDIR}/loc.conf

# Finish
echo "Done.
${MODULENAME} has been setup.
"

