#!/bin/sh
#inkVerbSerf! verb.ink

# This activates the repo....verb.vip folder so the web will provide an index

# How to use:
## ./activaterepo [on/off]

# Eg:
## ./activaterepo on
## ./activaterepo off


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

if [ "$1" = "on" ]
then
    rm -rf /var/www/html/vip.repo
    /bin/ln -sfn /var/www/vip/repo /var/www/html/vip.repo
    /bin/echo "repo on."
exit 0
fi

if [ "$1" = "off" ]
then
    rm -f /var/www/html/vip.repo
    cp -R /var/www/html/0ne /var/www/html/vip.repo
    /bin/echo "repo off."
exit 0
fi

