#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This activates a domain to work with either the FTP-accessible domains/ directory or a vapp

# How to use:
## ./activatedomain [domain] [vappname.domain - if activating the vapp]

# Eg:
## ./activatedomain inkisaverb.com				# activate inkisaverb.com for the FTP domains/ directory
## ./activatedomain inkisaverb.com drupal.inkisaverb.com	# activate inkisaverb.com for the Drupal vapp


DOMAIN=$1
VAPPNM=$2

if [ -n ${2} ]; then
then
    rm -rf /var/www/html/${DOMAIN}
    ln -sfn /var/www/vapps/${VAPPNM} /var/www/html/${DOMAIN}
    echo "${VAPPNM} vapp active at ${DOMAIN}."
exit 0
fi

if [ -z ${2} ]; then
then
    rm -rf /var/www/html/${DOMAIN}
    ln -sfn /var/www/domains/${DOMAIN} /var/www/html/
    echo "${DOMAIN} domain active."
exit 0
fi

