#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This activates the files....verb.guru folder so it the web will give an index
## Prerequisite: installvsftpd

# How to use:
## ./activatefiles [on/off]

# Eg:
## ./activatefiles on
## ./activatefiles off


# Include the config
. /var/local/verb/configs/siteurilist

if [ "$1" = "-h" ]
then
    echo "Usage: ./activatefiles [on/off]

Examples:
 ./activatefiles on
 ./activatefiles off

 allowed arguments:
 on	(files.${guruURI} becomes a web-accessible folder)
 off	(files.${guruURI} returns to a redirect to ${inkURI})"
exit 0
fi

if [ "$1" = "on" ]
then
    rm -rf /var/www/html/guru.files
    ln -s /var/www/guru/files /var/www/html/guru.files
    echo "files on."
exit 0
fi

if [ "$1" = "off" ]
then
    rm -f /var/www/html/guru.files
    cp -R /var/www/html/0ne /var/www/html/guru.files
    echo "files off."
exit 0
fi
