#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This adds an existing domain to guru/_domains

# How to use:
## ./adddomainguru [olddomain.tld]


OLDDOMAIN=$1

ln -s /var/www/domains/${OLDDOMAIN} /srv/guru/_domains/${OLDDOMAIN}
