#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This adds domains with OpenDKIM profiles and keys and inkCert and Apache configs and enables CGI.
## This also creates a folder for the domain in www/domains which an ftpvip can access

# How to use:
## ./adddomaincgi [newdomain.tld]


# Include settings
. /opt/verb/conf/sitenameip
. /opt/verb/conf/inkcert/inkcertstatus

NEWDOMAIN=$1

# Check the domain shell
if [ ! -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${NEWDOMAIN} ]; then
echo "The shell for ${NEWDOMAIN} does not exist yet. Creating it..."
/opt/verb/serfs/newdomainshell ${NEWDOMAIN}
fi

# Check if it already exists
if [ -f /etc/apache2/sites-available/${NEWDOMAIN}.conf ]; then
 if [ -f /etc/apache2/sites-enabled/${NEWDOMAIN}.conf ]; then
 echo "That subdomain already exists."
 exit 0
 else
 echo "That site's config exists, but it doesn't seem to be active on Apache. Something's not right."
 exit 0
 fi
fi

# Copy and prepare Apache server config files
cp /opt/verb/conf/site-files/conf/newdomaincgi.tld.conf /etc/apache2/sites-available/${NEWDOMAIN}.conf 
sed -i "s/newdomain.tld/${NEWDOMAIN}/g" /etc/apache2/sites-available/${NEWDOMAIN}.conf
if [ ! -d /var/www/domains/${NEWDOMAIN} ]; then
cp -rf /opt/verb/conf/site-files/newdomain.tld /var/www/domains/${NEWDOMAIN}
fi
ln -sfn /var/www/domains/${NEWDOMAIN} /var/www/html/
chown -R www-data:www-data /var/www/html/${NEWDOMAIN}
chown -R www-data:www-data /var/www/domains/${NEWDOMAIN}
chmod -R 750 /var/www/domains/${NEWDOMAIN}
a2ensite ${NEWDOMAIN}
apache2ctl graceful

# inkDNS
/opt/verb/serfs/inkdnsadddomain ${NEWDOMAIN}
wait
/opt/verb/serfs/inkdnsaddmail ${NEWDOMAIN}
wait
/opt/verb/serfs/inkdnsaddinkdkim ${NEWDOMAIN}
wait

# inkCert
## Ensure that you don't get double entries
sed -i "s/, ${NEWDOMAIN}/ /g" /opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini
## Add it to the cli-ini
sed -i "/^domains =/ s/$/, ${NEWDOMAIN}/" /opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini

# Finish
echo "Great! With no error messages, you are ready to run inkCert for ${NEWDOMAIN}, unless you want to add subdomains."

