#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This adds an existing domain to vip/_domains

# How to use:
## ./adddomainvip [olddomain.tld]


OLDDOMAIN=$1

ln -s /var/www/domains/${OLDDOMAIN} /srv/vip/_domains/${OLDDOMAIN}

