#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This backs up the installed Nextcloud webapp data folder by exporting the database, and siteconfig file into one downloadable zip file in the "guru" folder and symlinked to the main site domain.
## This is separate from other backups because Nextcloud's developers make exporting difficult by more or less "welding" the app to the server. But, the export file is also smaller.
## This mainly backs up the user files and database, not the app itself.

# How to use:
## ./backupnextcloud [securename 0-9, a-z, and A-Z only] [-nl for no link, optional]

# Eg:
## ./backupnextcloud 583
## ./backupnextcloud 7aJk -nl
## ./backupnextcloud b


SECNAME=$1

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist
. /var/local/verb/configs/verbapp.nextcloud

# Export the database
cd /var/local/verb/serfs
/var/local/verb/serfs/mysqlex ${APPDBASE}
mv /var/local/verb/serfs/${APPDBASE}.sql /var/www/vapps/nextcloud/data/

# Copy the config
cp /var/local/verb/configs/verbapp.nextcloud /var/www/vapps/nextcloud/data/

# Zip the data directory
cd /var/www/vapps/nextcloud
zip -r verb.nextcloud.${SECNAME}.vbak.zip data
mv verb.nextcloud.${SECNAME}.vbak.zip /var/www/guru/

# Finish
if [ "$3" = "-nl" ]
then
	echo "nextcloud has been backed up to the 'guru' folder.

Note that the app remains live.
"
exit 0
fi

ln -s /var/www/guru/verb.nextcloud.${SECNAME}.vbak.zip /var/www/html/${SITETLD}/
chown -R www-data:www-data /var/www/html/${SITETLD}/verb.nextcloud.${SECNAME}.vbak.zip
echo "Nextcloud has been backed up to the 'guru' folder and can also be downloaded at:

http://${nameURI}/verb.nextcloud.${SECNAME}.vbak.zip

Note that the app remains live.
"

