#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This backs up the installed Nextcloud webapp data folder by exporting the database, and siteconfig file into one downloadable vbak file in the "guru" folder and symlinked to the main site domain.
## This is separate from other backups because Nextcloud's developers make exporting difficult by more or less "welding" the app to the server. But, the export file is also smaller.
## This mainly backs up the user files and database, not the app itself.

# How to use:
## ./backupnextcloud [securename 0-9, a-z, and A-Z only] [-nl for no link, optional]

# Eg:
## ./backupnextcloud 583
## ./backupnextcloud 7aJk -nl
## ./backupnextcloud b


SECNAME=$1

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist
. /var/local/verb/configs/vapp.nextcloud

# Export the database
cd /var/www/vapps/nextcloud/data
/var/local/verb/serfs/mysqlvappout vapp.nextcloud; wait

# Pack the data directory
cd /var/www/vapps/nextcloud
/var/local/verb/serfs/vtxzin data
mv data.vtxz verb.nextcloud.${SECNAME}.vbak
mv verb.nextcloud.${SECNAME}.vbak /var/www/guru/

# Finish
if [ "$3" = "-nl" ]
then
echo "nextcloud has been backed up to the 'guru' folder.

Note that the app remains live.
"
exit 0
fi

ln -s /var/www/guru/verb.nextcloud.${SECNAME}.vbak /var/www/html/${SITETLD}/
chown -R www-data:www-data /var/www/html/${SITETLD}/verb.nextcloud.${SECNAME}.vbak
echo "Nextcloud has been backed up to the 'guru' folder and can also be downloaded at:

http://${nameURI}/verb.nextcloud.${SECNAME}.vbak

Note that the app remains live.
"

