#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This restores a backup .vbak file from an inkVerb app backed-up using backup

# Prereq: Either the app must already be installed (and will be totally replaced)
## or you must create the symlink from the html/tld.app folder to the vapps/APP folder

# Instructions:
## The file can have any name, even if you changed it from the original, as long as it ends in .vbak
## The file MUST be uploaded to the "guru" folder, which can be done with vsftp installed and an ftpguru

# How to use:
## ./backuprestore [app namespace] [filename]

## This uses the same app namespace as installAPPNAME and vapp.APPNAME configs
## This does not work for ghost sites
## For WordPress installed to a domain, the namespace follows the format: wp-DOMAIN.TLD or wp-SUB.DOMAIN.TLD

# Eg:
## ./backuprestore orangehrm verb.orangehrm.sF52.vbak
## ./backuprestore wp.inkisaverb.com verb.wp.inkisaverb.com.ftU8.vbak


APPNAME=$1
FILENAME=$2

# Include the site config
. /var/local/verb/configs/sitenameip

# Backup and remove whatever the original status is
. /var/local/verb/configs/vapp.${APPNAME}
cd /var/www/vapps/${APPNAME}/
/var/local/verb/serfs/mysqlvappout vapp.${APPNAME}; wait
mv /var/local/verb/configs/vapp.${APPNAME} .
cd /var/www/vapps/
/var/local/verb/serfs/vtxzin ${APPNAME}
mv ${APPNAME}.vtxz verb.${APPNAME}.restore-originalbackedup.vbak
mv verb.${APPNAME}.restore-originalbackedup.vbak /var/www/guru/
/var/local/verb/serfs/mysqlkilldb ${APPDBASE}; wait
/var/local/verb/serfs/mysqlkilluser ${APPDDBUSR}; wait
rm -rf ${APPNAME}

# Unpack the file
cd /var/www/guru
mv ${FILENAME} ${APPNAME}.vtxz
/var/local/verb/serfs/vtxzout ${APPNAME}
mv ${APPNAME} /var/www/vapps/

# Restore and include the app config
mv /var/www/vapps/${APPNAME}/vapp.${APPNAME} /var/local/verb/configs/
. /var/local/verb/configs/vapp.${APPNAME}

# Restore the database
/var/local/verb/serfs/mysqlnewdb ${APPDBASE} ${APPDDBUSR} ${APPDDBPAS}
cd  /var/www/vapps/${APPNAME}
/var/local/verb/serfs/mysqlin ${APPDBASE}; wait
rm -f ${APPDBASE}.sql

# Own
chown -R www-data:www-data /var/www/vapps/${APPNAME}

# Finish
echo "${APPNAME} has been restored and all its backup files removed from this server.

A backup of the previous ${APPNAME} on this server has been saved in the guru folder just in case.
"

