#!/bin/sh
#inkVerbSerf! verb.ink

# This restores a RoundCube backup .vbak file backed-up using backuprcmail
## You may run installemail prior to this, however this will completely overwrite the old roundcube
## and the old roundcube, settings, and database will be backed up in www/email

# Instructions:
## The file can have any name, even if you changed it from the original, as long as it ends in .vbak
## The file MUST be uploaded to the "vip" folder, which can be done with vsftp installed and an ftpvip

# NOTE:
## This is relatively benign and arguably unnecessary because it only affects SOME user settings only within the RoundCube app itself, and only for identical email inpfa created or imported in PostfixAdmin
## This is in addition to backupvmail and backupvmailrestore (which only affect Postfix) and neither overlaps nor conflicts
## There is no backup or backuprestore for PostfixAdmin since PFA's database is a controller of and slave to Postfix.

# How to use:
## ./backuprcmailrestore [filename]

# Eg:
## ./backuprcmailrestore verb.roundcube.a52.vbak


FILENAME=$1

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitemailpath

# Check allowed status
if [ ${SITERCPATH} = "RC_NOT_ALLOWED" ]; then
/bin/echo "
This is a backup email server and Roundcube is not allowed, including restore.
"
exit 0

# Backup and remove whatever the original status is
elif [ ${SITERCPATH} = "RC_NOT_INSTALLED" ]; then
/bin/echo "
Roundcube is not installed, no backups will be made in this restore.
"
RCFRESH="YES"
else
cd /opt/verb/serfs
/opt/verb/serfs/mysqlex rcmail; wait
/bin/mv /opt/verb/serfs/rcmail.sql /var/www/email/roundcube/verb.rcmail.restore-originalbackedup.vbak.sql
/bin/cp -f /opt/verb/conf/sitemailpass /var/www/email/roundcube/sitemailpass-old
/bin/cp -f /opt/verb/conf/sitemailpath /var/www/email/roundcube/sitemailpath-old
cd /var/www/email
/opt/verb/serfs/vtxzin roundcube
/bin/mv roundcube.vtxz verb.roundcube.restore-originalbackedup.vbak
/bin/mv /var/www/email/verb.roundcube.restore-originalbackedup.vbak /var/www/vip/
/opt/verb/serfs/mysqlkilldb rcmail; wait
/opt/verb/serfs/mysqlkilluser rcmailusr; wait
/bin/rm -rf roundcube
fi

# Unpack the file
cd /var/www/vip
/bin/mv ${FILENAME} roundcube.vtxz
/opt/verb/serfs/vtxzout roundcube
/bin/mv roundcube /var/www/email/

# Activate the rc web server config settings
if [ ${RCFRESH} = "YES" ]; then
##DNS
 if /bin/grep -Fq "Webmail Defaults" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}; then
 sed -i "s/; Webmail Defaults/; Webmail Defaults\nrc\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\nrc\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}
 fi
/usr/sbin/a2ensite rc.${emailTLDURI}
/usr/sbin/apache2ctl graceful
 if /bin/grep -Fq "rc.${emailTLDURI}" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini; then
 /bin/echo "rc.${emailTLDURI} already declared for inkCert, moving on..."; else
 sed -i "/^domains =/ s/$/, rc.${emailTLDURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini
 fi
fi

# Restore and include RC settings in the sitemail config
. /var/www/email/roundcube/sitemailpass-old
. /var/www/email/roundcube/sitemailpath-old
/bin/sed -i "s/SITERCPASSAPG.*/SITERCPASSAPG=\"${SITERCPASSAPG}\"/g" /opt/verb/conf/sitemailpass
/bin/sed -i "s/SITERCPATH.*/SITERCPATH=\"${SITERCPATH}\"/g" /opt/verb/conf/sitemailpath
. /opt/verb/conf/sitemailpass
. /opt/verb/conf/sitemailpath

# Restore the database
/opt/verb/serfs/mysqlnewdb rcmail rcmailusr rcpass${SITERCPASSAPG}; wait
cd /var/www/email/roundcube
/opt/verb/serfs/mysqlin rcmail; wait
/bin/rm -f rcmail.sql
/bin/rm -f sitenameip*
/bin/rm -f sitemailpass*
/bin/rm -f sitemailpath*

# Own
/bin/chown -R www-data:www-data /var/www/email/roundcube

# Set the apache symlink
/bin/cp -R /var/www/html/0ne /var/www/html/${SITEEMAILTLD}.rc
/bin/ln -sfn /var/www/email/roundcube /var/www/html/${SITEEMAILTLD}.rc/${SITERCPATH}
/bin/chown -R www-data:www-data /var/www/html/${SITEEMAILTLD}.rc

# Finish
/bin/echo "Roundcube has been restored and all its backup files removed from this server.

It should be currently live at rc.${emailTLDURI}/${SITERCPATH}.

A backup of the previous Roundcube on this server has been saved in the vip folder just in case.
"
