#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This delets all backups from the server and their web-accessible symlinks

# How to use:
## ./backupdel


# Include the configs
. /opt/verb/conf/sitenameip

rm -f /var/www/vip/*.vbak
rm -f /var/www/html/${SITETLD}/*.vbak -f

