#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This restores a backup .vbak file from Nextcloud backed-up using backupnextcloud

# Prereq: Nextcloud must be installed via the installnextcloud serf on the new server first

# Instructions:
## The file can have any name, even if you changed it from the original, as long as it ends in .vbak
## The file MUST be uploaded to the "guru" folder, which can be done with vsftp installed and an ftpguru

# How to use:
## ./backuprestorenextcloud [filename]

# Eg:
## ./backuprestorenextcloud verb.nextcloud.sF52.vbak  # (This is for the backup file verb.nextcloud.sF52.vbak)


FILENAME=$1

# Include the site config
. /var/local/verb/configs/sitenameip

# Backup whatever the original status is
. /var/local/verb/configs/vapp.nextcloud
cd /var/www/vapps/nextcloud/data
/var/local/verb/serfs/mysqlvappout vapp.nextcloud; wait
mv /var/local/verb/configs/vapp.nextcloud .
cd /var/www/vapps/nextcloud
/var/local/verb/serfs/vtxzin data
mv data.vtxz verb.nextcloud.restore-originalbackedup.vbak
mv verb.nextcloud.restore-originalbackedup.vbak /var/www/guru/
/var/local/verb/serfs/mysqlkilldb ${APPDBASE}; wait
/var/local/verb/serfs/mysqlkilluser ${APPDDBUSR}; wait
rm -rf /var/www/vapps/nextcloud/data


# Unpack the file
cd /var/www/guru
mv ${FILENAME} data.vtxz
/var/local/verb/serfs/vtxzout data
cd data
rm -f index.html
rm -f nextcloud.log
rm -rf updater-data
cd ..
cp /var/www/vapps/nextcloud/data/index.html data/
cp /var/www/vapps/nextcloud/data/nextcloud.log data/
rm -rf /var/www/vapps/nextcloud/data
mv data /var/www/vapps/nextcloud/

# Restore and include the app config
mv /var/www/vapps/nextcloud/data/vapp.nextcloud /var/local/verb/configs/
. /var/local/verb/configs/vapp.nextcloud

# Restore the database
/var/local/verb/serfs/mysqlnewdb ${APPDBASE} ${APPDDBUSR} ${APPDDBPAS}; wait
cd /var/www/vapps/nextcloud/data
/var/local/verb/serfs/mysqlin ${APPDBASE}; wait
rm -f ${APPDBASE}.sql

# Own
chown -R www-data:www-data /var/www/vapps/nextcloud

# Finish
echo "Owncloud's user data has been restored and all its backup files removed from this server.

A backup of the previous Nextcloud data on this server has been saved in the guru folder just in case.

You will probably need to log into Nextcloud as an admin to disable and re-enable apps that show \"enabled\" but are not working.
"

