#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This restores a backup .zip file from owncloud backed-up using backupowncloud

# Prereq: ownCloud must be installed via the installowncloud serf on the new server first

# Instructions:
## The file can have any name, even if you changed it from the original, as long as it ends in .zip
## The file MUST be uploaded to the "guru" folder, which can be done with vsftp installed and an ftpguru

# How to use:
## ./backuprestoreowncloud [filename, NO .zip]

# Eg:
## ./backuprestoreowncloud verb.owncloud.sF52.vbak  # (This is for the backup file verb.owncloud.sF52.vbak.zip)


FILENAME=$1

# Include the site config
. /var/local/verb/configs/sitenameip

# Backup whatever the original status is
. /var/local/verb/configs/verbapp.owncloud
cd /var/local/verb/serfs
/var/local/verb/serfs/backupappdb ${APPDBASE} restore-originalbackedup -nl
mv verb.${APPDBASE}.restore-originalbackedup.vbak.sql /var/www/vapps/owncloud/data/
mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
DROP DATABASE ${APPDBASE};"
mv /var/local/verb/configs/verbapp.owncloud /var/www/vapps/owncloud/data/
cd /var/www/vapps/owncloud
zip -r verb.owncloud.restore-originalbackedup.vbak.zip data
mv verb.owncloud.restore-originalbackedup.vbak.zip /var/www/guru/

# Unzip the file
cd /var/www/guru
unzip ${FILENAME}.zip
rm -f ${FILENAME}.zip
cd data
rm -f index.html
rm -f owncloud.log
rm -rf updater-data
cd ..
cp /var/www/vapps/owncloud/data/index.html data
cp /var/www/vapps/owncloud/data/owncloud.log data
rm -rf /var/www/vapps/owncloud/data
mv data /var/www/vapps/owncloud/

# Restore and include the app config
mv /var/www/vapps/owncloud/data/verbapp.owncloud /var/local/verb/configs/
. /var/local/verb/configs/verbapp.owncloud

# Restore the database
/var/local/verb/serfs/mysqlnewdb ${APPDBASE} ${APPDDBUSR} ${APPDDBPAS}
mv /var/www/vapps/owncloud/data/${APPDBASE}.sql /var/local/verb/serfs/
cd /var/local/verb/serfs/
/var/local/verb/serfs/mysqlin ${APPDBASE}
rm -f ${APPDBASE}.sql

# Own
chown -R www-data:www-data /var/www/vapps/owncloud

# Finish
echo "Owncloud's user data has been restored and all its backup files removed from this server.

A backup of the previous ownCloud data on this server has been saved in the guru folder just in case.

You will probably need to log into ownCloud as an admin to disable and re-enable apps that show \"enabled\" but are not working.
"

