#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This backs up the entire email server, including folders and database

# How to use:
## ./backupvmail [securename 0-9, a-z, and A-Z only] [-nl for no link, optional]

# Eg:
## ./backupvmail VERB-NAMESPACE
## ./backupvmail 583-NAME
## ./backupvmail aF9 -nl


SECNAME=$1

# Include the configs
. /var/local/verb/configs/sitenameip

# Export the database
cd /var/vmail
/var/local/verb/serfs/mysqlex mail; wait

# Copy the config
cp /var/local/verb/configs/sitemailpath /var/vmail/sitemailpath-old
cp /var/local/verb/configs/sitemailpass /var/vmail/sitemailpass-old
cp /var/local/verb/configs/sitenameip /var/vmail/sitenameip-old

# Zip the directory
cd /var
/var/local/verb/serfs/vtxzin vmail
mv vmail.vtxz verb.vmail.${SECNAME}.vbak

# Move to web-download area
mv /var/verb.vmail.${SECNAME}.vbak /var/www/guru/

if [ "$2" = "-nl" ]
then
	echo "The email server data has been backed up to the 'guru' folder.
Note that the email server remains live."
exit 0
fi

ln -s /var/www/guru/verb.vmail.${SECNAME}.vbak /var/www/html/${SITETLD}/
chown -R www-data:www-data /var/www/html/${SITETLD}/verb.vmail.${SECNAME}.vbak
echo "The email server data has been backed up to the 'guru' folder and can also be downloaded at
http://${nameURI}/verb.vmail.${SECNAME}.vbak
Note that the email server remains live."

