#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This backs up the installed ownCloud webapp data folder by exporting the database, and siteconfig file into one downloadable zip file in the "guru" folder and symlinked to the main site domain.
## This is separate from other backups because ownCloud's developers make exporting difficult by more or less "welding" the app to the server. But, the export file is also smaller.
## This mainly backs up the user files and database, not the app itself.

# How to use:
## ./backupowncloud [securename 0-9, a-z, and A-Z only] [-nl for no link, optional]

# Eg:
## ./backupowncloud 583
## ./backupowncloud 7aJk -nl
## ./backupowncloud b


SECNAME=$1

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist
. /var/local/verb/configs/verbapp.owncloud

# Export the database
cd /var/local/verb/serfs
/var/local/verb/serfs/mysqlex ${APPDBASE}
mv /var/local/verb/serfs/${APPDBASE}.sql /var/www/vapps/owncloud/data/

# Copy the config
cp /var/local/verb/configs/verbapp.owncloud /var/www/vapps/owncloud/data/

# Zip the data directory
cd /var/www/vapps/owncloud
zip -r verb.owncloud.${SECNAME}.vbak.zip data
mv verb.owncloud.${SECNAME}.vbak.zip /var/www/guru/

# Finish
if [ "$3" = "-nl" ]
then
	echo "owncloud has been backed up to the 'guru' folder.

Note that the app remains live.
"
exit 0
fi

ln -s /var/www/guru/verb.owncloud.${SECNAME}.vbak.zip /var/www/html/${SITETLD}/
chown -R www-data:www-data /var/www/html/${SITETLD}/verb.owncloud.${SECNAME}.vbak.zip
echo "owncloud has been backed up to the 'guru' folder and can also be downloaded at:

http://${nameURI}/verb.owncloud.${SECNAME}.vbak.zip

Note that the app remains live.
"

