#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This adds the wildcard * subdomain alias non-SSL catch to a domain's Apache config.
## By definition of the web, this will conflict with the fixhttps

# How to use:
## ./fixalias [domain.tld or subdomain.domain.tld]


DOMAIN=$1

# Conflict check to see if "fixhttps" has already been added
if grep -q "INKHTTPSFIX=fixed" /etc/apache2/sites-available/${DOMAIN}.conf; then
echo "Can't fix alias because www fix is already in."
exit 0; fi

# Check to see if "fixalias" has already been added
if grep -q "INKALIASFIX=fixed" /etc/apache2/sites-available/${DOMAIN}.conf; then
service apache2 reload
	echo "${DOMAIN} already has the alias fix. The server was just reloaded so the site should work."
else

## Then add the config lines if it doesn't.
echo "

##INKALIASFIX=fixed
# Fixes alias
        <VirtualHost *:80>
        ServerAlias *.${DOMAIN}
        </VirtualHost>
##verbFIXalias" >> /etc/apache2/sites-available/${DOMAIN}.conf
service apache2 reload
	echo "${DOMAIN} now has alias fix for subdomains and is ready to go."
fi

