#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This redirects all http traffic to https
## This could conflict with fixalias, due to wildcard cert limits of Letsencrypt.

# How to use:
## ./fixhttps [domain.tld or subdomain.domain.tld]


DOMAIN=$1

# Conflict check to see if "fixalias" has already been added
if grep -q "##INKALIASFIX=fixed" /etc/apache2/sites-available/${DOMAIN}.conf; then
echo "Can't fix https because alias fix is already in."
exit 0; fi

# Check to see if "fixhttps" has already been added
if grep -q "##INKHTTPSFIX=fixed" /etc/apache2/sites-available/${DOMAIN}.conf; then
service apache2 reload
	echo "${DOMAIN} already has the alias fix. The server was just reloaded so the site should work."
else

## Then add the config lines if it doesn't.
echo "

##INKHTTPSFIX=fixed
# Fixes https
       <VirtualHost *:80>
               ServerName ${DOMAIN}
               Redirect permanent / https://${DOMAIN}/
       </VirtualHost>
##verbFIX" >> /etc/apache2/sites-available/${DOMAIN}.conf
service apache2 reload
	echo "${DOMAIN} now redirects all http traffic to SSL-secure https."
fi

