#!/bin/sh
#inkVerbSerf! verb.ink

# This removes the httpsfix and restores the Apache file to it's original http and https state

# How to use:
## ./fixhttp [domain.tld or subdomain.domain.tld]


DOMAIN=$1

# Verify that it has been fixed
if /bin/grep -q "##INKHTTPSFIX=fixed" /etc/apache2/sites-available/${DOMAIN}.conf; then

# Replace it with the original file
## From the original file
/bin/sed -i "/##inkHTTPremoved/r /etc/apache2/sites-available/${DOMAIN}.conf.verbhttpsfixed" /etc/apache2/sites-available/${DOMAIN}.conf
## Remove the old marker
/bin/sed -i '/##inkHTTPremoved/d' /etc/apache2/sites-available/${DOMAIN}.conf
## Remove the old settings
/bin/sed -i '/^##INKHTTPSFIX=fixed/,/^##verbFIXhttps/{/^##INKHTTPSFIX=fixed/!{/^##verbFIXhttps/!d}}' /etc/apache2/sites-available/${DOMAIN}.conf
/bin/sed -i '/##INKHTTPSFIX=fixed/d' /etc/apache2/sites-available/${DOMAIN}.conf
/bin/sed -i '/##verbFIXhttps/d' /etc/apache2/sites-available/${DOMAIN}.conf
## Put the original settings back
/bin/cat /etc/apache2/sites-available/${DOMAIN}.conf.verbhttpsfixed >> /etc/apache2/sites-available/${DOMAIN}.conf
/usr/sbin/apache2ctl graceful
/bin/rm /etc/apache2/sites-available/${DOMAIN}.conf.verbhttpsfixed
/bin/echo "${DOMAIN} now accepts http traffic."
## WordPress?
if [ -d "/var/www/vapps/wp.${DOMAIN}" ]; then
/bin/sed -i "/WP_SITEURL/d" /var/www/vapps/wp.${DOMAIN}/wp-config.php
/bin/sed -i "/WP_HOME/d" /var/www/vapps/wp.${DOMAIN}/wp-config.php
/bin/echo "define( 'WP_SITEURL', 'http://${DOMAIN}' );
define( 'WP_HOME', 'http://${DOMAIN}' );" >> /var/www/vapps/wp.${DOMAIN}/wp-config.php
fi

# If it's not already there, just exit
else
/bin/echo "${DOMAIN} doesn't have the https fix. Doing nothing."
exit 0
fi
