#!/bin/sh
#inkVerbSerf! verb.ink

# This redirects all http traffic to https
## This could conflict with fixalias, due to wildcard cert limits of Letsencrypt.

# How to use:
## ./fixhttps [domain.tld or subdomain.domain.tld]


DOMAIN=$1


# Check to see if "fixhttps" has already been added
if /bin/grep -q "##INKHTTPSFIX=fixed" /etc/apache2/sites-available/${DOMAIN}.conf; then
/usr/sbin/apache2ctl graceful
	/bin/echo "${DOMAIN} already has the https fix. The server was just reloaded so the site should work."
else
 if [ -f "/etc/apache2/sites-available/${DOMAIN}.conf.verbhttpsfixed" ]; then
/bin/echo "Something is wrong. The backup file for this https fix exists, but the config does not have the settings."
exit 6
 fi

## Then set the new config if it doesn't.
### Back up the http declaration and remove it (this way, the actual Apache file stays small, without loads of commented lines)
/bin/sed -n '/##inkHTTPstart/,/##inkHTTPstop/p' /etc/apache2/sites-available/${DOMAIN}.conf > /etc/apache2/sites-available/${DOMAIN}.conf.verbhttpsfixed
/bin/sed -i '/^##inkHTTPstart/,/^##inkHTTPstop/{/^##inkHTTPstart/!{/^##inkHTTPstop/!d}}' /etc/apache2/sites-available/${DOMAIN}.conf
/bin/sed -i '/##inkHTTPstart/d' /etc/apache2/sites-available/${DOMAIN}.conf
/bin/sed -i 's/##inkHTTPstop/##inkHTTPremoved/' /etc/apache2/sites-available/${DOMAIN}.conf
### Add the new lines
#### WordPress?
if [ -d "/var/www/vapps/wp.${DOMAIN}" ]; then
/bin/sed -i "/WP_SITEURL/d" /var/www/vapps/wp.${DOMAIN}/wp-config.php
/bin/sed -i "/WP_HOME/d" /var/www/vapps/wp.${DOMAIN}/wp-config.php
/bin/echo "define( 'WP_SITEURL', 'https://${DOMAIN}' );
define( 'WP_HOME', 'https://${DOMAIN}' );" >> /var/www/vapps/wp.${DOMAIN}/wp-config.php
fi

#### Apache
/bin/echo "

##INKHTTPSFIX=fixed
# Fixes https
       <VirtualHost *:80>
               ServerName ${DOMAIN}
                       RewriteEngine On
                       RewriteCond %{HTTP_HOST} ^(.*)$ [NC]
                       RewriteRule ^ https://%1%{REQUEST_URI} [L,NE,R=301]
       </VirtualHost>
##verbFIXhttps" >> /etc/apache2/sites-available/${DOMAIN}.conf
/usr/sbin/apache2ctl graceful
	/bin/echo "${DOMAIN} now redirects all http traffic to SSL-secure https."
fi
