#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This adds the www subdomain prefix non-SSL catch to a domain's Apache config.
## This could be set to run automatically at some point, so may not be necessary independently.
## This may eventually be depreciated altogether
## This serf is kept in service because the www fix may not be necessary, especially on secure-based domains or subdomains and an untested possibility remains of breaking other serfs if it is not run deliberately. Besides, needing "www" in front of domains ended in the year 2000. It could also be fixed via a DNS cname.


# How to use:
## ./fixwww [domain.tld or subdomain.domain.tld]


DOMAIN=$1

# Check to see if "fixwww" has already been added
if grep -Fxq "INKWWWFIX=fixed" /etc/apache2/sites-available/${DOMAIN}.conf
then
service apache2 reload
	echo "${DOMAIN} already has the www subdomain fix. The server was just reloaded so the site should work."
else

## Then add the config lins if it doesn't.
echo "

# Fixes www
## inkVerb needs this line INKWWWFIX=fixed
        <VirtualHost *:80>
        ServerName www.${DOMAIN}
        Redirect permanent / http://${DOMAIN}/
        </VirtualHost>" >> /etc/apache2/sites-available/${DOMAIN}.conf
service apache2 reload
	echo "${DOMAIN} now has the www subdomain fix and is ready to go."
fi
