#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This batch runs a revoke and uninstall of inkCert-Letsencrypt certs for a domain and replaces the Snakeoil certificate
## It also applies to all subdomains for that domain
## Prerequesite: inkcertdole (or both subscripts thereof: inkcertreqle, inkcertaddle)

# How to use:
## ./inkcertundole [domain.tld NO SUBDOMAINS]

#Eg:
## ./inkcertundole inkisaverb.com
## ./inkcertundole YOURNAME.verb.blue


DOMAIN=$1

# Check variables
if [ -z ${1} ]; then
echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Request and get the certs
/opt/verb/serfs/inkcertrevokele ${DOMAIN}

# Install the certs
/opt/verb/serfs/inkcertremoveallle ${DOMAIN}

