#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This script runs inkcertdole for all native Verber domains... verb.ink, verb.blue, etc.

# How to use:
## ./inkcertdole-all-verbs


# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist
. /var/local/verb/configs/sitetldstatus

# Verify that it's not a domain Dod Verber
if grep -Fq "SITENAME=DOMAIN_MOD-" /var/local/verb/configs/sitenameip; then
echo "Domain.MOD Verber NOTICE:
This is a Domain Mod Verber. Letsencrypt won't run for so many domains in too short of a time.

You must run inkcertdole one at a time for each uri, once you reach quota, wait a few days to continue.

Eg: ./inkcertdole ${inkURI}
"
exit 0; fi

# Let each run wait 1 second to avoid congesting the server
if [ $VERBpink=true ]; then
/var/local/verb/serfs/inkcertdole ${pinkURI}; fi
wait
if [ $VERBemail=true ]; then
/var/local/verb/serfs/inkcertdole ${emailURI}; fi
wait
if [ $VERBone=true ]; then
/var/local/verb/serfs/inkcertdole ${oneURI}; fi
wait
if [ $VERBink=true ]; then
/var/local/verb/serfs/inkcertdole ${inkURI}; fi
wait
if [ $VERBblue=true ]; then
/var/local/verb/serfs/inkcertdole ${blueURI}; fi
wait
if [ $VERBguru=true ]; then
/var/local/verb/serfs/inkcertdole ${guruURI}; fi
wait
if [ $VERBkiwi=true ]; then
/var/local/verb/serfs/inkcertdole ${kiwiURI}; fi
wait
if [ $VERBred=true ]; then
/var/local/verb/serfs/inkcertdole ${redURI}; fi
wait
if [ $VERBrocks=true ]; then
/var/local/verb/serfs/inkcertdole ${rocksURI}; fi
wait
if [ $VERBuno=true ]; then
/var/local/verb/serfs/inkcertdole ${unoURI}; fi

