#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This runs the auto updater for LE inkCert.
## The script is already written, this merely runs it via Serf

# How to use:
## ./inkcertupdatele-all


/var/local/verb/configs/inkcert/inkcertle-renew-all.sh

