#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This script removes the Apache credentials and certificates for inkCert-Certbot certs for a domain and replaces the Snakeoil certificate
## It also applies to all subdomains for that domain
## Prerequesite: inkcertrevokecb
## This is intended as a subscript of inkcertundole

# How to use:
## ./inkcertremovecb [domain.tld NO SUBDOMAINS]

#Eg:
## ./inkcertremovecb inkisaverb.com
## ./inkcertremovecb YOURNAME.verb.blue


DOMAIN=$1

# Check Apache config status
if grep -Fq "#INKVERB-INKCERT=DONE_CB" /etc/apache2/sites-available/${DOMAIN}.conf ; then
echo "Removing inkCert-CB configs from ${DOMAIN}..."
else
 if grep -Fq "#INKVERB-INKCERT=DONE_IC" /etc/apache2/sites-available/${DOMAIN}.conf ; then
  echo "Apache configs use inkCert Proper. Use: inkcertremove"
  exit 8
elif grep -Fq "#INKVERB-INKCERT=DONE_LE" /etc/apache2/sites-available/${DOMAIN}.conf ; then
  echo "Apache configs use inkCert-Letsencrypt. Use: inkcertremovecb"
  exit 8
 elif grep -Fq "#INKVERB-INKCERT=DONE_SC" /etc/apache2/sites-available/${DOMAIN}.conf ; then
  echo "Apache configs use inkCert Self-Cert. Use: inkcertremovesc"
  exit 8
 elif grep -Fq "#INKVERB-INKCERT=NO" /etc/apache2/sites-available/${DOMAIN}.conf ; then
  echo "inkCert certs aren't setup. Nothing to do."
  exit 0
 else
  echo "Something's really wrong. No inkCert, no non-inkCert either. I quit."
  exit 6
 fi
fi


# Apache
## Check that the certs are no longer live
if [ ! -d /etc/inkcert/le/live/${DOMAIN} ]; then
## Uncomment the Snakeoil cert configs
sed -i "s/#INKVERB-INKCERT-COMMENT-SSLCertificateFile/SSLCertificateFile/g" /etc/apache2/sites-available/${DOMAIN}.conf
sed -i "s/#INKVERB-INKCERT-COMMENT-SSLCertificateKeyFile/SSLCertificateKeyFile/g" /etc/apache2/sites-available/${DOMAIN}.conf

## Remove the inkCert cert liness
sed -i '/^#INKVERB-INKCERT=DONE_CB/,/^#INKVERB-INKCERT-stop/{/^#INKVERB-INKCERT=DONE_CB/!{/^#INKVERB-INKCERT-stop/!d}}' /etc/apache2/sites-available/${DOMAIN}.conf
sed -i '/#INKVERB-INKCERT=DONE_CB/#INKVERB-INKCERT=INK_REMOVED/' /etc/apache2/sites-available/${DOMAIN}.conf
sed -i '/#INKVERB-INKCERT-stop/d' /etc/apache2/sites-available/${DOMAIN}.conf
apache2ctl graceful

## Note to the config
sed -i "s/INKCERTED=DONE_CB/INKCERT=NO_REMOVED_CB/" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}

## Remove the certs
### live/
for i in /etc/inkcert/sc/live/${DOMAIN}/*.pem
do
rm  "$(readlink -f $i)"
rm "$i"
done
rm -rf /etc/inkcert/sc/live/${DOMAIN}
### archive/
for i in /etc/inkcert/sc/archive/${DOMAIN}/*.pem
do
rm  "$(readlink -f $i)"
rm "$i"
done
rm -rf /etc/inkcert/sc/archive/${DOMAIN}
### renewal/
rm -rf /etc/inkcert/le/renewal/${DOMAIN}.conf

# Finish
echo "inkCert has been uninstalled from ${DOMAIN}. Using Snakeoil certs."
exit 0
else

# If they are live
echo "Something's wrong...

The certs still seem to be live. Did you first run inkcertrevokele or sumply run inkcertundole?
"
fi
