#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This script runs doinkcert for all native Verber domains... verb.ink, verb.blue, etc.

# DEV NOTE: This should probably be removed because the DNS record for all verb namespaces is not presumed.

# How to use:
## ./inkcertdo-all-verbs


# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist
. /var/local/verb/configs/sitetldstatus

if [ $VERBemail=true ]; then
/var/local/verb/serfs/inkcertdo ${emailURI}; fi
wait
if [ $VERBone=true ]; then
/var/local/verb/serfs/inkcertdo ${oneURI}; fi
wait
if [ $VERBink=true ]; then
/var/local/verb/serfs/inkcertdo ${inkURI}; fi
wait
if [ $VERBblue=true ]; then
/var/local/verb/serfs/inkcertdo ${blueURI}; fi
wait
if [ $VERBguru=true ]; then
/var/local/verb/serfs/inkcertdo ${guruURI}; fi
wait
if [ $VERBkiwi=true ]; then
/var/local/verb/serfs/inkcertdo ${kiwiURI}; fi
wait
if [ $VERBpink=true ]; then
/var/local/verb/serfs/inkcertdo ${pinkURI}; fi
wait
if [ $VERBred=true ]; then
/var/local/verb/serfs/inkcertdo ${redURI}; fi
wait
if [ $VERBrocks=true ]; then
/var/local/verb/serfs/inkcertdo ${rocksURI}; fi
wait
if [ $VERBuno=true ]; then
/var/local/verb/serfs/inkcertdo ${unoURI}; fi

