#!/bin/bash
#inkVerbSerf! verb.ink
set -e

# This runs inkcertaddle for all domains and subdomains
## Prerequesite: Certs must be installed via inkCert or this will do nothing.

# NOTE: This is intended to be run by inkcertundole

# How to use:
## ./inkcertremoveallle [domain.tld or sub.domain.tld]


# For the domain
/var/local/verb/serfs/inkcertremovele ${DOMAIN}

# For any/all sub-domains
if [ -f /etc/apache2/sites-available/*.${DOMAIN}.conf ]; then
/var/local/verb/serfs/inkcertremovele *.${DOMAIN}
fi

