#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This script copies the postfix/dovecot configs to turn of inkCert SSL certs and use snakeoil certs instead

# How to use:
## ./inkcertdoemailoff 


# Include the config file
. /var/local/verb/configs/sitenameip

cp /var/local/verb/configs/site-files/email/dovecot/conf.d/10-ssl-SNAKEOIL.conf /etc/dovecot/10-ssl.conf
cp /var/local/verb/configs/site-files/email/postfix/main-SNAKEOIL.cf /etc/postfix/main.cf

