#!/bin/bash
#inkVerbSerf! verb.ink
set -e

# This installs inkCert-Letsencrypt Apache credentials for a given domain, including inkVerb namespace domains
## Prerequesite: inkcertreqle
## This is intended as a subscript of inkcertaddle or to add certs to specific Apache configs as they are installed after the fact, such as in updates.

# NOTE: This is intended to be run by inkcertdole, but can be run separately, such as for updates
# NOTE: If your domain and subdomains have the same certificate then run this only for the main domain

# How to use:
## ./inkcertaddle [domain.tld or sub.domain.tld] [DOMAIN OF CERTIFICATE IF DIFFERENT, ie: domain.tld]

# Eg:
## ./inkcertaddle NAME.verb.ink (will apply ONLY to NAME.verb.ink)
## ./inkcertaddle blog.NAME.verb.ink (BAD NEWS: this won't work!! blog.NAME.verb.ink does not have a certificate by itself, use: 'inkcertaddallle NAME.verb.ink')
## ./inkcertaddle blog.NAME.verb.ink NAME.verb.ink
## ./inkcertaddle inkisaverb.com (BAD NEWS: this won't work!! inkisaverb.com does not have a certificate by itself, use: 'inkcertaddallle inkisaverb.com')
## ./inkcertaddle poetryiscode.com inkisaverb.com (if the SSL cert for poetryiscode.com is included in the CN of the certificate for inkisaverb.com)


SITEDOMAIN=$1
CERTDOMAIN=$2

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist
. /var/local/verb/configs/inkcert/inkcertstatus

# Check variables
if [ -z $1 ]; then
echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Set variable for same certificate as domain (most all scenarios)
if [ -z $2 ]; then
CERTDOMAIN=$1
fi

# Certs should already be in place from inkcertreqle
## This is a test for the inkcert directories:
if [ ! -d "/etc/inkcert/le/live/${CERTDOMAIN}" ]; then
echo "Something's wrong...

inkCert-Letsencrypt certs were not installed for ${SITEDOMAIN} because the ${CERTDOMAIN} certs don't exist. Common problems can include:
  - DNS records: ${SITEDOMAIN} should point to ${SITEIP}
  - DNS for ${SITEDOMAIN} may need a \"wildcard\" * CNAME record that points to ${SITEDOMAIN} as the \"hostname\"
  - DNS records can take about 4 hours to have effect
  - You need to first run: inkcertreqle
  - Do not run inkcertreqle for individual subdomains with a shared certificate, but only for: ${blueURI}, ${rocksURI}, inkisaverb.com, etc.
  - The verb/configs/inkcert/cli-ini/ file for ${CERTDOMAIN} may not contain the subdomain you are using.
"
exit 22
fi

# Check Apache config status
if grep -Fq "#INKVERB-INKCERT=INK_NO" /etc/apache2/sites-available/${SITEDOMAIN}.conf ; then
echo "Setting inkCert configs for ${SITEDOMAIN}..."
else
 if grep -Fq "#INKVERB-INKCERT=DONE_LE" /etc/apache2/sites-available/${SITEDOMAIN}.conf ; then
 echo "Already certified by inkCert-LE: ${SITEDOMAIN}. Moving on..."
 exit 0
 else
  if grep -Fq "#INKVERB-INKCERT=DONE_IC" /etc/apache2/sites-available/${SITEDOMAIN}.conf ; then
  echo "Already certified by inkCert-IC: ${SITEDOMAIN}. Moving on..."
  exit 0
  else
   if grep -Fq "#INKVERB-INKCERT=NA" /etc/apache2/sites-available/${SITEDOMAIN}.conf ; then
   echo "inkCert certs do not apply here: ${SITEDOMAIN}. Moving on..."
   exit 0
   else
   echo "Something's really wrong with ${SITEDOMAIN}. No inkCert, no non-inkCert either. I quit here."
   exit 66
   fi
  fi
 fi
fi

# Stop Apache
apachectl -k graceful-stop
## Hard stop in case it doesn't work
service apache2 stop

# Comment the Snakeoil certs
sed -i "s/SSLCertificateFile/#INKVERB-INKCERT-COMMENT-SSLCertificateFile/g" /etc/apache2/sites-available/${SITEDOMAIN}.conf
sed -i "s/SSLCertificateKeyFile/#INKVERB-INKCERT-COMMENT-SSLCertificateKeyFile/g" /etc/apache2/sites-available/${SITEDOMAIN}.conf

# Insert the inkCert certs
sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_LE\n\t\tSSLCertificateFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/cert\.pem\n\t\tSSLCertificateKeyFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/privkey\.pem\n\t\tSSLCertificateChainFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/chain\.pem/g" /etc/apache2/sites-available/${SITEDOMAIN}.conf
service apache2 start

# Create the inkCert-DOMAIN config file
echo "#!/bin/sh
INKCERTED=DONE_LE" > /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${SITEDOMAIN}

# inkCert status & exit
if [ "${FIRSTINKCERTADDLE}" = "NOT_YET" ]; then
## Config status: first inkCert done
sed -i "s/FIRSTINKCERTADDLE=NOT_YET/FIRSTINKCERTADDLE=DONE/g" /var/local/verb/configs/inkcert/inkcertstatus
## Create the cron job
### Add inkCertLE's auto updater to the cron
echo "3 3 * * * root /var/local/verb/configs/inkcert/inkcertle-renew-all.sh" >> /var/local/verb/configs/verbcron
### Set cron to run the verbcron
cp /var/local/verb/configs/verbcron /etc/cron.d/verber
exit 0
fi

# Finish
echo "
${SITEDOMAIN} certs installed.
"

