#!/bin/bash
#inkVerbSerf! verb.ink
#set -e

# This batch runs inkCert Self-Cert creation and install scripts for a given domain, including inkVerb namespace domains
## It also applies to all subdomains for that domain
## Prereqesite: inkcertinstall

# How to use:
## ./inkcertdosc [domain.tld NO SUBDOMAINS]

#Eg:
## ./inkcertdosc inkisaverb.com
## ./inkcertdosc YOURNAME.verb.blue


DOMAIN=$1

# Check variables
if [ -z ${1} ]; then
echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Request and get the certs
/opt/verb/serfs/inkcertsc ${DOMAIN}; wait

# Install the certs
/opt/verb/serfs/inkcertaddsc ${DOMAIN}; wait

# Finish
echo "
Excellent!
Verify above exits - IMPORTANT NOTES: ... - Congratulations!

If so, then ${DOMAIN} and all subdomains are now live with inkCert Letsencrypt certificates.
"
