#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This creates a domain inkDNS zone file on this Verber

# How to use:
## ./inkdnsadddomain [domain]


DNSDOMAIN=$1

# Include the configs
. /var/local/verb/configs/sitenameip

# Check if already added
if [ -e "/var/local/verb/configs/inkdns/zones/${DNSDOMAIN}.db" ]; then
echo "The domain ${DNSDOMAIN} zone file has already been created. Use inkdnskilldomain to remove it."
exit 0; fi

# Copy the file
cp /var/local/verb/configs/inkdns/dnsdomain.db /var/local/verb/configs/inkdns/zones/${DNSDOMAIN}.db

# Replace the data
sed -i "s/hostdomain286/${DNSDOMAIN}/g" /var/local/verb/configs/inkdns/zones/${DNSDOMAIN}.db

# Set the Serial No
/var/local/verb/serfs/inkdnsserial ${DNSDOMAIN}

# Finish
echo "${DNSDOMAIN} DNS zone file created."

