#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This removes an existing domain inkDNS zone file from this Verber

# How to use:
## ./inkdnskilldomain [domain]


DNSDOMAIN=$1

# Include the configs
. /opt/verb/conf/sitenameip

# Check if added
if [ -e "/opt/verb/conf/inkdns/zones/db.${DNSDOMAIN}" ]; then
echo "The domain ${DNSDOMAIN} zone file has not been created. Use inkdnsadddomain to add it."
exit 0; fi

# Remove the records
rm -f /opt/verb/conf/inkdns/zones/db.${DNSDOMAIN}
rm -f /opt/verb/conf/inkdns/zones/nv.${DNSDOMAIN}

# Refresh zones & delete the global rDNS entry
if [ -f "/opt/verb/conf/inkdns/inkdnsstatus" ]; then
  . /opt/verb/conf/inkdns/inkdnsstatus
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
echo "${DNSDOMAIN} DNS zone file removed."
