#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This adds a subdomain A & AAAA records to an existing GURU DNS record in the inkDNS zone file on this Verber

# How to use:
## ./inkdnsaddgurusub [subdomain]


DNSSUBDOM=$1

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

# Check if already added
if grep -Fq "${DNSSUBDOM}.${guruURI}" /var/local/verb/configs/inkdns/zones/${guruURI}.db; then
echo "The subdomain ${DNSSUBDOM} has already been added to ${guruURI}. Use inkdnskillsub to remove it."
exit 0; fi

# Echo the record
echo "; Subdomain Records Added by inkDNS ${DNSSUBDOM}\.${guruURI}" >> /var/local/verb/configs/inkdns/zones/${guruURI}.db
echo "${DNSSUBDOM}\.${guruURI}\tIN  A\t\t${SITEIP}" >> /var/local/verb/configs/inkdns/zones/${guruURI}.db
echo "${DNSSUBDOM}\.${guruURI}\tIN  AAAA\t\t${SITEIPV6}" >> /var/local/verb/configs/inkdns/zones/${guruURI}.db

# Set the Serial No
/var/local/verb/serfs/inkdnsserial ${DNSDOMAIN}

# Finish
echo "The GURU subdomain ${DNSSUBDOM} has been added to the DNS zone file."

