#!/bin/sh
#inkVerbSerf! verb.ink

# This sets the main Inker as the backup DNS for this Verber
## The default backup nameservers are already ns0.inkisaverb.com and ns1.inkisaverb.com
## This can replace ns0.inkisaverb.com, but is not recommended
## To replace ns1.inkisaverb.com, use inkdnssetinker2

# How to use:
## ./inkdnssetinker [ IPv6 Address ] [ IPv4 Address ] [ domain - optional, rare ]

# Eg:
## ./inkdnssetinker
## ./inkdnssetinker -d 111.222.333.444 0000:ef89::2001
## ./inkdnssetinker -d 111.222.333.444
## ./inkdnssetinker -d -d 0000:ef89::2001
## ./inkdnssetinker ns2.inkisaverb.com
## ./inkdnssetinker ns.poetryiscode.com
## ./inkdnssetinker ns2.inkisaverb.com 111.222.333.444
## ./inkdnssetinker ns2.inkisaverb.com -d 0000:ef89::2001
## ./inkdnssetinker ns.poetryiscode.com 555.555.555.555 8001:0056::489a


DEFAULTns="1verb.ink.verb.ink"
INKERip4="104.248.208.98"
INKDERip6="2604:a880:2:d0:53:1001::"

# Check variables present
## Domain
if [ -z "$1"  || [ "$1" -d ]]; then
  /bin/echo "Inkder domain not specified; using default."
  NSDOMAIN="${DEFAULTns}"
else
  NSDOMAIN="$1"
fi
## IP4
if [ -z "$2" ] || [ "$2" -d ]; then
  /bin/echo "IP4 not specified; using default."
  NSIP4="${INKERip4}"
else
  NSIP4=$2
fi
## IP6
if [ -z "$3" ] || [ "$3" -d ]; then
  /bin/echo "IP6 not specified; using default."
  NSIP6="${INKDERip6}"
else
  NSIP6=$3
fi

# Set the changes
/bin/sed -i "s/SITEINKERDNS.*/SITEINKERDNS=\"${NSDOMAIN}\"/" /opt/verb/conf/sitenameip
/bin/sed -i "s/SITEINKERIP4.*/SITEINKERIP4=\"${NSIP4}\"/" /opt/verb/conf/sitenameip
/bin/sed -i "s/SITEINKERIP6.*/SITEINKERIP6=\"${NSIP6}\"/" /opt/verb/conf/sitenameip

# Finish
/bin/echo "Primary DNS Inker set to: ${NSIP4} & ${NSIP6} for ${NSDOMAIN}"
