#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This adds the mail subdomain A & AAAA records in the inkDNS zone file on this Verber

# How to use:
## ./inkdnsaddmail [domain]


DNSDOMAIN=$1

# Include the configs
. /var/local/verb/configs/sitenameip

# Check if already added
if grep -Fq "; Hostname Mail Record Defaults" /var/local/verb/configs/inkdns/zones/${DNSDOMAIN}.db; then
echo "Mail Record Defaults already added to . Use inkdnskillmail to remove them."
exit 0; fi

# Echo the records
echo "; Hostname Mail Record Defaults
email.${DNSDOMAIN}.	IN  CNAME	mail.${DNSDOMAIN}.
${DNSDOMAIN}.		IN  MX  50	mail.${DNSDOMAIN}.
mail.${DNSDOMAIN}.	IN  A		${SITEIP}
smtp.${DNSDOMAIN}.	IN  A		${SITEIP}
imap.${DNSDOMAIN}.	IN  A		${SITEIP}
pop3.${DNSDOMAIN}.	IN  A		${SITEIP}
pop2.${DNSDOMAIN}.	IN  A		${SITEIP}
pop.${DNSDOMAIN}.	IN  A		${SITEIP}
mail.${DNSDOMAIN}.	IN  AAAA	${SITEIPV6}
smtp.${DNSDOMAIN}.	IN  AAAA	${SITEIPV6}
imap.${DNSDOMAIN}.	IN  AAAA	${SITEIPV6}
pop3.${DNSDOMAIN}.	IN  AAAA	${SITEIPV6}
pop2.${DNSDOMAIN}.	IN  AAAA	${SITEIPV6}
pop.${DNSDOMAIN}.	IN  AAAA	${SITEIPV6}
;; End Mail Defaults" >> /var/local/verb/configs/inkdns/zones/${DNSDOMAIN}.db

# Set the Serial No
/var/local/verb/serfs/inkdnsserial ${DNSDOMAIN}

# Finish
echo "The Mail Record Defaults have been added to the ${DNSDOMAIN} DNS zone file."

