#!/bin/sh
#inkVerbSerf! verb.ink

# This removes a subdomain A & AAAA records from an existing ONE DNS record in the inkDNS zone file on this Verber

# How to use:
## ./inkdnskillonesub [subdomain]


DNSSUBDOM=$1

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Check if already added
if ! /bin/grep -Fq "${DNSSUBDOM}.${oneURI}" /opt/verb/conf/inkdns/zones/db.${oneURI}; then
/bin/echo "The subdomain ${DNSSUBDOM} has not been added to ${oneURI}. Use inkdnsaddsub to add it."
exit 0; fi

# Remove the records
/bin/sed -i "/; Subdomain Records Added by inkDNS ${DNSSUBDOM}\.${oneURI}/,+2d" /opt/verb/conf/inkdns/zones/db.${oneURI}
/bin/sed -i "/; PTR Subdomain Records Added by inkDNS ${DNSSUBDOM}\.${oneURI}/,+2d" /opt/verb/conf/inkdns/zones/nv.${oneURI}

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${DNSDOMAIN}

# Refresh zones
if [ -f "/opt/verb/conf/inkdns/inkdnsstatus" ]; then
  . /opt/verb/conf/inkdns/inkdnsstatus
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "The ONE subdomain ${DNSSUBDOM} has been removed from the DNS zone file."
