#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This adds a Vrk/Verber Client's public SSH key to "authorized_hosts" on the CA Verber
## If the key is not included in the initial command, it will be read interactively.
## Prerequisite: inknetaddvrkclient/inknetaddverberclient

# How to use:
## ./inknetaddclientkey [vrk/verber type] [Client Host/Name] ["FULL KEY" - in quotes! - optional]

# Eg: (for Verber)
## ./inknetaddclientkey verber joeyhost_joeysite_verb_ink
## ./inknetaddclientkey verber joeyhost.joeysite.verb.ink
## ./inknetaddclientkey verber joeyhost_joeysite_verb_ink "ssh-rsa AAAAOmIOMIWhfsdfENFSDFaffJLKfsSDJsdSDKjWdsfsadfOkEjMCAfdSDKFLOIjhWESF.....WWLKqhOIMhgbSDF boss@joey"
## ./inknetaddclientkey verber joeyhost.joeysite.verb.ink "ssh-rsa AAAAOmIOMIWhfsdfENFSDFaffJLKfsSDJsdSDKjWdsfsadfOkEjMCAfdSDKFLOIjhWESF.....WWLKqhOIMhgbSDF boss@joey"

# Eg: (for Vrk Station)
## ./inknetaddclientkey vrk joey_gCodingStationJoey
## ./inknetaddclientkey vrk joey@gCodingStationJoey
## ./inknetaddclientkey vrk joey_gCodingStationJoey "ssh-rsa AAAAOmIOMIWhfsdfENFSDFaffJLKfsSDJsdSDKjWdsfsadfOkEjMCAfdSDKFLOIjhWESF.....WWLKqhOIMhgbSDF joey@gCodingStationJoey"
## ./inknetaddclientkey vrk joey@gCodingStationJoey "ssh-rsa AAAAOmIOMIWhfsdfENFSDFaffJLKfsSDJsdSDKjWdsfsadfOkEjMCAfdSDKFLOIjhWESF.....WWLKqhOIMhgbSDF joey@gCodingStationJoey"


VTYPE=$1
VINAME=$2
VCKEY=$3
# Determine vrk or verber
if [ "${VTYPE}" = "vrk" ]; then
VCNAME="$(echo ${VINAME} | sed 's/\./_/g' | sed 's/@/_/g' )"
fi
if [ "${VTYPE}" = "verber" ]; then
VCNAME="$(echo ${VINAME} | sed 's/\./_/g')"
VCHOST="$(echo ${VINAME} | sed 's/_/\./g')"
VCURI="$(echo ${VCHOST} | rev | cut -d'.' -f-3 | rev)"
fi

if [ "${VTYPE}" != "vrk" ] && [ "${VTYPE}" != "verber" ] ; then
echo "You need to specify \"vrk\" or \"verber\". Read the instructions."; exit 22; fi

# Check if the Client has been added
if [ "${VTYPE}" = "vrk" ]; then
 if [ ! -e "/var/local/verb/configs/inknet/vrk/client.vrk.${VCNAME}.cnf" ]; then
 echo "You must add the Client first using: inknetaddvrkclient."; exit 22; fi
fi
if [ "${VTYPE}" = "verber" ]; then
 if [ ! -e "/var/local/verb/configs/inknet/verber/client.verber.${VCNAME}.cnf" ]; then
 echo "You must add the Client first using: inknetaddverberclient."; exit 22; fi
fi

# Include the configs
if [ "${VTYPE}" = "vrk" ]; then
. /var/local/verb/configs/inknet/vrk/client.vrk.${VCNAME}.cnf; fi
if [ "${VTYPE}" = "verber" ]; then
. /var/local/verb/configs/inknet/verber/client.verber.${VCNAME}.cnf; fi
. /var/local/verb/configs/inknet/ca.verber.cnf

# Prompt for the copy-paste
if [ -z "${VCKEY}" ]; then
echo "
 Activate Client key area...

A key looks something like this, but longer, notice front and end:
ssh-rsa AAAAOmIOMIWhWESF.....WWLKqIMhgbSDF joey@gCodingStationJoey

Please copy and paste the entire contents of the Client public key, then press <Enter>...
"
read CPKEY
VCKEY="${CPKEY}"
fi
if [ -z "${VCKEY}" ]; then
echo "
 Activate Client key area...

A key looks something like this, but longer, notice front and end:
ssh-rsa AAAAOmIOMIWhWESF.....WWLKqIMhgbSDF joey@gCodingStationJoey

Please copy and paste the entire contents of the Client public key, then press <Enter>...
"
read CPKEY
VCKEY="${CPKEY}"
fi
if [ -z "${VCKEY}" ]; then
echo "You aren't entering a key. I quit."; exit 55; fi

# Add the key
if [ "${VTYPE}" = "vrk" ]; then
echo "${VCKEY}" >> /var/local/ivapp/inknet/vrker/${CLIENTUSERNAME}/.ssh/authorized_keys
fi
if [ "${VTYPE}" = "verber" ]; then
echo "${VCKEY}.${VCURI}" >> /var/local/ivapp/inknet/verber/${CLIENTUSERNAME}/.ssh/authorized_keys
## Remove any duplication of the URI
sed -i "s/${VCURI}\.${VCURI}/${VCURI}/" /var/local/ivapp/inknet/verber/${CLIENTUSERNAME}/.ssh/authorized_keys
fi

# Finish
echo "Success! The Client key for ${CLIENTURI} has been added."

## Serf message
echo "
Now, you need to run inknetzipclientpkg

Follow the instructions."

