#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This deletes the config files for a secondary CA Verber

# How to use:
## ./inknetkillsecondarycaverber [CA verber name]

# Eg: (almost certainly exactly this, but verify from inkVerb instructions at registration and available Inkers, probably region-specific)
## ./inknetkillsecondarycaverber ink_ink_verb_ink (for ink namespace - the master Inker site)
## ./inknetaddsecondarycaverber john_john_verb_ink (for john namespace - if you want your own Verber to act as your keys)
## ./inknetaddsecondarycaverber ink2_ink_inkisaverb_com (for Domain Verber mod)


FULLKILLNAME=$1
KILLCAVERBERNAME=$(echo $FULLKILLNAME | cut -c1-18)

rm /opt/verb/conf/inknet/2cav.${KILLCAVERBERNAME}.cnf

# Finish
echo "The secondary CA Verber credentials for ${KILLCAVERBERNAME} have been deleted."

