#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This puts the login credentials into the right place for a Verber
## This assumes that the key has been already uploaded to the CA, signed, downloaded from the CA, and put on this Verber in the www/vip folder

# How to use:
## ./inknetaddcavpkg [sec path code from CA Verber - optional, will prompt if not entered here]


SECPATH=$1

# Include the config
. /opt/verb/conf/inknet/inker.client.cnf

# Verify working home directory
cd ~/

# If sec path not specified in command line
if [ -z ${1} ]; then
echo "Please copy-paste the code the CA Verber gave you, then press Enter."
read SECPATH
fi
if [ -z "$SECPATH" ]; then
echo "Please copy-paste the code the CA Verber gave you, then press Enter."
read SECPATH
fi
if [ -z "$SECPATH" ]; then
echo "You aren't entering the path. I quit."; exit 5; fi

# Download the package
wget -q https://${CAVERBERHOST}/inknet/${SECPATH}/${CLIENTNAME}.ink --no-check-certificate

# Unpack
mv ${CLIENTNAME}.ink ${CLIENTNAME}.vtxz
/opt/verb/serfs/vtxzout ${CLIENTNAME}
rm -f ${CLIENTNAME}.vtxz
. ~/${CLIENTNAME}/verbername
cp ~/${CLIENTNAME}/client.verber.${CLIENTNAME}.cnf /opt/verb/conf/inknet/client.${VERBERNAME}.inker.login.cnf
rm -rf ${CLIENTNAME}

# Finish
echo "The CA-signed cert for this Verber has been installed. This Verber may now use inkNet to connect to the Inker for other services, such as inkCert."

