#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This deletes a Vrk Client's profile and kills the inkNet JailKit user

# How to use:
## ./inknetkillvrkclient [username on machine] [machine name - AKA 'computer name']


KILLUSER=$1
KILLHOST=$2
KILLMACHINE="$(echo ${KILLHOST} | sed 's/\./_/g')"
KILLVRKCLIENT="${KILLUSER}_${KILLMACHINE}"

if [ -z "$2" ]; then
echo "Enter the user, a space, then the machine. Get your machine name with: hostname -f"; exit 55; fi

# Chek if it exists
if [ ! -e "/var/local/verb/configs/inknet/vrk/client.vrk.${KILLVRKCLIENT}.cnf" ]; then
echo "That Verber Client doesn't exist here."
exit 22; fi

# Include the Client's config
. /var/local/verb/configs/inknet/vrk/client.vrk.${KILLVRKCLIENT}.cnf

# Kill the inkNet ivApp user
userdel -r ${CLIENTUSERNAME}
rm -rf /var/local/ivapp/inknet/vrker/${CLIENTUSERNAME}

# Remove directories
rm -f /var/local/verb/configs/inknet/vrk/client.vrk.${KILLVRKCLIENT}.cnf

# Remove the SSH authorized_key file
rm -f /etc/ssh/authorized_keys/${CLIENTUSERNAME}

# Finish
echo "Done. ${KILLVRKCLIENT} pushed overboard and fed to the sharks."

