#!/bin/sh
#IVapp installer! verb.ink

# This adds an IVapp user with settings for inkNet

# Usertype options are: sail vrb vrk

# How to use:
## ./inkneivappadduser [user] [password] [usertype]


ADDINIVUSER=$1
ADDINIVPASS=$2
ADDINIVCONF=$3

# Add the user
/var/local/verb/donjon/ivappadduser ${ADDINIVUSER} ${ADDINIVPASS} /var/local/verb/inst/configs/inknet/ivinknet-${ADDINIVCONF}.conf

# Create the inkNet Client tool links
rm -rf /var/local/ivapp/inknet/sailor/${ADDINIVUSER}/tools
ln -sfn /var/local/verb/tools/sailor /var/local/ivapp/inknet/sailor/${ADDINIVUSER}/tools

