#!/bin/sh
#IVapp installer! verb.ink

# This adds an IVapp inkNet Sailor based on the Client Verber profile

# How to use:
## ./inknetivappnewclientsailor [Client Verber name - optional, only if secondary]

# Eg:
## ./inknetivappnewclientsailor ink2.ink.inkisaverb.com
## ./inknetivappnewclientsailor ink2_ink_inkisaverb_com


CA2URICFG=$1
SECONDARYCACFG="$(echo ${CA2URICFG} | sed 's/\./_/g')"

# Set the Client config
if [ -z "$1" ]; then
CLIENTCFG=/var/local/verb/configs/inknet/inker.client.cnf
else
CLIENTCFG=/var/local/verb/configs/inknet/2cav.${SECONDARYCACFG}.cnf
fi

# Include the Client config
. ${CLIENTCFG}

# Generate Sailor name
NEWINIVSAILORNAME=sail$(pwgen -s -1 -A 14)

# Add the Sailor
/var/local/verb/serfs/inknetivappaddsailor ${NEWINIVSAILORNAME}

# Set Sailor name in the config
sed -i "s/CLIENTSAILOR=.*/CLIENTSAILOR=\"${NEWINIVSAILORNAME}\"/g" ${CLIENTCFG}

# Get the CA Public key for this Client
## Based on primary or secondary
if [ -z "$1" ]; then
/var/local/verb/serfs/inknetaddcaverberpubkey
else
/var/local/verb/serfs/inknetaddcaverberpubkey ${CA2URICFG}
fi

