#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This installs inkNet onto the Verber and...
## sets it up as a CA Verber for Vrk Station Clients and
## sets it up as a CA Inker for Verber Client

# DEV NOTE:
## There are two CA keys
### in_ca_${CAVERBERNAME}_key to sign the host key on the same CA Verber itself, which authenticates this server to Clients
### in_cav_${CAVERBERNAME}_key gets signed

# How to use:
## ./inknetinstallca


# Verify that this CA Verber candidate is already a Client Verber itself
if [ ! -f /var/local/verb/configs/inknet/inker.client.cnf ]; then
echo "Not bad, Bucko. But, this must be a Verber Client, even to itself if need be, before it can become a CA to anything else.

First run, according to instructions: inknetmakeverberclient
"
exit 0; fi

# inkNet/inkCert prerequisites
if [ ! -f /var/local/verb/configs/inknet/ca.verber.cnf ]; then
echo "...installing CA now..."
/var/local/verb/serfs/inknetmakeca
fi

# Include the config
. /var/local/verb/configs/inknet/ca.verber.cnf

# Check if already installed or correctly ready
if [ "${INKNETSTATUS}" = "INSTALLED" ]; then
echo "inkNet is already installed, dude. Don't mess."
exit 0; fi
if [ "${INKNETSTATUS}" != "MADE_INSTALL_READY" ]; then
echo "Catostrophic failure. inkNetStatus should be MADE_INSTALL_READY or INSTALLED, but isn't either one.
Look at ca.verber.cnf to see what's up.
"
exit 0; fi

# Create the first CA Verber/Inker self-signing master keys for the settings added in inknetmakeca
/var/local/verb/serfs/inknetnewcaselfauthpubkey

# Create the first host key on this CA Verber, for the settings added in inknetmakeca
/var/local/verb/serfs/inknetnewcahostkey

# Install ivApp
/var/local/verb/serfs/inknetinstallivapp

# Set the inkNet config
sed -i "s/INKNETSTATUS=\"MADE_INSTALL_READY\"/INKNETSTATUS=\"INSTALLED\"/g" /var/local/verb/configs/inknet/ca.verber.cnf

# Finish
echo "
inkNet has been installed as a CA Verber and is ready to add Verber and Vrk Clients.
"

