#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This puts the login credentials into the right place for a Verber
## This assumes that the key has been already uploaded to the CA, signed, downloaded from the CA, and put on this Verber in the www/guru folder

# How to use:
## ./inknetaddcavpkg [sec path code from CA Verber - optional, will prompt if not entered here]


SECPATH=$1

# Include the config
. /var/local/verb/configs/inknet/inker.client.cnf

# Verify working home directory
cd ~/

# If sec path not specified in command line
if [ -z "$1" ]; then
echo "Please copy-paste the code the CA Verber gave you, then press Enter."
read SECPATH
fi

# Download the package
wget -q https://${CAVERBERHOST}.${CAVERBERURI}/inknet/${SECPATH}/${CLIENTNAME}.ink --no-check-certificate

# Unpack
mv ${CLIENTNAME}.ink ${CLIENTNAME}.zip
unzip ${CLIENTNAME}.zip
rm -f ${CLIENTNAME}.zip
. ~/${CLIENTNAME}/verbername
cp ~/${CLIENTNAME}/client.verber.${CLIENTNAME}.cnf /var/local/verb/configs/inknet/client.${VERBERNAME}.inker.login.cnf
rm -rf ${CLIENTNAME}

# Finish
echo "The CA-signed cert for this Verber has been installed. This Verber's root may now use the inkNet to connect to the Inker for other services, such as inkCert."

