#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This creates the package with username and password for the Client to download and install.
## Prerequisite: inknetaddverberclient/inknetaddvrkclient (the requesting client must already exist on this serveer as an inkNet jailed user)
## FYI, the client name refers to the file at verb/configs/inknet/v.../...

# DEV NOTE:
## This uses some variables interchangeably. This is for compatability since CLIENTNAME comes from the config file retrieved using VCNAME and VTYPE. Altering this could break the script later because of coterminous but separate jargon dependencies.

# How to use:
## ./inknetzipclientpkg [vrk/verber type] [client name]

# Eg: (for Verber)
## ./inknetzipclientpkg verber joeyhost_joeysite_verb_ink
## ./inknetzipclientpkg verber joeyhost.joeysite.verb.ink
## ./inknetzipclientpkg verber joeyhost_ink_inkisaverb_ink
## ./inknetzipclientpkg verber joeyhost.ink.inkisaverb.ink

# Eg: (for Vrk Station)
## ./inknetzipclientpkg vrk joey_gCodingStationJoe
## ./inknetzipclientpkg vrk joey@gCodingStationJoe
## ./inknetzipclientpkg vrk joey_joeyhost_joeysite_verb_ink
## ./inknetzipclientpkg vrk joey@joeyhost.ink.inkisaverb.ink


VTYPE=$1
ICNAME=$2
VCNAME="$(echo ${ICNAME} | sed 's/\./_/g' | | sed 's/@/_/g' )"

# Check variables
if [ -z "$2" ]; then
echo "You must enter a name. Check the instructions."; exit 55; fi

# Check if the Client has been added
if [ "${VTYPE}" = "vrk" ]; then
 if [ ! -e "/var/local/verb/configs/inknet/vrk/client.vrk.${VCNAME}.cnf" ]; then
 echo "You must add the Client first using: inknetaddvrkclient."
 exit 22
 fi
fi
if [ "${VTYPE}" = "verber" ]; then
 if [ ! -e "/var/local/verb/configs/inknet/verber/client.verber.${VCNAME}.cnf" ]; then
 echo "You must add the Client first using: inknetaddverberclient."
 exit 22
 fi
fi
if [ "${VTYPE}" != "verber" ] && [ "${VTYPE}" != "vrk" ]; then
echo "You must properly specify verber or vrk."; exit 55; fi

# Include the configs
if [ "${VTYPE}" = "vrk" ]; then
. /var/local/verb/configs/inknet/vrk/client.vrk.${VCNAME}.cnf; fi
if [ "${VTYPE}" = "verber" ]; then
. /var/local/verb/configs/inknet/verber/client.verber.${VCNAME}.cnf; fi
. /var/local/verb/configs/inknet/ca.verber.cnf

# Create the working directory
if [ ! -f ~/.ssh/inknet/${VCNAME} ]; then
mkdir ~/.ssh/inknet/${VCNAME}
fi

# Put everything in a temporary, restricted downloadable directory
SECPATH=$(pwgen -1 -s 10)
## Add the Client username configs
if [ "${VTYPE}" = "vrk" ]; then
cp /var/local/verb/configs/inknet/vrk/client.vrk.${VCNAME}.cnf ~/.ssh/inknet/${VCNAME}/
echo "#!/bin/sh
VERBERNAME=${IAMCANAME}" > ~/.ssh/inknet/${VCNAME}/verbername
fi
if [ "${VTYPE}" = "verber" ]; then
cp /var/local/verb/configs/inknet/verber/client.verber.${VCNAME}.cnf ~/.ssh/inknet/${VCNAME}/
echo "#!/bin/sh
VERBERNAME=${IAMCANAME}" > ~/.ssh/inknet/${VCNAME}/verbername
fi
cd ~/.ssh/inknet/
zip -r ${VCNAME}.zip ${VCNAME}
rm -rf ${VCNAME}
mkdir /var/www/html/${IAMCAHOST}/inknet/${SECPATH}
mv ${VCNAME}.zip ${VCNAME}.ink
mv ${VCNAME}.ink /var/www/html/${IAMCAHOST}/inknet/${SECPATH}

# For non-IP Vrk Stations
if [ "${CLIENTIP}" = "NOT_SET" ]; then
echo "
<Files ${VCNAME}.ink>
 AuthType Basic
 AuthName \"Password Protected Area\"
 AuthUserFile .htpasswd
 Require valid-user
</Files>
" > /var/www/html/${IAMCAHOST}/inknet/${SECPATH}/.htaccess
SECNAME=$(pwgen -1 -s 15)
SECPASS=$(pwgen -1 -s 15)
echo "${SECNAME}:${SECPASS}" > /var/www/html/${IAMCAHOST}/inknet/${SECPATH}/.htpasswd
echo "Great! Now, hurry up and get the file from this URL:
 https://${IAMCAHOST}/${SECPATH}/inknet/${VCNAME}.ink

 Login:    ${SECNAME}
 Password: ${SECPASS}

 It expires in about 30 minutes, so hurry!
"

# For IP Vrk Stations and Verbers
else
echo "
<Files ${VCNAME}.ink>
 Order deny,allow
 Deny from all
 Allow from ${CLIENTIP}
</Files>
" > /var/www/html/${IAMCAHOST}/inknet/${SECPATH}/.htaccess
chown -R www-data:www-data /var/www/html/${IAMCAHOST}/inknet/${SECPATH}/
echo "Great! Now, hurry up and enter this code with inknetaddcavpkg: ${SECPATH}

 It expires in about 30 minutes. Hurry!
"
fi

