#!/bin/sh
#IVapp installer! verb.ink
set -e

# This adds an IVapp user with settings for inkNet

# Usertype options are: sail vrb vrk

# How to use:
## ./inkneivappadduser [user] [password] [usertype]


ADDINIVUSER=$1
ADDINIVPASS=$2
ADDINIVCONF=$3

# Check if installed
if [ ! -d "/var/local/ivapp/inknet" ]; then
echo "ivApp is not instlled yet. I quit."; exit 22; fi

# Add the user
/var/local/verb/donjon/ivappadduser ${ADDINIVUSER} ${ADDINIVPASS} /var/local/verb/configs/inknet/ivinknet-${ADDINIVCONF}.conf

# Include the user type config
. /var/local/verb/configs/inknet/ivinknet-${ADDINIVCONF}.conf

# Create the inkNet Client tool links
rm -rf /var/local/ivapp/inknet/${IVAPPGROUPDIR}/${ADDINIVUSER}/tools
ln -sfn /var/local/verb/tools/${IVAPPGROUPDIR} /var/local/ivapp/inknet/${IVAPPGROUPDIR}/${ADDINIVUSER}/tools

