#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This creates and signs the host key for this CA Verber
## This is used by inknetinstallca (Run by itselt, this only refreshes from when inknetinstallca first used this)
## Dependent: inknetnewcahostkey
## Prerequisite: inknetmakeca

# This can be run any time without clients needing to re-authenticate the server

# How to use:
## ./inknetnewcahostkey


# Check and include the config
if [ ! -f /var/local/verb/configs/inknet/ca.verber.cnf ]; then
echo "Out of order. This is not a CA Verber yet.

First run inknetinstallca
"
exit 22
fi

# Include the config
. /var/local/verb/configs/inknet/ca.verber.cnf

# Verber Keys (on the same CA server)
## Create the inkNet host keys for Verber
ssh-keygen -t rsa -N "" -f /etc/ssh/inknet/inknet_CAverber_${IAMCANAME}_key
## CA signs the Verber host key
ssh-keygen -s ~/.ssh/inknet/ca/inknet_ca_${IAMCANAME}_key -N "" -I verber_${IAMCANAME} -h -n ${IAMCAHOST}.${IAMCAURI} -V +170w /etc/ssh/inknet/inknet_CAverber_${IAMCANAME}_key.pub
### Now exists: /etc/ssh/inknet/inknet_CAverber_${CAVERBERNAME}_key-cert.pub

# Restart
service ssh restart
service sshd restart

# Finish
echo "A new hostkey has been created and signed for this CA Verber."

