#!/bin/bash
#inkVerbSerf! verb.ink
#set -e

# This sets the inkVPN client and server email address
## This is used by inkvpninstall but can also be used by itself
## If the email is not set in the first argument, the default will be used by the Verber's nameURI

# How to use:
## ./inkvpncakey


# Include the config
. /opt/verb/conf/inkvpn/inkvpnstatus

# Check if the directory exists
if [ ! -d "/opt/verb/conf/inkvpn/certificates" ]; then
echo "The OpenVPN \"certificates\" directory does not exist, something's wrong. Bye."; exit 0; fi

# Remove keys and start everything over
cd /opt/verb/conf/inkvpn/certificates
source vars
./clean-all && ./build-ca --batch
./build-key-server --batch server
./build-dh
openvpn --genkey --secret keys/ta.key
rm -f /etc/openvpn/{server.crt,server.key,ca.crt,dh2048.pem,ta.key}
cp keys/{server.crt,server.key,ca.crt,dh2048.pem,ta.key} /etc/openvpn/

# Restart the OpenVPNserver if already installed
if [ "${INKVPNINSTALLED}" = "INSTALLED_OPENVPN" ]; then
  systemctl restart openvpn@server
## Check status for the record
  if [ "$(systemctl is-active openvpn@server)" = "active" ]; then
    echo "Good to go! Systemctl check on inkVPN says \"active\"!"
  else
    echo "Something's wrong. Systemctl says OpenVPN is not active. I quit."; exit 6
  fi
fi
