#!/bin/bash
#inkVerbSerf! verb.ink
#set -e

# This creates a temporary link for downloading the inkVPN client profile file
## This is run automatically by inkvpninstall and inkvpnclientkey, but can be run separately

# How to use:
## ./inkvpnclientdl


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Set the link names
cDIR="$(pwgen -s -1 128)"
mkdir -p /var/www/html/ink.serve/${SERVEDIR}/${cDIR}

# Link it to the Serve folder
ln -sfn /opt/verb/conf/inkvpn/certificates/clients/client.ovpn /var/www/html/ink.serve/${SERVEDIR}/${cDIR}/${SITENAME}-${SITETLD}-client.ovpn

# Finish
echo "The client OVPN profile is ready for download.
Get it here: https://${serveURI}/${SERVEDIR}/${cDIR}/${SITENAME}-${SITETLD}-client.ovpn
This download link will expire in at least 30 minutes."
