#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This runs installpostfix, installrc, and installpfa as one job
## Prerequisite: setupverb of course, and verbemail if you wish an email tld other than .email
## Check prerequisites for those

# OPTIONAL Prerequesite:
## If restoring from a backupvmail backup, the .vbak file must be in guru

# How to use:
## ./installvmail [RoundCube webmail path] [PostfixAdmin email pfa path] [PostfixAdmin setup secure option: "secure" otherwise use any other] [backup filename IF restoring from backupvmail backup, optional]

# Eg:
## ./installvmail roundcubesecretpath postfixadminsecretpath secure  # Secure, but no backup
## ./installvmail rcbase pfabase secure myemailfile.vbak # Backup and secure
## ./installvmail rcbase pfabase no myemailfile.vbak  # Backup, not secure
## ./installvmail rciscool pfarocks # Not secure, no backup



# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist
. /var/local/verb/configs/sitemailpass
. /var/local/verb/configs/sitemailpath

RC=$1
PFA=$2
EASYSECURE=$3
BACKUPRESTORE=$4

/var/local/verb/serfs/installpostfixvmail; wait
/var/local/verb/serfs/installpfa ${PFA} ${EASYSECURE}; wait
/var/local/verb/serfs/installrc ${RC}; wait

# Backup
if [ -n "$4"]; then
/var/local/verb/serfs/backupvmailrestore ${BACKUPRESTORE}; wait
fi

# inkCert
if grep -Fq "INKCERTED=NO" /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${emailTLDURI}; then
echo "Note: ${emailTLDURI} still doesn't have proper SSL certs. You can install, but will get SSL warnings due to \"self-signed\" or \"snakeoil\" certs.
You may ignore these warnings if you choose. If you want proper SSL certs, you still need to run inkCert for them.
"
fi
if grep -Fq "INKCERTED=DONE_LE" /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${emailTLDURI}; then
/var/local/verb/serfs/inkcertreqle ${emailURI} r; wait
/var/local/verb/serfs/inkcertaddallle ${emailURI}; wait
fi
if grep -Fq "INKCERTED=DONE_IC" /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${emailTLDURI}; then
/var/local/verb/serfs/inkcertreq ${emailURI} r; wait
/var/local/verb/serfs/inkcertaddall ${emailURI}; wait
fi

# Finished
if [ "${EASYSECURE}" != "secure" ]; then
    echo "
Everything looks good.
For setup, note:
- Use the install password 'inkverb77'
- Use any email you want admin, the admin password must include two numbers and two letters
- Then, login:
  - Add the domain: ${nameURI}
  - Create a user, such as me@${nameURI} etc
  - Use this new email and password to test the IMAP/SMTP connection in the third step of this next (webmail) setup process
Set up all this at:

 https://pfa.${emailTLDURI}/${PFA}/setup.php

- Then run ./postinstallpfa

Roundcube is ready to be installed at:

 https://rc.${emailTLDURI}/${RC}/installer

- Then run ./postinstallrc
"
fi

if [ "${EASYSECURE}" = "secure" ]; then
    	echo "
Everything looks good.

For PostfixAdmin setup, note:
- You must create your own password on the Setup page, then add it via: setpfapass
  Then...
- Use any email you want admin, the admin password must include two numbers and two letters
- Then, login:
  - Add the domain: ${nameURI}
  - Create a user, such as me@${inkURI} etc
  - Use this new email and password to test the IMAP/SMTP connection in the third step of this next (webmail) setup process

Set up all this for PostfixAdmin at:
 https://pfa.${emailTLDURI}/${PFA}/setup.php

- Then run ./postinstallpfa

Roundcube is also ready to be installed at:
 https://rc.${emailTLDURI}/${RC}/installer

- Then run ./postinstallrc
"
fi

