#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and installs OrangeHRM manually from inkisaverb.com/repo and linnks it to ....verb.blue

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installorangehrm [dbase] [dbuser] [dbpassword]


CVAPPNAME=orangehrm

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

DBASE=$1
DBUSER=$2
DBPASSWORD=$3
CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')

# Check if already installed
## Config
if [ -f /var/local/verb/configs/verbapp.${CVAPPNAME} ]; then
echo "This is already installed."
exit 0; fi
## Directory
if [ -d /var/www/vapps/${CVAPPNAME} ]; then
echo "OrangeHRM already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 22; fi

# Auto database
if [ -z $3 ]; then
DBPASSWORD=$(pwgen -s -1 10); fi
if [ -z $1 ]; then
DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
if [ -z $2 ]; then
DBUSER=${DBASE}; fi

# Download and unpack the latest checked version from inkisaverb.com/repo
cd /var/www/vapps
/var/local/verb/serfs/inkget ${CVAPPNAME}.current
unzip ${CVAPPNAME}.current.zip
rm -f ${CVAPPNAME}.current.zip
mkdir /var/www/vapps/${CVAPPNAME}/lib/logs
mkdir /var/www/vapps/${CVAPPNAME}/symfony/cache
mkdir /var/www/vapps/${CVAPPNAME}/symfony/log
rm -rf /var/www/html/red.hrm
ln -s /var/www/vapps/${CVAPPNAME} /var/www/html/red.hrm
chown -R www-data:www-data /var/www/html/red.hrm
chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}

# Create the database and credentials
mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
FLUSH PRIVILEGES;"

# Config files
## Preconfig setup is currently disabled until OrangeHRM installation allows, but this would be a start:
#cp /var/www/vapps/orangehrm/lib/confs/Conf.php-distribution /var/www/vapps/orangehrm/lib/confs/Conf.php
#sed -i "s/dbname   = 'hr_mysql'/dbname   = '${DBASE}'/g" /var/www/vapps/orangehrm/lib/confs/Conf.php
#sed -i "s/dbuser   = 'root'/dbuser   = '${DBUSER}'/g" /var/www/vapps/orangehrm/lib/confs/Conf.php
#sed -i "s/dbpass   = 'orangehrm'/dbpass   = '${DBPASSWORD}'/g" /var/www/vapps/orangehrm/lib/confs/Conf.php

# Firewall
ufw allow 3306

# Write the config for backup
echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/verbapp.${CVAPPNAME}

echo "These are setup:

Database Host Name: localhost
Database: ${DBASE}
OrangeHRM Database user (and Privileged user if applicable, use the same): ${DBUSER}
Database user password: ${DBPASSWORD}

*Select \"Existing database\" in setup to make life easier, if you want.
*Enable Data Encryption? - Probably NOT!

Go to http://hrm.${redURI} to install.
"

