#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This installs Ampache from inkisaverb.com/repo and links it to ampache....verb.kiwi

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installampache [dbase] [dbuser] [dbpassword]


CVAPPNAME=ampache

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

DBASE=$1
DBUSER=$2
DBPASSWORD=$3

# Auto database
if [ -z $3 ]; then
DBPASSWORD=$(pwgen -s -1 10); fi
if [ -z $1 ]; then
DBASE=${CVAPPNAME}$(pwgen -s -1 6); fi
if [ -z $2 ]; then
DBUSER=${DBASE}; fi

# Install
cd /var/www/vapps
/var/local/verb/serfs/inkget ${CVAPPNAME}.current
unzip ${CVAPPNAME}.current.zip
rm -f ${CVAPPNAME}.current.zip
rm -rf /var/www/html/kiwi.ampache
ln -s /var/www/vapps/${CVAPPNAME} /var/www/html/kiwi.ampache
chown -R www-data:www-data /var/www/html/kiwi.ampache
chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}

# Create the database user and credentials
mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON *.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"

# Ampache config file
## All of this works, but fools the app into thinking it is fully installed
#cp /var/www/vapps/ampache/config/ampache.cfg.php.dist /var/www/vapps/ampache/config/ampache.cfg.php
#sed -i "s/database_name = ampache/database_name = ${DBASE}/g" /var/www/vapps/ampache/config/ampache.cfg.php
#sed -i "s/database_username = username/database_username = ${DBUSER}/g" /var/www/vapps/ampache/config/ampache.cfg.php
#sed -i "s/database_password = password/database_password = ${DBPASSWORD}/g" /var/www/vapps/ampache/config/ampache.cfg.php
## Add the tables to the database
#mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf ${DBASE} < /var/www/vapps/ampache/sql/ampache.sql

# Write the config for backup
echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/verbapp.${CVAPPNAME}

echo "These are setup:

Database Name: ${DBASE}
MySQL Hostname: localhost
MySQL port: (leave blank)
MySQL Administrative Username: ${DBUSER} (not root)
MySQL Administrative Password: ${DBPASSWORD}

*UnCheck \"Create Database\"
*Check \"Create Tables (ampache.sql)\" (no change)
*Check \"Create Database User\"
 ...and enter this information:

Ampache Database Username:	${DBUSER}
Ampache Database User Password:	${DBPASSWORD}

*Click \"Insert Database\"

Next page: All info should be correct already

*DO NOT make any changes for \"Database connection\"

*Players: iTunes, WebDAV, etc. can be enabled now or later in Admin > Server Config > System

*Click \"Create Config\"
...And go from there.

*Make sure you look through Admin areas for some important options after you complete the installation and login.

Go to http://ampache.${kiwiURI} to install.
"

