#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and installs the current verified version of suiteCRM from inkisaverb.com/repo to crm.your-name.verb.red

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installsuitecrm [dbuser] [dbpassword]


CVAPPNAME=suitecrm

DBASE=$1
DBUSER=$2
DBPASSWORD=$3
CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')

# Check if already installed
## Config
if [ -f /var/local/verb/configs/verbapp.${CVAPPNAME} ]; then
echo "This is already installed."
exit 0; fi
## Directory
if [ -d /var/www/vapps/${CVAPPNAME} ]; then
echo "SuiteCRM already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 22; fi

# Auto database
if [ -z $3 ]; then
DBPASSWORD=$(pwgen -s -1 10); fi
if [ -z $1 ]; then
DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
if [ -z $2 ]; then
DBUSER=${DBASE}; fi

# Include the config file
. /var/local/verb/configs/sitenameip

# This does not create a database, only an administrator since suiteCRM will create that automatically

# Download and unpack the latest checked version from inkisaverb.com/repo
cd /var/www/vapps
/var/local/verb/serfs/inkget ${CVAPPNAME}.current
unzip ${CVAPPNAME}.current.zip
rm -f ${CVAPPNAME}.current.zip
cd /var/www/html
rm -rf red.crm
ln -s /var/www/vapps/${CVAPPNAME} /var/www/html/red.crm
chown -R www-data:www-data /var/www/html/red.crm
chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}

# Create the database user and credentials
mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON *.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"

# Write the config for backup
echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/verbapp.${CVAPPNAME}

echo "These are setup:

Database: ${DBASE}
Host Name: localhost (do not use crm....verb.red)
Database user: ${DBUSER}
Database password: ${DBPASSWORD}

*The SuiteCRM installer can be finicky. Be mindful of all details. Copy-paste into fields whenever possible.

*Choose \"Provide Existing User\" BEFORE entering above information.

Go to the http://crm.${SITENAME}.verb.red site to install.
"

