#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and installs Nextcloud manually from inkisaverb.com/repo and linnks it to ....verb.blue

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installnextcloud [latest/repo] [dbase] [dbuser] [dbpassword]

# Eg:
## ./installnextcloud repo
## ./installnextcloud latest bestdbase trump besteverpass



CVAPPNAME=nextcloud

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

LATREP=$1
DBASE=$2
DBUSER=$3
DBPASSWORD=$4
CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')

# Check if already installed
## Config
if [ -f /var/local/verb/configs/vapp.${CVAPPNAME} ]; then
echo "This is already installed."
exit 0; fi
## Directory
if [ -d /var/www/vapps/${CVAPPNAME} ]; then
echo "Nextcloud already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 22; fi

# Auto database
if [ -z ${4} ]; then
DBPASSWORD=$(pwgen -s -1 10); fi
if [ -z ${2} ]; then
DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
if [ -z ${3} ]; then
DBUSER=${DBASE}; fi

# Do it
cd /var/www/vapps
## Get and unpack
echo "Getting Nextcloud, this could take a minute or so..."
### Repo version ('stable' inkVerb recommendation)
if [ ${LATREP}="repo" ]; then
/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
rm -rf nextcloud
/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
### Latest Release Candidate version (default)
elif [ -z ${1} ] || [ ${LATREP}="latest" ]; then
wget https://download.nextcloud.com/server/daily/latest.tar.bz2
if [ ! -f latest.tar.bz2 ]; then
echo "Can't download Nextcloud. I quit."
exit 44; fi
rm -rf nextcloud
tar -xvjf latest.tar.bz2
rm -f latest.tar.bz2
fi
## Install it
rm -rf /var/www/html/blue.nextcloud
ln -sfn /var/www/vapps/${CVAPPNAME} /var/www/html/blue.nextcloud
chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
chown -R www-data:www-data /var/www/html/blue.nextcloud
## Run the Nextcloud script
/var/local/verb/donjon/nextcloudprep.sh; wait
## Set up cron for updates
echo "*/15  *  *  *  * www-data php -f /var/www/vapps/nextcloud/cron.php" > /etc/cron.d/nextcloud
#chmod 644 /etc/cron.d/nextcloud
chmod 755 /etc/cron.d/nextcloud

# Create the database and credentials
mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
FLUSH PRIVILEGES;"

# Write the config for backup
echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}

echo "These are setup:

Database user: ${DBUSER}
Database password: ${DBPASSWORD}
Database name: ${DBASE}
Host: localhost

*Don't make any other changes during the install!

Go to https://nextcloud.${blueURI} to install.

After, you may want to run setnextcloudbfdoff to disable brute force detection in order to allow some client apps to work. You can always turn it on again with setnextcloudbfdon
"

