#!/bin/sh
#inkVerbSerf! verb.ink

# This installs postfix admin
## Prerequisite: verbemail IF using a verb domain other than verb.email
## Prerequisite: installpostfix, installrc

# How to use:
## ./installpfa [path folder] [secure option]
### PostfixAdmin setup secure option: use "secure" for a password required, otherwise anything else including empty

# Eg: (To use at pfa.NAME.verb.email/mysecretpath do:)
## ./installpfa mysecretpath
## ./installpfa mysecretpath secure


CVAPPNAME=postfixadmin
# Include the config files
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitemailpass
. /opt/verb/conf/sitemailpath

# Check dependencies and to see if already installed
if [ ${SITEMAILSTATUS} != "VMAIL_SERVER" ]; then
/bin/echo "
The email server must be installed first. Run: installpostfix
"
exit 8; fi
if [ ${SITEPFAPATH} = "PFA_NOT_ALLOWED" ]; then
/bin/echo "
This is a backup email server and PostfixAdmin is not allowed.
"
exit 0; fi
if [ ${SITEPFAPATH} != "PFA_NOT_INSTALLED" ]; then
/bin/echo "
PostfixAdmin is already installed.
"
exit 0; fi
if /bin/grep -Fq "Webmail Defaults" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}; then
/bin/echo "Proceeding..."; else
/bin/echo "
Webmail Defaults not declared in the DNS zone file. This won't work.
"
exit 8; fi

# Options & secure path
if [ -n "$1" ]; then
PFAFOLDER=$1
else
PFAFOLDER="$(/usr/bin/pwgen -0 5 1)"
fi
PFAPASS=$2

# Download from repo
cd /var/www/email
/opt/verb/serfs/inkget ${CVAPPNAME}; wait
### Check
/opt/verb/serfs/inkget ${CVAPPNAME} check
if [ "$?" = 4 ]; then
/bin/echo "Repo failed to retrieve the file."
exit 4; fi
if [ ! -f ${CVAPPNAME}.vtxz ]; then
/bin/echo "Failed to retrieve from the repo."
exit 4; fi

/bin/rm -rf ${CVAPPNAME}
/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
## Fix a bug
/bin/mkdir -p /var/www/email/postfixadmin/templates_c

# Settings
## Whether secure or standard password
### If using 'secure', you must set the hash via pfapass
if [ "${PFAPASS}" != "secure" ]; then
    cp /opt/verb/conf/lab/vmail/postfixadmin/postfixadmin286-config.inc.php /var/www/email/postfixadmin/config.local.php
fi

if [ "${PFAPASS}" = "secure" ]; then
    cp /opt/verb/conf/lab/vmail/postfixadmin/postfixadmin286-secure-config.inc.php /var/www/email/postfixadmin/config.local.php
fi

# Settings
/bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /var/www/email/postfixadmin/config.local.php
/bin/sed -i "s/nameURI286/${nameURI}/g" /var/www/email/postfixadmin/config.local.php
/bin/sed -i "s/mailpassword/mailpass${SITEMAILPASSAPG}/g" /var/www/email/postfixadmin/config.local.php
/bin/sed -i "s/rcfolder286/${SITERCPATH}/g" /var/www/email/postfixadmin/config.local.php
/bin/sed -i "s/pfafolder286/${PFAFOLDER}/g" /var/www/email/postfixadmin/config.local.php

# Copy the branding files
/bin/cp /opt/verb/conf/lab/vmail/postfixadmin/pfapics/images/logo-ink.png /var/www/email/postfixadmin/public/images/

# Set Apache
/bin/cp -R /var/www/html/0ne /var/www/html/${SITEEMAILTLD}.pfa; wait
/bin/ln -sfn /var/www/email/postfixadmin/public /var/www/html/${SITEEMAILTLD}.pfa/${PFAFOLDER}; wait
/bin/chown -R www-data:www-data /var/www/html/${SITEEMAILTLD}.pfa; wait
/bin/chown -R www-data:www-data /var/www/email/postfixadmin; wait
/bin/sed -i "s/; Webmail Defaults/; Webmail Defaults\npfa\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\npfa\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}
/usr/sbin/a2ensite pfa.${emailTLDURI}
/usr/sbin/apache2ctl graceful

# Write the config
/bin/sed -i "s/SITEPFAPATH.*/SITEPFAPATH=\"${PFAFOLDER}\"/g" /opt/verb/conf/sitemailpath

# inkCert
## This adds the declared domain to the end of the "domains =" line
/bin/sed -i "/^domains =/ s/$/, pfa.${emailTLDURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini

# Finished
if [ "${PFAPASS}" = "secure" ]
then
	/bin/echo "
Everything looks good.

For setup, note:
- You must create your own password on the Setup page, then add it via: setpfapass
  Then...
- Use any email you want admin, the admin password must include two numbers and two letters
- Then, login:
  - Add the domain: ${nameURI}
  - Create a user, such as me@${inkURI} etc
  - Use this new email and password to test the IMAP/SMTP connection in the third step of this next (webmail) setup process

Set up all this at:
 https://pfa.${emailTLDURI}/${PFAFOLDER}/setup.php

- Then run ./postinstallpfa
"
exit 0
fi

/bin/echo "
Postfix Admin is installed and ready to be set up.

For setup, note:
- Use the install password 'inkverb77'
- Use any email you want admin, the admin password must include two numbers and two letters
- Then, login:
  - Add the domain: ${nameURI}
  - Create a user, such as me@${nameURI} etc
  - Use this new email and password to test the IMAP/SMTP connection in the third step of this next (webmail) setup process

Set up all this at:
 https://pfa.${emailTLDURI}/${PFAFOLDER}/setup.php
- Then run ./postinstallpfa
"

