#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This Collabora Online to be used with Nextcloud
## Thanks for the awesome instructions from: https://nextcloud.com/collaboraonline/

# How to use:
## ./installcollaboraonline [port - optional, if other than 9980]


CVAPPNAME=collaboraonline

## Set the port
if [ -z "$1" ]; then
PORT=9980
else
PORT=$1
fi

# Check if already installed
if [ -f /var/local/verb/configs/verbapp.${CVAPPNAME} ]; then
echo "This is already installed. I quit."
exit 0; fi

# Include the config file
. /var/local/verb/configs/sitenameip

# Make sure Docker is installed
/var/local/verb/serfs/installdocker

# Install it
docker pull collabora/code
			docker run -t -d -p 127.0.0.1:${PORT}:${PORT} -e 'domain=nextcloud\\.${SITENAME}\\.verb\\.blue' --restart always --cap-add MKNOD collabora/code

# Firewall
ufw allow ${PORT}

# Apache2
## Enable mods
a2enmod proxy
a2enmod proxy_wstunnel
a2enmod proxy_http
a2enmod ssl
## Config files
cp /var/local/verb/configs/site-files/collabora.${SITENAME}.verb.blue.conf-collabora /etc/apache2/sites-available/collabora.${SITENAME}.verb.blue.conf
sed -i "s/por286/${PORT}/g" /etc/apache2/sites-available/collabora.${SITENAME}.verb.blue.conf
## inkCert is already installed (check first to avoid errors, apply inkCert-LE or inkCert Proper as needed)
if grep -Fq "#INKVERB-INKCERT=DONE_LE" /etc/apache2/sites-available/${SITEDOMAIN}.conf; then 
/var/local/verb/serfs/inkcertaddle collabora.${SITENAME}.verb.blue ${SITENAME}.verb.blue
fi
if grep -Fq "#INKVERB-INKCERT=DONE_IC" /etc/apache2/sites-available/${SITEDOMAIN}.conf; then
/var/local/verb/serfs/inkcertadd collabora.${SITENAME}.verb.blue
fi
## Reload
service apache2 reload

# Write the config for status
echo "#!/bin/sh
COVAPPSTATUS=\"INSTALLED\"
COPORT=${PORT}
COHOST=\"nextcloud.${SITENAME}.verb.blue\"" > /var/local/verb/configs/verbapp.${CVAPPNAME}

echo "Collabora Online is now installed...

Next:
1. Login as an admin to https://nextcloud.${SITENAME}.verb.blue to enable the Collabora Online office app.
2. Finish the settings: Admin > Collabora Online > Collabora Online server: https://collabora.${SITENAME}.verb.blue
"

