#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This Collabora Online to be used with Nextcloud
## Thanks for the awesome instructions from: https://nextcloud.com/collaboraonline/

# How to use:
## ./installcollaboraonline [port - optional, if other than 9980]


CVAPPNAME=collaboraonline

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

## Set the port
if [ -z ${1} ]; then
PORT=9980
else
PORT=$1
fi

# Check if already installed
if [ -f /opt/verb/conf/vapp.${CVAPPNAME} ]; then
echo "This is already installed. I quit."
exit 0; fi

# Make sure Docker is installed
/opt/verb/serfs/installdocker
wait

# Install it
docker pull collabora/code
docker run -t -d -p 127.0.0.1:${PORT}:${PORT} -e "domain=nc.${blueURI}" --restart always --cap-add MKNOD collabora/code

# Firewall
ufw allow ${PORT}

# Apache2
## Enable mods
a2enmod proxy
a2enmod proxy_wstunnel
a2enmod proxy_http
a2enmod ssl
## Reload
apache2ctl graceful

# Write the config for status
echo "#!/bin/sh
COVAPPSTATUS=\"INSTALLED\"
COPORT=${PORT}
COHOST=\"nc.${blueURI}\"" > /opt/verb/conf/vapp.${CVAPPNAME}

echo "Collabora Online is now installed...

Next:
1. Login as an admin to https://nc.${blueURI} to enable the Collabora Online office app.
2. Finish the settings: Settings > Administration > Collabora Online > Collabora Online server: https://collabora.${blueURI}:${PORT}
"

