#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and installs Nextcloud manually from inkisaverb.com/repo and linnks it to ....verb.blue

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installnextcloud [dbase] [dbuser] [dbpassword]


CVAPPNAME=nextcloud

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

DBASE=$1
DBUSER=$2
DBPASSWORD=$3
CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')

# Check if already installed
## Config
if [ -f /var/local/verb/configs/verbapp.${CVAPPNAME} ]; then
echo "This is already installed."
exit 0; fi
## Directory
if [ -d /var/www/vapps/${CVAPPNAME} ]; then
echo "Nextcloud already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 22; fi

# Auto database
if [ -z $3 ]; then
DBPASSWORD=$(pwgen -s -1 10); fi
if [ -z $1 ]; then
DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
if [ -z $2 ]; then
DBUSER=${DBASE}; fi

# Do it
cd /var/www/vapps
## Get and unpack
/var/local/verb/serfs/inkget ${CVAPPNAME}.current
unzip ${CVAPPNAME}.current.zip
rm -f ${CVAPPNAME}.current.zip
rm -rf /var/www/html/blue.nextcloud
ln -sfn /var/www/vapps/${CVAPPNAME} /var/www/html/blue.nextcloud
chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
chown -R www-data:www-data /var/www/html/blue.nextcloud
## Run the Nextcloud script
/var/local/verb/donjon/nextcloudprep.sh
## Set up cron for updates
echo "*/15  *  *  *  * www-data php -f /var/www/vapps/nextcloud/cron.php" > /etc/cron.d/nextcloud

# Create the database and credentials
mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
FLUSH PRIVILEGES;"

# Write the config for backup
echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/verbapp.${CVAPPNAME}

echo "These are setup:

Database user: ${DBUSER}
Database password: ${DBPASSWORD}
Database name: ${DBASE}
Host: localhost

*Don't make any other changes during the install!

Go to https://nextcloud.${blueURI} to install.
"

