#!/bin/sh
#inkVerbSerf! verb.ink

# This installs Postfix as the email server wtih Dovecot and OpenDKIM
## Prerequisite: sertupverb
## This only performs basic back-end server setup and creates no mail accounts
## Once this is done it is set for the server permanently.

# How to use:
## ./installpostfixvmail


# Include the config files
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitemailpath

# Check to see if already installed
if [ ${SITEMAILSTATUS} = "VMAIL_SERVER" ]; then
/bin/echo "
Email server already installed.
"
exit 0; fi
if [ ${SITEMAILSTATUS} = "EMAIL_BACKUP_MX" ]; then
/bin/echo "
Email server is already a backup server.
"
exit 0; fi
if [ ${SITEMAILSTATUS} = "PMAIL_SERVER" ]; then
/bin/echo "
Email server is already installed.
"
exit 0; fi
if /bin/grep -Fq "Webmail Defaults" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}; then
/bin/echo "
Webmail Defaults already declared in the DNS zone file. This won't work.
"
exit 7; fi

# Generate the mailpassword appendage (just a little more secure, wink)
MAILPASSGEN="$(/usr/bin/pwgen -s -1 5)"

# Choose Internet Site options in advance
/bin/echo "postfix postfix/mailname string ${hostURI}" | debconf-set-selections
/bin/echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
#/bin/echo "postfix postfix/relayhost string smtp.localdomain" | debconf-set-selections
/usr/bin/apt-get install -y mail-server^
## Get the PHP version
phpNum=$(/opt/verb/serfs/phpver)
## Continue the install
/usr/bin/apt-get install -y \
  postfix-mysql \
  dovecot-mysql \
  amavis \
  clamav \
  clamav-daemon \
  spamassassin \
  libdbi-perl \
  libdbd-mysql-perl \
  php${phpNum}-imap
/usr/sbin/apache2ctl graceful

# Add other tools for spam and antivirus
/usr/bin/apt-get install -y \
  pyzor \
  razor \
  arj \
  cabextract \
  lzop \
  nomarch \
  p7zip-full \
  ripole \
  rpm2cpio \
  tnef \
  unzip \
  unrar-free \
  zip

# Create the MySQL database and user
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE DATABASE mail;
GRANT ALL PRIVILEGES ON mail.* TO 'mail'@'localhost' IDENTIFIED BY 'mailpass${MAILPASSGEN}';
FLUSH PRIVILEGES;"
# OR try:
#/opt/verb/serfs/newmysqldb mail mail mailpass${MAILPASSGEN}

# Create the MySQL login .cnf
echo "[client]
user = mail
password = mailpass${MAILPASSGEN}
database = mail
host = localhost
" > /opt/verb/conf/mysqldb.vmail.cnf

# Create the mailbox table
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "CREATE TABLE IF NOT EXISTS mailbox (
    username varchar(255) NOT NULL default '',
    password varchar(255) NOT NULL default '',
    name varchar(255) NOT NULL default '',
    maildir varchar(255) NOT NULL default '',
    quota bigint(20) NOT NULL default '0',
    domain varchar(255) NOT NULL default '',
    created DATETIME,
    modified DATETIME,
    active tinyint(1) NOT NULL default '1',
    PRIMARY KEY  (username)
  ) COMMENT='Postfix Vmail - Virtual Mailboxes';
  CREATE TABLE IF NOT EXISTS alias (
    address varchar(255) NOT NULL default '',
    goto text NOT NULL,
    domain varchar(255) NOT NULL default '',
    created DATETIME,
    modified DATETIME,
    active tinyint(1) NOT NULL default '1',
    PRIMARY KEY  (address)
  ) COMMENT='Postfix Vmail - Virtual Aliases';
  CREATE TABLE IF NOT EXISTS domain (
    domain varchar(255) NOT NULL default '',
    description varchar(255) NOT NULL default '',
    aliases int(10) NOT NULL default '0',
    mailboxes int(10) NOT NULL default '0',
    maxquota bigint(20) NOT NULL default '0',
    quota bigint(20) NOT NULL default '0',
    transport varchar(255) default NULL,
    backupmx tinyint(1) NOT NULL default '0',
    created DATETIME,
    modified DATETIME,
    active tinyint(1) NOT NULL default '1',
    PRIMARY KEY (domain)
  ) COMMENT='Postfix Vmail - Virtual Domains';"
#### Below to manage admins ####
#  CREATE TABLE IF NOT EXISTS admin (
#    username varchar(255) NOT NULL default '',
#    password varchar(255) NOT NULL default '',
#    superadmin BOOLEAN NOT NULL default '0',
#    created DATETIME,
#    modified DATETIME,
#    active tinyint(1) NOT NULL default '1',
#    PRIMARY KEY  (username)
#  ) COMMENT='Postfix Vmail - Virtual Admins';
#  CREATE TABLE IF NOT EXISTS domain_admins (
#    username varchar(255) NOT NULL default '',
#    domain varchar(255) NOT NULL default '',
#    created DATETIME,
#    active tinyint(1) NOT NULL default '1',
#    KEY username (username)
#  ) COMMENT='Postfix Vmail - Domain Admins';

# Add base domains & addresse
verberdomain="$nameURI"
PASSWORD=$(/usr/bin/pwgen -s -1 20)
password="$(/bin/echo $PASSWORD | /usr/bin/openssl passwd -1 -stdin)"
username="verberadmin@$nameURI"
NAME="Change Me Dont Delete Me"
vmaildirectory="$nameURI/verberadmin/"
mailboxsize="524288000" # 0.5GB, 2GB=2097152000, 1GB=1048576000, 5GB=5242880000

/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "INSERT INTO domain (domain, description, aliases, mailboxes, maxquota, quota, transport, backupmx, created, modified, active) VALUES ('$verberdomain', '$verberdomain', '1000', '1000', '10000', '2048', 'virtual', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO mailbox (username, password, name, maildir, quota, local_part, domain, created, modified, active) VALUES ('$username', '$password', '$NAME', '$vmaildirectory', '$mailboxsize', 'verberadmin', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('$username', '$username', '$domain', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('abuse@$nameURI', 'verberadmin@$nameURI', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('hostmaster@$nameURI', 'verberadmin@$nameURI', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('postmaster@$nameURI', 'verberadmin@$nameURI', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('webmaster@$nameURI', 'verberadmin@$nameURI', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);"

# Add the virtual user to handle mail
/usr/sbin/useradd -r -u 150 -g mail -d /var/vmail -s /sbin/nologin -c "Virtual maildir handler" vmail
/bin/mkdir -p /var/vmail
/bin/chmod 770 /var/vmail
/bin/chown -R vmail:mail /var/vmail

# Use msmtp for a real SMTP address to send system mail, such as in php
## for vmailsysmailbox at the end, because it checks $VMAIL_SERVER to register installed
/usr/bin/apt-get install -y msmtp

### THIS WAS REMOVED ###
## Postgres Whitelist
### These were changed to links to keep them up to date
##cp /etc/postgrey/whitelist_clients /etc/postfix/postgrey_whitelist_clients
##cp /etc/postgrey/whitelist_recipients /etc/postfix/postgrey_whitelist_recipients
#/bin/ln -sfn /etc/postgrey/whitelist_clients /etc/postfix/postgrey_whitelist_clients
#/bin/ln -sfn /etc/postgrey/whitelist_recipients /etc/postfix/postgrey_whitelist_recipients
### REMOVED ###

# Dovecot
## Sieve for moving spam to Junk
####systemctlend#
#/bin/systemctl stop dovecot
####systemctlend#
####service######
#/usr/sbin/service dovecot stop
####serviceend###
#/usr/bin//usr/bin/apt-get install -y dovecot-sieve
####systemctlend#
#/bin/systemctl start dovecot
####systemctlend#
####service######
#/usr/sbin/service dovecot start
####serviceend###
## Copy config files
/bin/cp /opt/verb/conf/lab/vmail/dovecot/conf.d/10-auth.conf /etc/dovecot/conf.d/
/bin/cp /opt/verb/conf/lab/vmail/dovecot/conf.d/10-mail.conf /etc/dovecot/conf.d/
/bin/cp /opt/verb/conf/lab/vmail/dovecot/conf.d/10-master.conf /etc/dovecot/conf.d/
/bin/cp /opt/verb/conf/lab/vmail/dovecot/conf.d/10-ssl.conf /etc/dovecot/conf.d/
/bin/cp /opt/verb/conf/lab/vmail/dovecot/conf.d/15-lda.conf /etc/dovecot/conf.d/
/bin/cp /opt/verb/conf/lab/vmail/dovecot/conf.d/15-mailboxes.conf /etc/dovecot/conf.d/
/bin/cp /opt/verb/conf/lab/vmail/dovecot/dovecot-sql.conf.ext /etc/dovecot/

# Move spam to Junk
# This plugin to move spam to the spam folder is not yet finished.
#/bin/cp /opt/verb/conf/lab/vmail/dovecot/conf.d/90-plugin.conf /etc/dovecot/conf.d/
#/bin/cp /opt/verb/conf/lab/vmail/dovecot/conf.d/90-sieve.conf /etc/dovecot/conf.d/
#/bin/mkdir -p /etc/dovecot/sieve
#/bin/cp /opt/verb/conf/lab/vmail/dovecot/sieve/default.sieve /etc/dovecot/sieve
#/bin/chown -R vmail:vmail /etc/dovecot/sieve ???? spam-move instructions

## Replace configs
/bin/sed  -i "s/nameURI286/${nameURI}/g" /etc/dovecot/conf.d/10-ssl.conf
/bin/sed  -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/lab/vmail/dovecot/conf.d/10-ssl-SNAKEOIL.conf
/bin/sed  -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/lab/vmail/dovecot/conf.d/10-ssl-INKCERT.conf
/bin/sed  -i "s/nameURI286/${nameURI}/g" /etc/dovecot/conf.d/15-lda.conf
/bin/sed  -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/dovecot/dovecot-sql.conf.ext
## Own
/bin/chown -R vmail:dovecot /etc/dovecot
/bin/chmod -R o-rwx /etc/dovecot

# Amavis, ClamAV, and SpamAssassin
/usr/sbin/adduser clamav amavis
/usr/sbin/adduser amavis clamav
## Copy config files
/bin/cp -R /opt/verb/conf/lab/vmail/amavis/conf.d/15-content_filter_mode /etc/amavis/conf.d/
/bin/cp -R /opt/verb/conf/lab/vmail/amavis/conf.d/50-user /etc/amavis/conf.d/
/bin/cp -R /opt/verb/conf/lab/vmail/clamav/clamd.conf /etc/clamav/
/bin/cp /opt/verb/conf/lab/vmail/default/spamassassin /etc/default/
## Replace configs
/bin/sed  -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/amavis/conf.d/50-user
## Restart and stuff
####systemctl####
#/bin/systemctl restart clamav-daemon
#/bin/systemctl restart amavis
#/bin/systemctl restart spamassassin
####systemctlend#
####service######
/usr/sbin/service clamav-daemon restart
/usr/sbin/service amavis restart
/usr/sbin/service spamassassin restart
####Serviceend###
### Sometimes freshclam is already running or its log file is locked
killall freshclam 2>/dev/null
freshclam

# Postfix
## Copy configs
/bin/cp /opt/verb/conf/lab/vmail/postfix/mysql_virtual_alias_domainaliases_maps.cf /etc/postfix/
/bin/cp /opt/verb/conf/lab/vmail/postfix/mysql_virtual_alias_maps.cf /etc/postfix/
/bin/cp /opt/verb/conf/lab/vmail/postfix/mysql_virtual_domains_maps.cf /etc/postfix/
/bin/cp /opt/verb/conf/lab/vmail/postfix/mysql_virtual_mailbox_domainaliases_maps.cf /etc/postfix/
/bin/cp /opt/verb/conf/lab/vmail/postfix/mysql_virtual_mailbox_maps.cf /etc/postfix/
/bin/cp /opt/verb/conf/lab/vmail/postfix/mysql_virtual_sender_login_maps.cf /etc/postfix/
/bin/cp /opt/verb/conf/lab/vmail/postfix/main.cf /etc/postfix/
/bin/cp /opt/verb/conf/lab/vmail/postfix/master.cf /etc/postfix/
/bin/cp /opt/verb/conf/lab/vmail/postfix/header_checks /etc/postfix/
/bin/cp /opt/verb/conf/lab/vmail/postfix/main_orig.cf /etc/postfix/
## Replace configs
/bin/sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_alias_domainaliases_maps.cf
/bin/sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_alias_maps.cf
/bin/sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_domains_maps.cf
/bin/sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_mailbox_domainaliases_maps.cf
/bin/sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_mailbox_maps.cf
/bin/sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_sender_login_maps.cf
/bin/sed -i "s/hostURI286/${hostURI}/g" /etc/postfix/main.cf
/bin/sed -i "s/nameURI286/${nameURI}/g" /etc/postfix/main.cf
/bin/sed -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/lab/vmail/postfix/main-SNAKEOIL.cf
/bin/sed -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/lab/vmail/postfix/main-INKCERT.cf

# Spamassassin likes to be finickey. Sometimes it needs this on update or whenever...
sa-update -v

# Grand Restart
####systemctl####
#/bin/systemctl restart postfix
#/bin/systemctl restart postfix
#/bin/systemctl restart spamassassin
#/bin/systemctl restart clamav-daemon
#/bin/systemctl restart amavis
#/bin/systemctl restart dovecot
####systemctlend#
####service######
/usr/sbin/service postfix restart
/usr/sbin/service spamassassin restart
/usr/sbin/service clamav-daemon restart
/usr/sbin/service amavis restart
/usr/sbin/service dovecot restart
####serviceend###

# Set the config for backup
/bin/sed -i "s/SITEMAILPASSAPG.*/SITEMAILPASSAPG=\"${MAILPASSGEN}\"/g" /opt/verb/conf/sitemailpass

# UFW (services and ports below them if known)
/usr/sbin/ufw allow postfix
/usr/sbin/ufw allow smtp
/usr/sbin/ufw allow 25
/usr/sbin/ufw allow 587
/usr/sbin/ufw allow smtps
/usr/sbin/ufw allow 465
/usr/sbin/ufw allow pop3
/usr/sbin/ufw allow 110
/usr/sbin/ufw allow pop3s
/usr/sbin/ufw allow 995
/usr/sbin/ufw allow imap
/usr/sbin/ufw allow 143
/usr/sbin/ufw allow imaps
/usr/sbin/ufw allow 993
# for OpenDKIM
/usr/sbin/ufw allow 8891
/usr/sbin/ufw allow 12301

# OpenDKIM
## Create/reset OpenDKIM files
/usr/bin/apt-get install -y opendkim opendkim-tools
/bin/cp /opt/verb/conf/lab/vmail/default/opendkim /etc/default/
/bin/cp /opt/verb/conf/lab/vmail/opendkim.conf /etc/
/bin/mkdir /etc/opendkim
/bin/mkdir /etc/opendkim/keys
/bin/echo "127.0.0.1
localhost
${SITEIP}
${hostURI}" > /etc/opendkim/TrustedHosts
/bin/echo "inkdkim._domainkey.${nameURI} ${nameURI}:inkdkim:/etc/opendkim/keys/${nameURI}/inkdkim.private" > /etc/opendkim/KeyTable
/bin/echo "${nameURI} inkdkim._domainkey.${nameURI}" > /etc/opendkim/SigningTable
## OpenDKIM Key for initial site
/bin/mkdir -p /etc/opendkim/keys/${nameURI}
cd /etc/opendkim/keys/${nameURI}
/usr/bin/opendkim-genkey -r -S -s inkdkim -d ${nameURI}
/bin/chmod 660 inkdkim.private
/bin/chown -R opendkim:opendkim /etc/opendkim
####systemctl####
#/bin/systemctl start opendkim
####systemctlend#
####service######
/usr/sbin/service opendkim start
####serviceend###

# Apache
####systemctl####
#/usr/sbin/apache2ctl graceful
####systemctlend#
####service######
/usr/sbin/service apache2 reload
####serviceend###

# DNS MX and TXT mail records for this server
/opt/verb/serfs/inkdnsaddmail ${nameURI}; wait
## Keep the zone file clean & let the server know "I was here."
/bin/echo ";" >> /opt/verb/conf/inkdns/zones/db.${nameURI}
/opt/verb/serfs/addinkdkim ${nameURI}; wait
/opt/verb/serfs/inkdnsaddinkdkim ${nameURI}; wait
## Webmail TLD prep
/bin/echo "; Webmail Defaults
" >> /opt/verb/conf/inkdns/zones/db.${emailTLDURI}

# inkCert
## This adds the declared domain to the end of the "domains =" line
#sed -i "/^domains =/ s/$/, mail.${emailTLDURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini

# Monit
/bin/cp /opt/verb/conf/lab/vmail/monit/monitrc.d/amavis /etc/monit/monitrc.d/
/bin/cp /opt/verb/conf/lab/vmail/monit/monitrc.d/dovecot /etc/monit/monitrc.d/
/bin/cp /opt/verb/conf/lab/vmail/monit/monitrc.d/opendkim /etc/monit/monitrc.d/
/bin/cp /opt/verb/conf/lab/vmail/monit/monitrc.d/postfix /etc/monit/monitrc.d/
/bin/cp /opt/verb/conf/lab/vmail/monit/monitrc.d/spamassassin /etc/monit/monitrc.d/
####systemctl####
/bin/systemctl restart monit
####systemctlend#
####service######
#/usr/sbin/service monit restart
####serviceend###

# Config settings to "EMAIL_INSTALLED"
/bin/sed -i "s/SITEMAILSTATUS=.*/SITEMAILSTATUS=\"VMAIL_SERVER\"/g" /opt/verb/conf/sitemailpath

# Use real mail for php mail
/opt/verb/serfs/vmailsysmailbox

# Finish
/bin/echo "Postfix and friends for inkVerb has been installed.

The email server is https://${emailTLDURI}

FYI, you must restart the server in order for email boxes to send and receive."
