#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This downloads and installs the current verified version of suiteCRM from inkisaverb.com/repo to crm.your-name.verb.red

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installsuitecrm [dbuser] [dbpassword]


CVAPPNAME=suitecrm

# Include the config
. /opt/verb/conf/siteurilist

DBASE=$1
DBUSER=$2
DBPASSWORD=$3
CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')

# Check if already installed
## Config
if [ -f /opt/verb/conf/vapp.${CVAPPNAME} ]; then
echo "This is already installed."
exit 0; fi
## Directory
if [ -d /var/www/vapps/${CVAPPNAME} ]; then
echo "SuiteCRM already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 8; fi

# Include the config file
. /opt/verb/conf/sitenameip

# This does not create a database, only an administrator since suiteCRM will create that automatically

# Download and unpack the latest checked version from inkisaverb.com/repo
cd /var/www/vapps
/opt/verb/serfs/inkget ${CVAPPNAME}; wait
### Check
/opt/verb/serfs/inkget ${CVAPPNAME} check
if [ "$?" = 4 ]; then
echo "Repo failed to retrieve the file."
exit 4; fi
if [ ! -f ${CVAPPNAME}.vtxz ]; then
echo "Failed to retrieve from the repo."
exit 4; fi

/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
cd /var/www/html
/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
chown -R www-data:www-data /var/www/html/red.crm; wait
chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait

# Auto database
if [ -z ${3} ]; then
DBPASSWORD=$(pwgen -s -1 10); fi
if [ -z ${1} ]; then
DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
if [ -z ${2} ]; then
DBUSER=${DBASE}; fi

# Create the database user and credentials
mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON *.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"

# Write the config for backup
echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}

echo "These are setup:

Database: ${DBASE}
Host Name: localhost (do not use crm....verb.red)
Database user: ${DBUSER}
Database password: ${DBPASSWORD}

*The SuiteCRM installer can be finicky. Be mindful of all details. Copy-paste into fields whenever possible.

*Choose \"Provide Existing User\" BEFORE entering above information.

Go to the http://crm.${redURI} site to install.
"

