#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and installs Pydio manually from inkisaverb.com/repo and linnks it to ....verb.blue

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installpydio [dbase] [dbuser] [dbpassword]


CVAPPNAME=pydio

# Include the config
. /var/local/verb/configs/siteurilist

DBASE=$1
DBUSER=$2
DBPASSWORD=$3
CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')

# Check if already installed
## Config
if [ -f /var/local/verb/configs/verbapp.${CVAPPNAME} ]; then
echo "This is already installed."
exit 0; fi
## Directory
if [ -d /var/www/vapps/${CVAPPNAME} ]; then
echo "Pydio already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 22; fi

# Auto database
if [ -z $3 ]; then
DBPASSWORD=$(pwgen -s -1 10); fi
if [ -z $1 ]; then
DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
if [ -z $2 ]; then
DBUSER=${DBASE}; fi

# Include the config file
. /var/local/verb/configs/sitenameip

# Download and unpack the latest checked version from the Inker repo
cd /var/www/vapps
/var/local/verb/serfs/inkget ${CVAPPNAME}.current
unzip ${CVAPPNAME}.current.zip
rm -f ${CVAPPNAME}.current.zip
chown -R www-data:www-data ${CVAPPNAME}
rm -rf /var/www/html/blue.pydio
ln -s /var/www/vapps/${CVAPPNAME} /var/www/html/blue.pydio
chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
chown -R www-data:www-data /var/www/html/blue.pydio

# Create the database and credentials
mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
FLUSH PRIVILEGES;"

# Write the config for backup
echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/verbapp.${CVAPPNAME}

echo "These are setup:

Database Connexion
Host: localhost
Database: MySQL
Database: ${DBASE}
User: ${DBUSER}
Password: ${DBPASSWORD}

*Check \"MySQLi\" if the installer asks.
Don't make any other changes in set-up!

Go to http://pydio.${blueURI} to install.
"

