#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and installs ownCloud manually from inkisaverb.com/repo and linnks it to ....verb.blue

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installowncloud [dbase] [dbuser] [dbpassword]

# Eg:
## ./installowncloud
## ./installowncloud bestdbase trump besteverpass



CVAPPNAME=owncloud

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

DBASE=$1
DBUSER=$2
DBPASSWORD=$3
CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')

# Check if already installed
## Config
if [ -f /var/local/verb/configs/vapp.${CVAPPNAME} ]; then
echo "This is already installed."
exit 0; fi
## Directory
if [ -d /var/www/vapps/${CVAPPNAME} ]; then
echo "ownCloud already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 22; fi

# Auto database
if [ -z ${3} ]; then
DBPASSWORD=$(pwgen -s -1 10); fi
if [ -z ${1} ]; then
DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
if [ -z ${2} ]; then
DBUSER=${DBASE}; fi

# Do it
cd /var/www/vapps
## Get and unpack
echo "Getting ownCloud, this could take a minute or so..."
/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
rm -rf owncloud
/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
## Install it
rm -rf /var/www/html/blue.owncloud
ln -sfn /var/www/vapps/${CVAPPNAME} /var/www/html/blue.owncloud
chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
chown -R www-data:www-data /var/www/html/blue.owncloud
## Run the ownCloud script
#/var/local/verb/donjon/owncloudprep.sh; wait # May be unique to Nextcloud
## Set up cron for updates
echo "*/15  *  *  *  * www-data php -f /var/www/vapps/owncloud/cron.php" > /etc/cron.d/owncloud
#chmod 644 /etc/cron.d/owncloud
chmod 755 /etc/cron.d/owncloud

# Create the database and credentials
mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
FLUSH PRIVILEGES;"

# Write the config for backup
echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}

echo "These are setup:

Database user: ${DBUSER}
Database password: ${DBPASSWORD}
Database name: ${DBASE}
Host: localhost

*Don't make any other changes during the install!

Go to https://owncloud.${blueURI} to install.

After, you may want to run setowncloudbfdoff to disable brute force detection in order to allow some client apps to work. You can always turn it on again with setowncloudbfdon
"

