#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This installs the inkSplat Dovecot utility, moving marked spapm to the Junk folder and learning spam
## This was largely informed by:
### https://wiki2.dovecot.org/HowTo/AntispamWithSieve
### https://wiki.dovecot.org/Pigeonhole/Sieve/Examples
## Also referenced:
### https://stackoverflow.com/a/32470349/10343144
### https://wiki1.dovecot.org/LDA/Sieve
### https://wiki.dovecot.org/ConfigFile
### https://wiki2.dovecot.org/Pigeonhole/Sieve
### https://wiki2.dovecot.org/Pigeonhole/Sieve/Configuration


# How to use:
## ./installinksplat



# Check status
. /opt/verb/conf/sitemailpath
if [ ${SITEMAILSTATUS} = "VMAIL_SERVER" ] || [ ${SITEMAILSTATUS} = "EMAIL_BACKUP_MX" ] || [ ${SITEMAILSTATUS} = "PMAIL_SERVER" ]; then
  echo "A mail server is already installed, all is well, continuing..."
else
  echo "No mail server installed yet. Do that first. I quit."
exit 0; fi

if [ ${INKSPLAT} = "INSTALLED" ]; then
  echo "inkSplat already installed. Doing nothing."
exit 0;fi

# Install Sieve & the Pigeonhole package (on Debian it is: managesieved, https://wiki2.dovecot.org/Pigeonhole/Installation)
apt install dovecot-sieve dovecot-managesieved -y

# Setup the plugins and their files
echo "# List the Sieve plugin (for moving spam and using colored priority tags/flags)
## From: https://wiki.dovecot.org/Pigeonhole/Sieve/Examples
plugin {
    sieve = /etc/dovecot/sieve/inksplat.sieve
}" > /etc/dovecot/conf.d/90-plugin.conf
chmod 640 /etc/dovecot/conf.d/90-plugin.conf
echo '
# inkSplat utility set
!include_try inksplat.conf' >> /etc/dovecot/dovecot.conf
cp /opt/verb/conf/lab/inksplat/inksplat.conf /etc/dovecot/
chown -R vmail:dovecot /etc/dovecot/inksplat.conf
chown 640 /etc/dovecot/inksplat.conf
mkdir -p /etc/dovecot/sieve
chown -R vmail:dovecot /etc/dovecot/sieve
chmod 750 /etc/dovecot/sieve
cp /opt/verb/conf/lab/inksplat/inksplat.sieve /etc/dovecot/sieve/
chmod 640 /etc/dovecot/sieve/inksplat.sieve
mkdir -p /usr/lib/dovecot/sieve
cp /opt/verb/conf/lab/inksplat/report-spam.sieve /usr/lib/dovecot/sieve/
cp /opt/verb/conf/lab/inksplat/report-ham.sieve /usr/lib/dovecot/sieve/
chmod 644 /usr/lib/dovecot/sieve/*.sieve
cp /opt/verb/conf/lab/inksplat/sa-learn-spam.sh /usr/lib/dovecot/sieve/
cp /opt/verb/conf/lab/inksplat/sa-learn-ham.sh /usr/lib/dovecot/sieve/
chmod 755 /usr/lib/dovecot/sieve/*.sh

# Restart
systemctl restart dovecot

# Finished
sed -i "s/INKSPLAT=.*/INKSPLAT=\"INSTALLED\"/" /opt/verb/conf/sitemailpath
echo "inkSplat email tagging & filtering for Dovecot installed."
