#!/bin/bash
#inkVerbSerf! verb.ink
set -e

# This installs droids from a git repo.

# How to use:
## installdroid [ http://github.com/clonePathTo/droidRepo - optional to avoid dialogue ]

# Eg:
## installdroid 
## installdroid https://github.com/inkVerb/droids


DROIDREPO=$1

# Sanitize repo
CLNDROIDREPO1=$(echo $DROIDREPO | cut -d'/' -f5-)
CLNDROIDREPO=$(echo $CLNDROIDREPO1 | sed 's/\.git//')

# Clone it
cd /var/local/verb/droids
git clone ${DROIDREPO}

# Clean up and install
cd ${CLNDROIDREPO}
chmod +x vd*
mv vd* ../
cd ..
rm -rf ${CLNDROIDREPO}

# Finish
echo "The droids from \"${CLNDROIDREPO}\" are installed."

