#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This runs installpostfix and some extra scripts to setup a backup email server on this Verber
## Prerequisite: setupverb of course, and verbemail if you wish an email tld other than .email
## Prerequisite: this Verber should be linked to the backup server already.
## Roundcube and PostfixAdmin will be disallowed by running this.

# DEV NOTE: This is by no means finished. It is only a start to set config files.

# How to use:
## ./installemailbackmx

# Eg:
## ./installemailbackmx

SERVER=$1

/var/local/verb/serfs/installpostfix

# Config settings
sed -i "s/RC_NOT_INSTALLED/RC_NOT_ALLOWED/g" /var/local/verb/configs/sitemailpath
sed -i "s/RC_NOT_INSTALLED/RC_NOT_ALLOWED/g" /var/local/verb/configs/sitemailpass
sed -i "s/PFA_NOT_INSTALLED/PFA_NOT_ALLOWED/g" /var/local/verb/configs/sitemailpath
sed -i "s/EMAIL_SERVER/EMAIL_BACKUP_MX/g" /var/local/verb/configs/sitemailpath

# Finished
echo "
All set. This is now a backup email server for $SERVER.
"
