#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This downloads and installs the InfiniteWP Server to a new directory to an existing domain in the .../html/ folder
## For security, this does NOT install to a pre-defined inkVerb subdomain, ie iwp.name.verb.ink. The site has too much control and must be set differently.
## This does not interfere at all with the contents of the domain.
## This should be installed AFTER any installations to the domain, such as WordPress

# All options after the email are optional, but are sequential

# How to use:
## ./installiwpadmin [sub.domain.tld or domain.tld] [email for registration] [directory of domain.tld/directory] [dbase] [dbuser] [dbpassword]


CVAPPNAME=iwpadmin

DOMAIN=$1
REMAIL=$2
DIRECTORY=$3
DBASE=$4
DBUSER=$5
DBPASSWORD=$6
CLEANNAME=$(echo $DOMAIN | sed -e 's/\.//g')

# Check that the directory doesn't already exist
if [ -d /var/www/html/${DOMAIN}/${DIRECTORY} ]; then
echo "That directory already exists for that domain. Choose a different directory."
exit 8; fi

# Options
if [ -z ${1} ]; then
echo "You must designate a domain."
exit 8; fi

# Check email is set
if [ -z ${2} ]; then
echo "You must set an email for the repo package in InfiniteWP-Admin."
exit 8; fi


# Include the config file
. /opt/verb/conf/sitenameip

# Download and establish IWPAdmin in the server to pre-created domain
cd /var/www/vapps
/opt/verb/serfs/inkget ${CVAPPNAME} ${REMAIL}; wait
### Check
/opt/verb/serfs/inkget ${CVAPPNAME} check
if [ "$?" = 4 ]; then
echo "Repo failed to retrieve the file."
exit 4; fi
if [ ! -f ${CVAPPNAME}.vtxz ]; then
echo "Failed to retrieve from the repo."
exit 4; fi

## Auto options
if [ -z ${3} ]; then
DIRECTORY=iwp$(pwgen -s -1 1); fi
if [ -z ${6} ]; then
DBPASSWORD=$(pwgen -s -1 10); fi
if [ -z ${4} ]; then
DBASE=iwp$(echo $CLEANNAME | cut -c1-23)$(pwgen -s -1 5); fi
if [ -z ${5} ]; then
DBUSER=${DBASE}; fi

/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
mv ${CVAPPNAME} ${DOMAIN}
mv ${CVAPPNAME} ${CVAPPNAME}.${DOMAIN}
ln -sfn /var/www/vapps/${CVAPPNAME}.${DOMAIN} /var/www/html/${DOMAIN}/${DIRECTORY}

# Create the database and credentials
mysql --login-path=local -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
FLUSH PRIVILEGES;"

# Write the config for backup
echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}
IWPADMIN_DIRECTORY=\"${DIRECTORY}\"" > /opt/verb/conf/vapp.${CVAPPNAME}.${DOMAIN}

# Reset all permissions
chown -R www-data:www-data /var/www/html/${DOMAIN}/${DIRECTORY}; wait

echo "${DOMAIN} now has the InfiniteWP Admin Panel.
These are setup:

Database: ${DBASE}
Database user: ${DBUSER}
Database password: ${DBPASSWORD}
Database port / prefix: DO NOT CHANGE

Go to http://${DOMAIN}/${DIRECTORY} to install.
"
