#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This installs Postfix as the email server wtih Dovecot and OpenDKIM
## Prerequisite: sertupverb
## This only performs basic back-end server setup and creates no mail accounts
## Once this is done it is set for the server permanently.

# How to use:
## ./installpostfixvmail


# Include the config files
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist
. /var/local/verb/configs/sitemailpath

# Check to see if already installed
if [ ${SITEMAILSTATUS} = "VMAIL_SERVER" ]; then
echo "
Email server already installed.
"
exit 0; fi
if [ ${SITEMAILSTATUS} = "EMAIL_BACKUP_MX" ]; then
echo "
Email server is already a backup server.
"
exit 0; fi
if [ ${SITEMAILSTATUS} = "PMAIL_SERVER" ]; then
echo "
Email server is already a backup server.
"
exit 0; fi
if grep -Fq "Webmail Defaults" /var/local/verb/configs/inkdns/zones/${emailTLDURI}.db; then
echo "
Webmail Defaults already declared in the DNS zone file. This won't work.
"
exit 11; fi

# Generate the mailpassword appendage (just a little more secure, wink)
MAILPASSGEN=$(pwgen -s -1 5)

# Choose Internet Site options in advance
echo "postfix postfix/mailname string ${hostURI}" | debconf-set-selections
echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
#echo "postfix postfix/relayhost string smtp.localdomain" | debconf-set-selections 
apt install -y mail-server^
apt install -y \
  postfix-mysql \
  dovecot-mysql \
# Postgrey causes delay problems and is seriously outdated!! Try running without it. https://blog.slowb.ro/reasons-why-i-had-to-disable-greylisting/
  postgrey \
  amavis \
  clamav \
  clamav-daemon \
  spamassassin \
  libdbi-perl \
  libdbd-mysql-perl \
  php7.0-imap
apache2ctl graceful

# Add other tools for spam and antivirus
apt install -y \
  pyzor \
  razor \
  arj \
  cabextract \
  lzop \
  nomarch \
  p7zip-full \
  ripole \
  rpm2cpio \
  tnef \
  unzip \
  unrar-free \
  zip \
  zoo

# Create the MySQL database and user
mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
CREATE DATABASE mail;
GRANT ALL PRIVILEGES ON mail.* TO 'mail'@'localhost' IDENTIFIED BY 'mailpass${MAILPASSGEN}';
FLUSH PRIVILEGES;"
# OR try:
#/var/local/verb/serfs/newmysqldb mail mail mailpass${MAILPASSGEN}

# Add the virtual user to handle mail
useradd -r -u 150 -g mail -d /var/vmail -s /sbin/nologin -c "Virtual maildir handler" vmail
mkdir -p /var/vmail
chmod 770 /var/vmail
chown -R vmail:mail /var/vmail

# Postgres Whitelist
## These were changed to links to keep them up to date
#cp /etc/postgrey/whitelist_clients /etc/postfix/postgrey_whitelist_clients
#cp /etc/postgrey/whitelist_recipients /etc/postfix/postgrey_whitelist_recipients
ln -sfn /etc/postgrey/whitelist_clients /etc/postfix/postgrey_whitelist_clients
ln -sfn /etc/postgrey/whitelist_recipients /etc/postfix/postgrey_whitelist_recipients

# Dovecot
## Sieve for moving spam to Junk
####systemctlend#
#systemctl stop dovecot
####systemctlend#
####service######
#service dovecot stop
####serviceend###
#apt install -y dovecot-sieve
####systemctlend#
#systemctl start dovecot
####systemctlend#
####service######
#service dovecot start
####serviceend###
## Copy config files
cp /var/local/verb/configs/conflab/vmail/dovecot/conf.d/10-auth.conf /etc/dovecot/conf.d/
cp /var/local/verb/configs/conflab/vmail/dovecot/conf.d/10-mail.conf /etc/dovecot/conf.d/
cp /var/local/verb/configs/conflab/vmail/dovecot/conf.d/10-master.conf /etc/dovecot/conf.d/
cp /var/local/verb/configs/conflab/vmail/dovecot/conf.d/10-ssl.conf /etc/dovecot/conf.d/
cp /var/local/verb/configs/conflab/vmail/dovecot/conf.d/15-lda.conf /etc/dovecot/conf.d/
cp /var/local/verb/configs/conflab/vmail/dovecot/conf.d/15-mailboxes.conf /etc/dovecot/conf.d/
cp /var/local/verb/configs/conflab/vmail/dovecot/conf.d/90-plugin.conf /etc/dovecot/conf.d/
cp /var/local/verb/configs/conflab/vmail/dovecot/conf.d/90-sieve.conf /etc/dovecot/conf.d/
cp /var/local/verb/configs/conflab/vmail/dovecot/dovecot-sql.conf.ext /etc/dovecot/

# Move spam to Junk
mkdir -p /etc/dovecot/sieve
cp /var/local/verb/configs/conflab/vmail/dovecot/sieve/default.sieve /etc/dovecot/sieve
#chown -R vmail:vmail /etc/dovecot/sieve ???? spam-move instructions

## Replace configs
sed  -i "s/nameURI286/${nameURI}/g" /etc/dovecot/conf.d/10-ssl.conf
sed  -i "s/nameURI286/${nameURI}/g" /var/local/verb/configs/conflab/vmail/dovecot/conf.d/10-ssl-SNAKEOIL.conf
sed  -i "s/nameURI286/${nameURI}/g" /var/local/verb/configs/conflab/vmail/dovecot/conf.d/10-ssl-INKCERT.conf
sed  -i "s/nameURI286/${nameURI}/g" /etc/dovecot/conf.d/15-lda.conf
sed  -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/dovecot/dovecot-sql.conf.ext
## Own
chown -R vmail:dovecot /etc/dovecot
chmod -R o-rwx /etc/dovecot

# Amavis, ClamAV, and SpamAssassin
adduser clamav amavis
adduser amavis clamav
## Copy config files
cp -R /var/local/verb/configs/conflab/vmail/amavis/conf.d/15-content_filter_mode /etc/amavis/conf.d/
cp -R /var/local/verb/configs/conflab/vmail/amavis/conf.d/50-user /etc/amavis/conf.d/
cp -R /var/local/verb/configs/conflab/vmail/clamav/clamd.conf /etc/clamav/
cp /var/local/verb/configs/conflab/vmail/default/spamassassin /etc/default/
## Replace configs
sed  -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/amavis/conf.d/50-user
## Restart and stuff
####systemctl####
#systemctl restart clamav-daemon
#systemctl restart amavis
#systemctl restart spamassassin
####systemctlend#
####service######
service clamav-daemon restart
service amavis restart
service spamassassin restart
####Serviceend###
### Sometimes freshclam is already running or its log file is locked
killall freshclam 2>/dev/null
freshclam

# Postfix
## Copy configs
cp /var/local/verb/configs/conflab/vmail/postfix/mysql_virtual_alias_domainaliases_maps.cf /etc/postfix/
cp /var/local/verb/configs/conflab/vmail/postfix/mysql_virtual_alias_maps.cf /etc/postfix/
cp /var/local/verb/configs/conflab/vmail/postfix/mysql_virtual_domains_maps.cf /etc/postfix/
cp /var/local/verb/configs/conflab/vmail/postfix/mysql_virtual_mailbox_domainaliases_maps.cf /etc/postfix/
cp /var/local/verb/configs/conflab/vmail/postfix/mysql_virtual_mailbox_maps.cf /etc/postfix/
cp /var/local/verb/configs/conflab/vmail/postfix/mysql_virtual_sender_login_maps.cf /etc/postfix/
cp /var/local/verb/configs/conflab/vmail/postfix/main.cf /etc/postfix/
cp /var/local/verb/configs/conflab/vmail/postfix/master.cf /etc/postfix/
cp /var/local/verb/configs/conflab/vmail/postfix/header_checks /etc/postfix/
cp /var/local/verb/configs/conflab/vmail/postfix/main_orig.cf /etc/postfix/
## Replace configs
sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_alias_domainaliases_maps.cf
sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_alias_maps.cf
sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_domains_maps.cf
sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_mailbox_domainaliases_maps.cf
sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_mailbox_maps.cf
sed -i "s/mailpassword/mailpass${MAILPASSGEN}/g" /etc/postfix/mysql_virtual_sender_login_maps.cf
sed -i "s/hostURI286/${hostURI}/g" /etc/postfix/main.cf
sed -i "s/nameURI286/${nameURI}/g" /etc/postfix/main.cf
sed -i "s/nameURI286/${nameURI}/g" /var/local/verb/configs/conflab/vmail/postfix/main-SNAKEOIL.cf
sed -i "s/nameURI286/${nameURI}/g" /var/local/verb/configs/conflab/vmail/postfix/main-INKCERT.cf

# Spamassassin likes to be finickey. Sometimes it needs this on update or whenever...
sa-update -v

# Grand Restart
####systemctl####
#systemctl restart postfix
#systemctl restart postfix
#systemctl restart spamassassin
#systemctl restart clamav-daemon
#systemctl restart amavis
#systemctl restart dovecot
####systemctlend#
####service######
service postfix restart
service spamassassin restart
service clamav-daemon restart
service amavis restart
service dovecot restart
####serviceend###

# Set the config for backup
sed -i "s/SITEMAILPASSAPG.*/SITEMAILPASSAPG=\"${MAILPASSGEN}\"/g" /var/local/verb/configs/sitemailpass

# UFW (services and ports below them if known)
ufw allow postfix
ufw allow smtp
ufw allow 25
ufw allow 587
ufw allow smtps
ufw allow 465
ufw allow pop3
ufw allow 110
ufw allow pop3s
ufw allow 995
ufw allow pop2
ufw allow 109
ufw allow imap
ufw allow 143
ufw allow imaps
ufw allow 993
# for OpenDKIM
ufw allow 8891
ufw allow 12301

# OpenDKIM
## Create/reset OpenDKIM files
apt install -y opendkim opendkim-tools
cp /var/local/verb/configs/conflab/vmail/default/opendkim /etc/default/
cp /var/local/verb/configs/conflab/vmail/opendkim.conf /etc/
mkdir /etc/opendkim
mkdir /etc/opendkim/keys
echo "127.0.0.1
localhost
${SITEIP}
${hostURI}" > /etc/opendkim/TrustedHosts
echo "inkdkim._domainkey.${nameURI} ${nameURI}:inkdkim:/etc/opendkim/keys/${nameURI}/inkdkim.private" > /etc/opendkim/KeyTable
echo "${nameURI} inkdkim._domainkey.${nameURI}" > /etc/opendkim/SigningTable
## OpenDKIM Key for initial site
mkdir -p /etc/opendkim/keys/${nameURI}
cd /etc/opendkim/keys/${nameURI}
opendkim-genkey -r -S -s inkdkim -d ${nameURI}
chmod 660 inkdkim.private
chown root:opendkim inkdkim.private
chown opendkim:opendkim inkdkim.private
####systemctl####
#systemctl start opendkim
####systemctlend#
####service######
service opendkim start
####serviceend###

# Apache
####systemctl####
#apache2ctl graceful
####systemctlend#
####service######
service apache2 reload
####serviceend###

# DNS MX and TXT mail records for this server
/var/local/verb/serfs/inkdnsaddmail ${nameURI}; wait
## Keep the zone file clean & let the server know "I was here."
echo ";" >> /var/local/verb/configs/inkdns/zones/${nameURI}.db
/var/local/verb/serfs/addinkdkim ${nameURI}; wait
/var/local/verb/serfs/inkdnsaddinkdkim ${nameURI}; wait
## Webmail TLD prep
echo "; Webmail Defaults
" >> /var/local/verb/configs/inkdns/zones/${emailTLDURI}.db

# inkCert
## This adds the declared domain to the end of the "domains =" line
#sed -i "/^domains =/ s/$/, mail.${emailTLDURI}/" /var/local/verb/configs/inkcert/cli-ini/cli.${emailTLDURI}.ini

# Monit
cp /var/local/verb/configs/conflab/vmail/monit/monitrc.d/amavis /etc/monit/monitrc.d/
cp /var/local/verb/configs/conflab/vmail/monit/monitrc.d/dovecot /etc/monit/monitrc.d/
cp /var/local/verb/configs/conflab/vmail/monit/monitrc.d/opendkim /etc/monit/monitrc.d/
cp /var/local/verb/configs/conflab/vmail/monit/monitrc.d/postfix /etc/monit/monitrc.d/
cp /var/local/verb/configs/conflab/vmail/monit/monitrc.d/spamassassin /etc/monit/monitrc.d/
####systemctl####
systemctl restart monit
####systemctlend#
####service######
service monit restart
####serviceend###

# Config settings to "EMAIL_INSTALLED"
sed -i "s/SITEMAILSTATUS=.*/SITEMAILSTATUS=\"VMAIL_SERVER\"/g" /var/local/verb/configs/sitemailpath

# Finish
echo "Postfix and friends for inkVerb has been installed.

The email server is https://${emailTLDURI}"

