#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This installs vsftpd and prepares it for use according to newftpguru, delftpguru, newftpfiler, and delftpfiler scripts
# This is a prereqisite for ftpgurus and ftpfilers and net2ftp

## THIS HAS EXPIRIMENTAL LINES. Remove commented lines if it works.

# How to use:
## ./installvsftpd


# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

apt install vsftpd

# Allow users to upload
sed -i "s/#write_enable=YES/write_enable=YES/g" /etc/vsftpd.conf

# Limit users to their respective directories
sed -i "s/#chroot_local_user=YES/chroot_local_user=YES/g" /etc/vsftpd.conf

echo "# Added by inkVerb with respect to above chroot_local_user=YES also uncommented" >> /etc/vsftpd.conf
echo "chroot_list_enable=NO" >> /etc/vsftpd.conf

# Set the umask to the normal 022
sed -i "s/#local_umask=022/local_umask=022/g" /etc/vsftpd.conf

# Set the listening port to 2121
## Commented, may not be necessary given ufw config
#echo "listen_port=2121" >> /etc/vsftpd.conf

# Set the branding
sed -i "s/#ftpd_banner=Welcome to blah FTP service\./ftpd_banner=inkVerb FTP, get inking.../g" /etc/vsftpd.conf

# Enable SSL
## Comment the snakeoil settings
sed -i "s/rsa_cert_file=\/etc\/ssl\/certs\/ssl-cert-snakeoil\.pem/#rsa_cert_file=\/etc\/ssl\/certs\/ssl-cert-snakeoil\.pem/g" /etc/vsftpd.conf
sed -i "s/rsa_private_key_file=\/etc\/ssl\/private\/ssl-cert-snakeoil\.key/#rsa_private_key_file=\/etc\/ssl\/private\/ssl-cert-snakeoil\.key/g" /etc/vsftpd.conf
## Allow the inkCert certs
echo "ssl_enable=Yes" >> /etc/vsftpd.conf
echo "rsa_cert_file=/etc/inkcert/live/${nameURI}/cert.pem" >> /etc/vsftpd.conf
echo "rsa_private_key_file=/etc/inkcert/live/${nameURI}/privkey.pem" >> /etc/vsftpd.conf
## The line below is expirimental based on info from http://vsftpd.beasts.org/vsftpd_conf.html
echo "ca_certs_file=/etc/inkcert/live/${nameURI}/chain.pem" >> /etc/vsftpd.conf

# Put the default ftp user to another directory
mkdir /srv/vsftpd
mkdir /srv/vsftpd/ftp
usermod -d /srv/vsftpd/ftp ftp

# Start the service
## This is expirimental
service vsftpd start

# Restart
## Former is commented, new is expirimental and may be redundant
service vsftpd restart
#restart vsftpd

# Set the firewall to allow the site port
. /var/local/verb/configs/siteport
ufw allow from any to any port ${SITEPORT}

