#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This installs ghost as an app to be connected to blog.your-name.verb.ink

# You MUST HAVE EMAIL SETUP with an email address. Once you set this password you can't change it. Probably ghost@your-name.verb.ink

# Ghost Port: Only the blog.YOU.verb.ink URI uses 2368, domains use higher ports.

# NOTE: Put the email password in "double quotes" to avoid problems with special characters.

# How to use:
## ./installghostinkblog [emailusername] "[emailpassword]"


CVAPPNAME=ghost.inkblog

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

EMAILUSER=$1
EMAILPASS=$2

# Basic credential check
if [ -z ${2} ]; then
echo "You need to set two variables (email and password) to install Ghost to a domain. See \"How to use\" in the serf."
exit 5
fi

# Check for existing inkblog
. /opt/verb/conf/siteinstallstatus
if [ "${INKblog}" != "NOT_YET" ]; then
echo "Awkward...
Your blog at blog.${inkURI} already has ${INKblog} installed. This just isn't going to work."
exit 0
fi

# Install Node.js (LTS req by Ghost) and npm
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
apt install -y nodejs

# Install Ghost
cd /var/www/ghost
curl -L https://ghost.org/zip/ghost-latest.zip -o ghost.zip
unzip -uo ghost.zip -d ghostblog
rm -f ghost.zip

## Now install it with npm
cd /var/www/ghost/ghostblog
npm install --production

# Set up the Ghost config
cd /var/www/ghost/ghostblog
cp config.example.js config.js
sed -i "s/url: 'http:\/\/my-ghost-blog.com'/url: 'http:\/\/blog.${inkURI}'/g" config.js
sed -i "s/host: '127.0.0.1'/host: '${SITEIP}'/g" config.js
sed -i "s/mail: {}/mail: {transport: 'SMTP', options: {host: 'localhost', port: 25, service: 'dovecot', auth: {user: '${EMAILUSER}', pass: '${EMAILPASS}'}}}/g" config.js

# Set UFW to allow the Ghost port
ufw allow 2368

# Apache
## Remove static-Apache html folder
rm -rf /var/www/html/ink.blog
echo "Ghost" > /var/www/html/ink.blog
## Set the IP address in the Apache config file
cp /opt/verb/conf/site-files/conf/blog.${inkURI}.conf-ghost /etc/apache2/sites-available/blog.${inkURI}.conf
sed -i "s/ip286/${SITEIP}/g" /etc/apache2/sites-available/blog.${inkURI}.conf
apache2ctl graceful
## inkCert SSL certs
### Not setup
if grep -Fq "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${inkURI}; then
echo "FYI: inkCert is not yet setup for ${inkURI}."
fi
### inkCert-LE DONE
if grep -Fq "INKCERTED=DONE_LE" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${inkURI}; then
echo "inkCert-LE is already setup for ${inkURI}. Updating the Apache configs..."
/opt/verb/serfs/inkcertaddallle ${inkURI}
wait
fi
### inkCert-IC DONE
if grep -Fq "INKCERTED=DONE_IC" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${inkURI}; then
echo "inkCert-IC is already setup for ${inkURI}. Updating the Apache configs..."
/opt/verb/serfs/inkcertadd blog.${inkURI}
wait
fi

# Make it a service at startup
cp /opt/verb/conf/site-files/conf/ghost.conf /etc/init/ghost.conf

# Set the site-wide inkblog config
sed -i "s/INKblog=.*/INKblog=\"Ghost\"/g" /opt/verb/conf/siteinstallstatus

# Write the config for backup
echo "#!/bin/sh
GHOSTEMAIL=\"${EMAILUSER}\"
GHOSTEMLPAS=\"${EMAILPASS}\"" > /opt/verb/conf/vapp.${CVAPPNAME}

### Below (Forever) is expirimental on inkVerb, but working, and should be replaced with a way to run Ghost as a proper service at startup
# Run Ghost with Forever
npm install -g forever
## Production forever
cd /var/www/ghost/ghostblog && NODE_ENV=production forever start index.js
## Non-production / developer forever
#forever start index.js
## If you want, stop Forever with:
### cd /var/www/ghost/ghostblog && forever stop index.js

##### Don't use this normally because it halts the current script and does not finish the rest of the jobs
## Start Ghost only for this server session
#cd /var/www/ghost/ghostblog
#npm start --production
#####

# Finish
echo "Ghost is setup.
Go to http://blog.${inkURI}/ghost to install."

# Optional server restart
#echo "But first, wait two minutes for the server to restart."
#sleep 3
#reboot
