#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This "hard" kills a domain added with adddomain or adddomaincgi
## This removes everything. The server probably wouldn't even know that the domain existed, except for any connected vapp

## This DOES NOT:
### Remove any connected vapp

## This DOES:
### Remove the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpvip can access
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove opekDKIM/inkDKIM keys.
### Remove the inkDNS zone file

# How to use:
## ./killdomainhard [KILLDOMAIN.tld]


KILLDOMAIN=$1

# Remove all config files, symlinks, and directories
rm -f /etc/apache2/sites-enabled/${KILLDOMAIN}.conf
rm -f /etc/apache2/sites-enabled/*${KILLDOMAIN}.conf
rm -f /etc/apache2/sites-available/${KILLDOMAIN}.conf
rm -f /etc/apache2/sites-available/*${KILLDOMAIN}.conf
apache2ctl graceful
/opt/verb/serfs/killdomainshell ${KILLDOMAIN}; wait
rm -f /var/www/html/${KILLDOMAIN}
rm -f /var/www/html/*${KILLDOMAIN}
rm -rf /var/www/domains/${KILLDOMAIN}
rm -rf /var/www/domains/*${KILLDOMAIN}

# Restart
/etc/init.d/postfix reload
/etc/init.d/postfix restart

# Finish
echo "${KILLDOMAIN} is all gone, bye bye. Some vapps might remain.
"

