#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This "soft" kills a domain added with adddomain or adddomaincgi
## This removes the root Apache file, html/ symlink, root DNS declarations, and the root domain inkCert-LE declaration, but not other entire configs, such as the inkCert-LE config file that may apply to subdomains.
## This basically turns off the root domain without losing files and retains support for mail, subdomains, and other services.

## This DOES NOT:
### Remove the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpguru can access
### Remove any connected vapp
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove opekDKIM/inkDKIM keys.
### Remove the entire inkDNS zone file

# How to use:
## ./killdomainsoft [KILLDOMAIN.tld]


KILLDOMAIN=$1

# Remove Apache server config files
rm -f /etc/apache2/sites-enabled/${KILLDOMAIN}.conf
rm -f /etc/apache2/sites-available/${KILLDOMAIN}.conf
apache2ctl graceful

# Remove from inkCert
sed -i "s/${KILLDOMAIN}, //g" /var/local/verb/configs/inkcert/cli-ini/cli.${KILLDOMAIN}.ini

# Remove Root Site Defaults from inkDNS
sed -i "/; Root Site Defaults/,/;; End Root Site Defaults/d" /var/local/verb/configs/inkdns/zones/${KILLDOMAIN}.db
echo ";;; Root Site Defauls removed" >> /var/local/verb/configs/inkdns/zones/${KILLDOMAIN}.db

# Remove http folder symlinks
rm -f /var/www/html/${KILLDOMAIN}

# Restart
/etc/init.d/postfix reload
/etc/init.d/postfix restart

