#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This removes an existing domain from vip/_domains.vip

# How to use:
## ./killdomainvip [olddomain.tld]


OLDDOMAIN=$1

rm -f /srv/vip/_domains.vip/${OLDDOMAIN}
