#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This deletes an ftp guru and his vsftpd folder and home folder

# How to use:
## ./killftpguru [user]


DELFTPGURU=$1

# Delete the user
userdel ${DELFTPGURU}

# Remove directory
rm -rf /home/${DELFTPGURU}
