#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This deletes an ftp user and his vsftpd folder, home folder, web accessible folder, and all contents

# How to use:
## ./killftpuser [user]


DELFTPUSER=$1

# Delete the user
userdel ${DELFTPUSER}

# Remove directories and web symlink
rm -rf /srv/vsftpd/${DELFTPUSER}
rm -rf /home/${DELFTPUSER}
rm -f /var/www/guru/files/${NEWFTPUSER}
