#!/bin/sh
#inkVerbSerf! verb.ink
set -e

### LEGACY ###

# This kills a domain with OpenDKIM profiles and keys after it has been added with a newdomain or newdomaincgi
## This is NOT for a subdomain's OpenDKIM files or Apache files.
## To remove a subdomain from the Apache web server and OpenDKIM, use killsubdomain

## This ALSO:
### Removes the SSL certificate for the domain and all subdomains thereof.
## This DOES NOT:
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpguru can access
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.

# How to use:
## ./killdomainshell [KILLDOMAIN.tld]


KILLDOMAIN=$1

# Remove Apache server config files
rm -f /etc/apache2/sites-available/${KILLDOMAIN}.conf
rm -f /etc/apache2/sites-emabled/${KILLDOMAIN}.conf
service apache2 reload

# Remove http folder symlinks
rm -f /var/www/html/${KILLDOMAIN}

# inkCert
## This removes the declared domain from the end of the "domains =" line
cd /var/local/verb/configs/inkcert/cli-ini
rm -f siteinkcert.${KILLDOMAIN}
rm -f cli.${KILLDOMAIN}.ini
rm -f /etc/inkcert/cli.${KILLDOMAIN}.ini

# OpenDKIM
## This removes the declared domain key
rm -rf /etc/opendkim/keys/${KILLDOMAIN}
## This removes the killed domain key to the config files
sed -i "s/inkdkim\._domainkey\.${KILLDOMAIN} ${KILLDOMAIN}:inkdkim:\/etc\/opendkim\/keys\/${KILLDOMAIN}\/inkdkim\.private//g" /etc/opendkim/KeyTable
sed -i "s/${KILLDOMAIN} inkdkim._domainkey.${KILLDOMAIN}//g" /etc/opendkim/SigningTable
sed -i "s/${KILLDOMAIN}//g" /etc/opendkim/TrustedHosts
/etc/init.d/opendkim restart
/etc/init.d/postfix reload
/etc/init.d/postfix restart

# Finish
echo "The domain has been completely removed from the server. However, web files are still available to domain gurus and any subdomains sites are still life."

