#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This deletes a boss and its home folder.

# How to use:
## ./killboss [user]


DELBOSSUSER=$1

# Delete the user
userdel ${DELBOSSUSER}

# Remove directories and web symlink
rm -rf /home/${DELBOSSUSER}

