#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This reinstall MySQL with new bosses and passwords after it has been removed via mysqluninstall

# How to use:
## ./mysqlinstall


MYSQLPASS=$(pwgen -0 -1 -A -B 11)
MYSQLBOSSPASS=$(pwgen -s -1 10)

# Record the MySQL root password
echo "${MYSQLPASS}" > /var/local/verb/inst/mysqlrootpassword
echo "mysql-server mysql-server/root_password password ${MYSQLPASS}" | debconf-set-selections
echo "mysql-server mysql-server/root_password_again password ${MYSQLPASS}" | debconf-set-selections

# Install MySQL
apt -y install mysql-server mysql-client

# MySQL superuser to auto-create databases
mysql -uroot -p${MYSQLPASS} -e "
CREATE USER mysqlboss@localhost;
SET PASSWORD FOR mysqlboss@localhost=PASSWORD('${MYSQLBOSSPASS}');
GRANT ALL PRIVILEGES ON *.* TO 'mysqlboss'@'localhost' IDENTIFIED BY '${MYSQLBOSSPASS}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"
## Set the mysqlboss as the mysqlboss config file so the password is not in the line command
echo "[client]
user = mysqlboss
password = ${MYSQLBOSSPASS}
host = localhost" > /var/local/verb/configs/mysqlboss.cnf

