#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This completely removes MySQL
## WARNING: This WILL cause the Apocalypse!
## WARNING: Only use this if the Apocalypse already began and you are ready for fallout.
## WARNING: Your mail server, if installed, will permanently break and you'll have to install the entire server again.
## WARNING: Use only if you have a good reason. Re-installing the entire server from backups may save time.

# How to use:
## ./mysqluninstall


systemctl stop mysql
killall -KILL mysql mysqld_safe mysqld
apt --yes purge mysql-server mysql-client
apt --yes autoremove --purge
apt autoclean
deluser --remove-home mysql
delgroup mysql
rm -rf /etc/apparmor.d/abstractions/mysql /etc/apparmor.d/cache/usr.sbin.mysqld /etc/mysql /var/lib/mysql /var/log/mysql* /var/log/upstart/mysql.log* /var/run/mysqld
updatedb
exit

