#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This adds a user to an existing MySQL database with a password

# How to use:
## ./mysqldbusr [dbase] [dbuser] [dbpassword]


DBASE=$1
DBUSER=$2
DBPASSWORD=$3

mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
FLUSH PRIVILEGES;"

