#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This prepares core Verber config files for a domain, with OpenDKIM profiles and keys and inkCert and inkDNS configs, WITHOUT including the actual domain itself or its Apache configs and html folder.
## This is intended as a subscript to be used by adddomain or adddomaincgi
## This does NOT:
### Add the domain to inkCert for SSL requests
### Create Apache folders or configs for the domain
## For inkCert and Apache configs, use adddomain or adddomaincgi

# How to use:
## ./newdomainshell [newdomain.tld]


# Include settings
. /opt/verb/conf/sitenameip
. /opt/verb/conf/inkcert/inkcertstatus

NEWDOMAIN=$1

# inkCert
cp /opt/verb/conf/inkcert/cli-ini/cli.new.ini /opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini
sed -i "s/inkcertemail589/${INKCERTEMAIL}/g" /opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini
sed -i "s/newdomain589/${INKCERTEMAIL}/g" /opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini
echo "#!/bin/sh
INKCERTED=NOT_YET
" > /opt/verb/conf/inkcert/cli-ini/siteinkcert.${NEWDOMAIN}

# inkDKIM
/opt/verb/serfs/addinkdkim ${NEWDOMAIN}; wait

# inkDNS
/opt/verb/serfs/inkdnsadddomain ${NEWDOMAIN}; wait
/opt/verb/serfs/inkdnsaddmail ${NEWDOMAIN}; wait
/opt/verb/serfs/inkdnsaddinkdkim ${NEWDOMAIN}; wait

# Finish
echo "Great! With no error messages, ${NEWDOMAIN} is ready to be added on the Verber."

