#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This changes the password for an existing fossil user

# How to use:
## ./newfossilpass [existing-fossil-name] [username] [userpassword]

# Example:
## ./newfossilpass dinosaur adam AdamNuup4$$w0RD


# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

OLDFOSSIL=$1
OLDUSER=$2
NEWPASS=$3

cd /var/www/guru/fossil

# Change the password
fossil user password ${OLDUSER} ${NEWPASS} --repository ${OLDFOSSIL}.fossil

echo "New ${OLDFOSSIL}.fossil password set for ${OLDUSER}.
Available on web at fossil.${guruURI}/${OLDFOSSIL}.cgi"
