#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This creates a normal ftp user, owning a unique ftp folder accessible at files....verb.vip/FTPUSERNAME/
## Requires installvsftpd and activatefiles on

# How to use:
## ./newftpuser [new user] [new user password]


NEWFTPUSER=$1
NEWUSERPASS=$2

# Create the user with password
adduser ${NEWFTPUSER} --gecos ",,," --disabled-password
echo "${NEWFTPUSER}:${NEWUSERPASS}" | chpasswd

# Change the user's directory to the vsftpd vips directory
mkdir /srv/vsftpd/${NEWFTPUSER}
usermod -d /srv/vsftpd/${NEWFTPUSER} ${NEWFTPUSER}
restart vsftpd

# Create the link to access the folder via web
ln -s /srv/vsftpd/${NEWFTPUSER} /var/www/vip/files/

# Own the user's web accessible symlink folder
chown -R www-data:www-data /var/www/vip/files/${NEWFTPUSER}
