#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This creates a new fossil available at fossil.your-name.verb.guru/FOSSIL-NAME.cgi
## Prereq: fossil

# How to use:
## ./newfossil [new-fossil-name] [username] [user-email] [userpassword]

# Example:
## ./newfossil dinosaur adam adam@verb.ink Adamp4$$w0RD


# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

NEWFOSSIL=$1
NEWUSER=$2
NEWEMAIL=$3
NEWPASS=$4

# Create the fossil with user
cd /var/www/guru/fossil
fossil new ${NEWFOSSIL}.fossil --admin-user ${NEWUSER}

# Change the user's password
fossil user password ${NEWUSER} ${NEWPASS} --repository ${NEWFOSSIL}.fossil

# Write the .cgi file
echo "#!/usr/bin/fossil
repository: /fossil/${NEWFOSSIL}.fossil" > ${NEWFOSSIL}.cgi
chmod +x ${NEWFOSSIL}.cgi

# Final chown to allow database to be writable
chown -R www-data:www-data /var/www/guru/fossil

echo "${NEWFOSSIL}.fossil created.
Available on web at fossil.${guruURI}/${NEWFOSSIL}.cgi"

