#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This adds a new subdomain to become newsub.your-name.verb.one, and enables CGI.

# How to use:
## ./newonesubcgi [newsub only]


# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

NEWONESUB=$1

# Copy and prepare Apache server config files
cp /var/local/verb/configs/site-files/conf/newonesubcgi.conf /etc/apache2/sites-available/${NEWONESUB}.${oneURI}.conf 
sed -i "s/newonesub/${NEWONESUB}/g" /etc/apache2/sites-available/${NEWONESUB}.${oneURI}.conf
sed -i "s/oneURI286/${oneURI}/g" /etc/apache2/sites-available/${NEWUNOSUB}.${unoURI}.conf
cp -R /var/local/verb/configs/site-files/newonesubdir /var/www/one/${NEWONESUB}
chown -R www-data:www-data /var/www/one/${NEWONESUB}
a2ensite ${NEWONESUB}.${oneURI}
service apache2 reload
cp /var/www/html/one/index-newonesub.php /var/www/html/one/index-${NEWONESUB}.php
chown -R www-data:www-data /var/www/html/one

# inkCert, at end of the "domains =" line
sed -i "/^domains =/ s/$/, ${NEWONESUB}.${oneURI}/" /var/local/verb/configs/inkcert/cli-ini/cli.${oneURI}.ini

