#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a new subdomain to become newsub.your-name.verb.vip, accessible in the _subs.vip folder.
# Dependencies: vsftpd and ftpvip or ftpfiler, run: installvsftpd, and newftpvip and/or newftpfiler

# How to use:
## ./newvipsub [newsub only]


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

NEWVIPSUB=$1

# Copy and prepare Apache server config files
/bin/cp /opt/verb/conf/site-files/conf/newvipsub.conf /etc/apache2/sites-available/${NEWVIPSUB}.${vipURI}.conf 
/bin/sed -i "s/newvipsub/${NEWVIPSUB}/g" /etc/apache2/sites-available/${NEWVIPSUB}.${vipURI}.conf
/bin/sed -i "s/vipURI286/${vipURI}/g" /etc/apache2/sites-available/${NEWVIPSUB}.${vipURI}.conf
/bin/cp -R /opt/verb/conf/site-files/newvipsubdir /var/www/vip/_subs.vip/${NEWVIPSUB}
/bin/chown -R www-data:www-data /var/www/vip/_subs.vip/${NEWVIPSUB}
/usr/sbin/a2ensite ${NEWVIPSUB}.${vipURI}
/usr/sbin/apache2ctl graceful
/bin/cp /var/www/html/vip/index-newvipsub.php /var/www/html/vip/index-${NEWVIPSUB}.php
/bin/chown -R www-data:www-data /var/www/html/vip

# inkCert, at end of the "domains =" line
/bin/sed -i "/^domains =/ s/$/, ${NEWONESUB}.${vipURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${vipURI}.ini

