#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a new subdomain to become newsub.your-name.verb.vip, accessible in the _subs.vip folder, and enables CGI.
# Prereq: vsftpd and ftpvip or ftpfiler

# How to use:
## ./newvipsubcgi [newsub only]


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

NEWVIPSUB=$1

# Copy and prepare Apache server config files
/bin/cp /opt/verb/conf/site-files/conf/newvipsubcgi.conf /etc/apache2/sites-available/${NEWVIPSUB}.${vipURI}.conf 
/bin/sed -i "s/newvipsub/${NEWVIPSUB}/g" /etc/apache2/sites-available/${NEWVIPSUB}.${vipURI}.conf
/bin/sed -i "s/vipURI286/${vipURI}/g" /etc/apache2/sites-available/${NEWVIPSUB}.${vipURI}.conf
/bin/cp -R /opt/verb/conf/site-files/newvipsubdir /var/www/vip/_subs.vip/${NEWVIPSUB}
/bin/chown -R www-data:www-data /var/www/vip/_subs.vip/${NEWVIPSUB}
/usr/sbin/a2ensite ${NEWVIPSUB}.${vipURI}
/usr/sbin/apache2ctl graceful
/bin/cp /var/www/html/vip/index-newvipsub.php /var/www/html/vip/index-${NEWVIPSUB}.php
/bin/chown -R www-data:www-data /var/www/html/vip

# inkCert, at end of the "domains =" line
/bin/sed -i "/^domains =/ s/$/, ${NEWVIPSUB}.${vipURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${vipURI}.ini

