#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This adds a verb domain, already created, to the OpenDKIM library so it can be used in email on the DNS.
## This is a selected redundancy from newdomain, excluding all the work already done for verb domains.
## This is necessary for non- .ink verb domains because installpostfix/installemail only creates OpenDKIM keys for NAMESPACE.verb.ink

# How to use:
## ./newverbdkim [verbtld only]

# Eg:
## ./newverbdkim kiwi


# Include the config
. /var/local/verb/configs/sitenameip

VERBDOMAIN=$1

# OpenDKIM
## This creates the declared domain key
mkdir -p /etc/opendkim/keys/${VERBDOMAIN}
cd /etc/opendkim/keys/${VERBDOMAIN}
opendkim-genkey -r -d ${VERBDOMAIN}
chown opendkim:opendkim inkdkim.private
## This adds the new domain key to the config files
echo "inkdkim._domainkey.${VERBDOMAIN} ${VERBDOMAIN}:inkdkim:/etc/opendkim/keys/${VERBDOMAIN}/inkdkim.private" >> /etc/opendkim/KeyTable
echo "${VERBDOMAIN} inkdkim._domainkey.${VERBDOMAIN}" >> /etc/opendkim/SigningTable
echo "${VERBDOMAIN}" >> /etc/opendkim/TrustedHosts
/etc/init.d/opendkim restart
/etc/init.d/postfix reload
/etc/init.d/postfix restart

echo "Great! With no error messages, ${VERBDOMAIN} has an OpenDKIM key. Use showdkim to get it."
