#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This sets up a new single default verb.ink subdomain Apache config file, standard http dir, and letsencrypt declaration in cli.inkverb.ini.
## This is intended to be run as an appendage after setupverb has already set the server.
## For pre-make creation, refer to makepreverbsub and make-apache in verb/verb-install

# How to use:
## ./newverbsub [TLD] [SUBDOMAIN]


TLD=$1
SUBDOMAIN=$2

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

## Domain Mod?
if grep -Fq "SITENAME=DOMAIN_MOD-" /opt/verb/conf/sitenameip; then
tldURI="${TLD}.${baseDOM}"
else
tldURI="${SITENAME}.verb.${TLD}"
fi

# Copy the file
cp /opt/verb/conf/site-files/conf/sub286.tldURI286.conf /etc/apache2/sites-available/${SUBDOMAIN}.${tldURI}.conf

# Replace
sed -i "s/sub286/${SUBDOMAIN}/g" /etc/apache2/sites-available/${SUBDOMAIN}.${tldURI}.conf
sed -i "s/tldURI286/${tldURI}/g" /etc/apache2/sites-available/${SUBDOMAIN}.${tldURI}.conf
sed -i "s/tld286/${TLD}/g" /etc/apache2/sites-available/${SUBDOMAIN}.${tldURI}.conf

# inkCert, at end of the "domains =" line
sed -i "/^domains =/ s/$/, ${SUBDOMAIN}.${tldURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${tldURI}.ini

# Create the http dir
cd /var/www/html
cp -R 0ne ${TLD}.${SUBDOMAIN}
chown -R www-data:www-data /var/www/html/${TLD}.${SUBDOMAIN}

# Apache
## If setupverb has already run
if [ ! -f "/opt/verb/inst/setupverb" ]; then
echo "...reloading Apache..."
a2ensite ${SUBDOMAIN}.${tldURI}
apache2ctl graceful

# inkCert
## If inkCert has already run
 if [ -f  "/opt/verb/conf/inkcert/cli-ini/siteinkcert.${tldURI}" ]; then
 echo "Updating inkCert SSL certs to include ${SUBDOMAIN}.${tldURI}..."
 /opt/verb/serfs/inkcertreqle ${tldURI} r
 /opt/verb/serfs/inkcertaddallle ${tldURI}
 else
 echo "${SUBDOMAIN}.${tldURI} will get its SSL certs when you run inkCert for ${tldURI}."
 fi
else
echo "${SUBDOMAIN}.${tldURI} will be activated with the crew when you run setupverb."
fi

# Finish
echo "
${SUBDOMAIN}.${tldURI} is all set to go.
But, remember it is not part of the native Verber package. This is an aftermarket mod that inkVerb will not maintain.
"

