#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This sets up a new single default verb.ink subdomain Apache config file, standard http dir, and letsencrypt declaration in cli.inkverb.ini.
## This is intended to be run as an appendage after setupverb has already set the server.
## For pre-make creation, refer to makepreverbsub and make-apache in verb/verb-install

# How to use:
## ./newverbsub [TLD] [SUBDOMAIN]


TLD=$1
SUBDOMAIN=$2

# Include the config file
. /var/local/verb/configs/sitenameip

# Copy the file
cp /var/local/verb/configs/site-files/sub286.${SITENAME}.verb.tld286.conf /etc/apache2/sites-available/${SUBDOMAIN}.${SITENAME}.verb.${TLD}.conf

# Replace
sed -i "s/sub286/${SUBDOMAIN}/g" /etc/apache2/sites-available/${SUBDOMAIN}.${SITENAME}.verb.${TLD}.conf
sed -i "s/tld286/${TLD}/g" /etc/apache2/sites-available/${SUBDOMAIN}.${SITENAME}.verb.${TLD}.conf

# inkCert, at end of the "domains =" line
sed -i "/^domains =/ s/$/, ${SUBDOMAIN}.${SITENAME}.verb.${TLD}/" /var/local/verb/configs/inkcert/cli-ini/cli.${SITENAME}.verb.${TLD}.ini

# Create the http dir
cd /var/www/html
cp -R 0ne ${TLD}.${SUBDOMAIN}
chown -R www-data:www-data /var/www/html/${TLD}.${SUBDOMAIN}

# Apache
## If setupverb has already run
if [ ! -f "/var/local/verb/inst/setupverb" ]; then
echo "...reloading Apache..."
a2ensite ${SUBDOMAIN}.${SITENAME}.verb.${TLD}
service apache2 reload

# inkCert
## If inkCert has already run
 if [ -f  "/var/local/verb/configs/inkcert/cli-ini/siteinkcert.${SITENAME}.verb.${TLD}" ]; then
 echo "Updating inkCert SSL certs to include ${SUBDOMAIN}.${SITENAME}.verb.${TLD}..."
 /var/local/verb/serfs/inkcertreqle ${SITENAME}.verb.${TLD} r
 /var/local/verb/serfs/inkcertaddallle ${SITENAME}.verb.${TLD}
 else
 echo "${SUBDOMAIN}.${SITENAME}.verb.${TLD} will get its SSL certs when you run inkCert for ${SITENAME}.verb.${TLD}."
 fi
else
echo "${SUBDOMAIN}.${SITENAME}.verb.${TLD} will be activated with the crew when you run setupverb."
fi

# Finish
echo "
${SUBDOMAIN}.${SITENAME}.verb.${TLD} is all set to go.
But, remember it is not part of the native Verber package. This is an aftermarket mod that inkVerb will not maintain.
"

