#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This adds a new subdomain to become newsub.your-name.verb.vip, accessible in the _subs.vip folder.
# Dependencies: vsftpd and ftpvip or ftpfiler, run: installvsftpd, and newftpvip and/or newftpfiler

# How to use:
## ./newvipsub [newsub only]


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

NEWVIPSUB=$1

# Copy and prepare Apache server config files
cp /opt/verb/conf/site-files/conf/newvipsub.conf /etc/apache2/sites-available/${NEWVIPSUB}.${vipURI}.conf 
sed -i "s/newvipsub/${NEWVIPSUB}/g" /etc/apache2/sites-available/${NEWVIPSUB}.${vipURI}.conf
sed -i "s/vipURI286/${vipURI}/g" /etc/apache2/sites-available/${NEWVIPSUB}.${vipURI}.conf
cp -R /opt/verb/conf/site-files/newvipsubdir /var/www/vip/_subs.vip/${NEWVIPSUB}
chown -R www-data:www-data /var/www/vip/_subs.vip/${NEWVIPSUB}
a2ensite ${NEWVIPSUB}.${vipURI}
apache2ctl graceful
cp /var/www/html/vip/index-newvipsub.php /var/www/html/vip/index-${NEWVIPSUB}.php
chown -R www-data:www-data /var/www/html/vip

# inkCert, at end of the "domains =" line
sed -i "/^domains =/ s/$/, ${NEWONESUB}.${vipURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${vipURI}.ini

