#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This script allows all of a user's main inkVerb subdomains to point to preferred apps, 
# This is mainly aesthetic, defining a particular web app to be the king of its color

# How to use:
## ./pointink [subdomain only]

# Eg: (To point name.verb.red to hrm.your-name.verb.red do:)
## ./pointink hrm.red

# Type ./pointink -h for help


# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

if [ "$1" = "-h" ]; then
    echo "Usage: ./pointink [subdomin only]

Examples:
 ./pointink crm.red (points ${redURI} to crm.your-name.verb.red)
 ./pointink red (resets ${redURI} to point to itself)

 allowed arguments:
 blue
 chat.blue
 collabora.blue
 nextcloud.blue
 owncloud.blue
 pydio.blue
 seafile.blue
 xmpp.blue
 guru
 cgi.guru
 ftp.guru
 files.guru
 fossil.guru
 net2ftp.guru
 mysql.guru
 repo.guru
 kiwi
 kiwi.ampache
 kiwi.art
 kiwi.ejabberd
 kiwi.gallery
 kiwi.media
 kiwi.podcast
 kiwi.prosody
 kiwi.studio
 kiwi.voip
 kiwi.webrtc
 red
 crm.red
 erp.red
 hrm.red
 odoo.red
 scm.red
"
exit 0
fi

if [ "$1" = 0 ]; then
    echo "No parameters set. Use ./pointink -h for help"
exit 0
fi

if [ "$1" = "blue" ]; then
    cp /var/www/html/blue/index-blue.php /var/www/html/blue/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "chat.blue" ]; then
    cp /var/www/html/blue/index-chat.php /var/www/html/blue/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "collabora.blue" ]; then
    cp /var/www/html/blue/index-collabora.php /var/www/html/blue/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "nextcloud.blue" ]; then
    cp /var/www/html/blue/index-nextcloud.php /var/www/html/blue/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "owncloud.blue" ]; then
    cp /var/www/html/blue/index-owncloud.php /var/www/html/blue/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "pydio.blue" ]; then
    cp /var/www/html/blue/index-pydio.php /var/www/html/blue/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "seafile.blue" ]; then
    cp /var/www/html/blue/index-seafile.php /var/www/html/blue/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "xmpp.blue" ]; then
    cp /var/www/html/blue/index-xmpp.php /var/www/html/blue/index.php
    echo "Done."
exit 0
fi


if [ "$1" = "guru" ]; then
    cp /var/www/html/guru/index-guru.php /var/www/html/guru/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "cgi.guru" ]; then
    cp /var/www/html/guru/index-ftp.php /var/www/html/guru/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "ftp.guru" ]; then
    cp /var/www/html/guru/index-ftp.php /var/www/html/guru/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "files.guru" ]; then
    cp /var/www/html/guru/index-files.php /var/www/html/guru/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "fossil.guru" ]; then
    cp /var/www/html/guru/index-fossil.php /var/www/html/guru/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "net2ftp.guru" ]; then
    cp /var/www/html/guru/index-net2ftp.php /var/www/html/guru/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "repo.guru" ]; then
    cp /var/www/html/guru/index-repo.php /var/www/html/guru/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "sql.guru" ]; then
    cp /var/www/html/guru/index-sql.php /var/www/html/guru/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi" ]; then
    cp /var/www/html/kiwi/index-kiwi.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi.ampache" ]; then
    cp /var/www/html/kiwi/index-ampache.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi.art" ]; then
    cp /var/www/html/kiwi/index-art.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi.ejabberd" ]; then
    cp /var/www/html/kiwi/index-ejabberd.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi.gallery" ]; then
    cp /var/www/html/kiwi/index-gallery.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi.media" ]; then
    cp /var/www/html/kiwi/index-media.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi.podcast" ]; then
    cp /var/www/html/kiwi/index-podcast.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi.prosody" ]; then
    cp /var/www/html/kiwi/index-prosody.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi.studio" ]; then
    cp /var/www/html/kiwi/index-studio.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi.voip" ]; then
    cp /var/www/html/kiwi/index-voip.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "kiwi.webrtc" ]; then
    cp /var/www/html/kiwi/index-webrtc.php /var/www/html/kiwi/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "red" ]; then
    cp /var/www/html/red/index-red.php /var/www/html/red/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "crm.red" ]; then
    cp /var/www/html/red/index-crm.php /var/www/html/red/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "erp.red" ]; then
    cp /var/www/html/red/index-hrm.php /var/www/html/red/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "hrm.red" ]; then
    cp /var/www/html/red/index-hrm.php /var/www/html/red/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "odoo.red" ]; then
    cp /var/www/html/red/index-odoo.php /var/www/html/red/index.php
    echo "Done."
exit 0
fi

if [ "$1" = "scm.red" ]; then
    cp /var/www/html/red/index-hrm.php /var/www/html/red/index.php
    echo "Done."
exit 0
fi

