#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This script points your-name.verb.one subdomains to custom-made subdomains, 

# How to use:
## ./pointguru [subdomain only]

# Eg: (This will point name.verb.guru to lucky.your-name.verb.guru)
## ./pointguru lucky

# Type ./pointguru -h for help


# Include the config file
. /var/local/verb/configs/sitenameip

if [ "$1" = "-h" ]; then
    echo "Usage: ./pointguru [subdomain only]
Examples:
 ./pointguru lucky (points ${SITENAME}.verb.guru to lucky.your-name.verb.one
 ./pointguru verb.guru (resets ${SITENAME}.verb.guru to point to itself)
 you may use any subdomain you want except
 verb.guru, which will reset ${SITENAME}.verb.guru
 and
 cgi, fpt, files, fossil, mysql, net2ftp, repo which are already taken."
exit 0
fi

if [ "$1" = "verb.guru" ]; then
    cp /var/www/html/guru/index-guru.php /var/www/html/guru/index.php
    echo "Reset, done."
exit 0
fi

if [ "$1" = "cgi" ]; then
    echo "That one's already taken. Sorry, sparky."
exit 0
fi

if [ "$1" = "ftp" ]; then
    echo "That one's already taken. Sorry, sparky."
exit 0
fi

if [ "$1" = "files" ]; then
    echo "That one's already taken. Sorry, sparky."
exit 0
fi

if [ "$1" = "fossil" ]; then
    echo "That one's already taken. Sorry, sparky."
exit 0
fi

if [ "$1" = "mysql" ]; then
    echo "That one's already taken. Sorry, sparky."
exit 0
fi

if [ "$1" = "net2ftp" ]; then
    echo "That one's already taken. Sorry, sparky."
exit 0
fi

if [ "$1" = "repo" ]; then
    echo "That one's already taken. Sorry, sparky."
exit 0
fi

NEWONESUB=$1

    cp /var/www/html/guru/index-newgurusub.php /var/www/html/guru/index.php
    sed -i "s/newgurusub/${NEWONESUB}/g" /var/www/html/guru/index.php
    echo "Pointing to http://${NEWONESUB}.${SITENAME}.verb.guru, done."
exit 0
