#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This script points your-name.verb.uno to custom-made subdomains

# How to use:
## ./pointuno [subdomain only]

# Eg: (This will point your-name.verb.uno to lucky.your-name.verb.uno)
## ./pointuno lucky

# Type ./pointuno -h for help


# Include the config
. /var/local/verb/configs/siteurilist

if [ "$1" = "-h" ]; then
    echo "Usage: ./pointuno [subdomain only]
Examples:
 ./pointuno lucky (points ${unoURI} to lucky.${unoURI}
 ./pointuno verb.uno (resets ${unoURI} to point to itself)

 Make sure the .${unoURI} subdomain exists
 Then, you may use any subdomain you want except
 verb.uno
 which will reset ${unoURI}"
exit 0
fi

if [ "$1" = "verb.uno" ]; then
    cp /var/www/html/uno/index-uno.php /var/www/html/uno/index.php
    echo "Reset, done."
exit 0
fi

NEWUNOSUB=$1

    cp /var/www/html/uno/index-newunosub.php /var/www/html/uno/index.php
    sed -i "s/newunosub/${NEWUNOSUB}/g" /var/www/html/uno/index.php
    echo "Pointing to http://${NEWUNOSUB}.${unoURI}, done."
exit 0

