#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This should be run after SuiteCRM has successfully been installed at crm.your-name.verb.red

# How to use:
## ./postinstallscrm


# Set installer to false
echo "*    *    *    *    *     cd /var/www/vapps/suitecrm; php -f cron.php > /dev/null 2>&1" >> /var/local/verb/configs/verbcron
cp /var/local/verb/configs/verbcron /etc/cron.d/verber

# Finish
echo "SuiteCRM cron job has been added to the system."

