#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This should be run after PostfixAdmin has been setup through the web interface

# How to use:
## ./postinstallpfa


# Deny http access to the setup file
echo "<Files "setup.php">
deny from all
</Files>" > /var/www/email/postfixadmin/.htaccess
chown -R www-data:www-data /var/www/email/postfixadmin/.htaccess

# Set the setup password so it can't work until setpfapass runs agian
sed -i "s/$CONF\['setup_password'\] = .*/$CONF\['setup_password'\] = ''; #NOT_SET_RUN_setup_THEN_pfapass/g" /var/www/email/postfixadmin/config.local.php
sed -i "/\/\/ With this long hash/d" /var/www/email/postfixadmin/config.local.php

# Finish
echo "Finished. PostfixAdmin Setup disallowed and the setup password disabled."

