#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This should be run after roundcube has been setup through the web interface at rc.your-name.verb.email/rcpath

# How to use:
## ./postinstallrc


# Set installer to false
sed -i "s/\$config\['enable_installer'\].*/\$config\['enable_installer'\] = false;/g" /var/www/email/roundcube/config/config.inc.php

echo "Finished. Roudcube installer disabled."
