#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This disables the ability for a root user to login over ssh with a password
## This presumes that the ssh .pub keys have already been added to ~/.ssh/authorized_keys

# How to use:
## ./rootloginoff

sed -i "s/PermitRootLogin.*/PermitRootLogin without-password/g" /etc/ssh/sshd_config
service ssh reload

