#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This sets new site-wide SSH CA
## Theoretically, this should not be necessary unless inkVerb makes changes to their own domain.

# How to use:
## ./setinkcertsshca [inkCert SSH CA]

# Eg:
## ./setinkcertsshca sshca.inkisaverb.com


INKSSHCA=$1

sed -i "s/INKCERTSSHCA=.*/INKCERTSSHCA=\"${INKSSHCA}\"/g" /opt/verb/conf/inkcert/inkcertstatus

