#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This sets a new IPv4 address on the server

# How to use:
## ./setip4 [IPv4 number]


# Include the config file
. /opt/verb/conf/sitenameip

NEWIP4=$1

# Normal IP
sed -i "s/SITEIP\..*/SITEIP=\"${NEWIP4}\"/" /opt/verb/conf/sitenameip
sed -i "s/${SITEIP}/${NEWIP4}/" /etc/hosts

# ARPA & inverse IP
## THANKS https://unix.stackexchange.com/a/132806/315069
NEWARPAIP4=$(echo ${NEWIP4} | sed -r 's/^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/\4.\3.\2.\1.in-addr.arpa/')
sed -i "s/SITEARPAIP4.*/SITEARPAIP4=\"${NEWARPAIP4}\"/" /opt/verb/conf/sitenameip

# Finish
echo "IPv4 now set to: ${NEWIP4}"
