#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This sets new site-wide SSL CA
## Theoretically, this should not be necessary unless inkVerb makes changes to their own domain.

# How to use:
## ./setinkcertsslca [inkCert SSL CA]

# Eg:
## ./setinkcertsslca sslca.inkisaverb.com


INKSSLCA=$1

sed -i "s/INKCERTSSLCA=.*/INKCERTSSLCA=\"${INKSSLCA}\"/g" /var/local/verb/configs/inkcert/inkcertstatus

