#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This turns on bruteforce protection for nextcloud

# How to use:
## ./setnextcloudbfdon


# First remove any existing declaration for this setting
sed -i "/  'auth\.bruteforce\.protection\.enabled.*/d" /var/www/vapps/nextcloud/config/config.php

# Put the setting just before the close of the settings array
sed -i "s/);/  'auth\.bruteforce\.protection\.enabled' => false,\n);/" /var/www/vapps/nextcloud/config/config.php
