#!/bin/sh
#inkVerbSerf! verb.ink

# This changes the path of the PostfixAdmin web path
## This changes the path already set by installfpa

# How to use:
## ./setpfapath [folder]

# Eg:
## To use at pfa.NAME.verb.email/mysecretpath do: ./installpfa easy mysecretpath


# Include the config files
. /opt/verb/conf/sitenameip
. /opt/verb/conf/sitemailpath

PFAFOLDER=$1

/bin/rm -rf /var/www/html/${SITEEMAILTLD}.pfa
/bin/cp -R /var/www/html/0ne /var/www/html/${SITEEMAILTLD}.pfa
/bin/ln -s /var/www/email/postfixadmin /var/www/html/${SITEEMAILTLD}.pfa/${PFAFOLDER}
/bin/chown -R www-data:www-data /var/www/html/${SITEEMAILTLD}.pfa
/bin/sed -i "s/SITEPFAPATH=.*/SITEPFAPATH=\"${PFAFOLDER}\"/g" /opt/verb/conf/sitemailpass
/bin/sed -i "s/\$CONF\['postfix_admin_url'\] = 'https:\/\/.*/\$CONF\['postfix_admin_url'\] = 'https:\/\/pfa\.${SITENAME}\.verb\.${SITEEMAILTLD}\/${PFAFOLDER}';/g" /var/www/email/postfixadmin/config.inc.php

