#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This changes the path of the PostfixAdmin web path
## This changes the path already set by installfpa

# How to use:
## ./setpfapath [folder]

# Eg:
## To use at pfa.NAME.verb.email/mysecretpath do: ./installpfa easy mysecretpath


# Include the config file
. /opt/verb/conf/sitenameip
. /opt/verb/conf/sitemailpath

PFAFOLDER=$1

rm -rf /var/www/html/${SITEEMAILTLD}.pfa
cp -R /var/www/html/0ne /var/www/html/${SITEEMAILTLD}.pfa
ln -s /var/www/email/postfixadmin /var/www/html/${SITEEMAILTLD}.pfa/${PFAFOLDER}
chown -R www-data:www-data /var/www/html/${SITEEMAILTLD}.pfa
sed -i "s/SITEPFAPATH=.*/SITEPFAPATH=\"${PFAFOLDER}\"/g" /opt/verb/conf/sitemailpass
sed -i "s/\$CONF\['postfix_admin_url'\] = 'https:\/\/.*/\$CONF\['postfix_admin_url'\] = 'https:\/\/pfa\.${SITENAME}\.verb\.${SITEEMAILTLD}\/${PFAFOLDER}';/g" /var/www/email/postfixadmin/config.inc.php

