#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This sets the inkGet repo version list so that it will not automatically update when the Verber is updated

# How to use:
## ./setrepocust


sed -i "s/INKGET_LIST=.*/INKGET_LIST=\"CUSTOM\"/g" /opt/verb/conf/siteinkget

