#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This changes the path of the RoundCube web path
## This changes the path already set by installrc

# How to use:
## ./setrcpath [folder]

# Eg:
## (To use at pfa.NAME.verb.email/mysecretpath do:)
## ./installpfa easy mysecretpath


# Include the config file
. /opt/verb/conf/sitenameip
. /opt/verb/conf/sitemailpath

RCFOLDER=$1

rm -rf /var/www/html/${SITEEMAILTLD}.rc
cp -R /var/www/html/0ne /var/www/html/${SITEEMAILTLD}.rc
ln -s /var/www/email/roundcube /var/www/html/${SITEEMAILTLD}.rc/${RCFOLDER}
chown -R www-data:www-data /var/www/html/${SITEEMAILTLD}.rc
sed -i "s/SITERCPATH=.*/SITERCPATH=\"${RCFOLDER}\"/g" /opt/verb/conf/sitemailpass
sed -i "s/\$CONF\['footer_link'\] = 'https:\/\/.*/\$CONF\['footer_link'\] = 'https:\/\/rc\.${SITENAME}\.verb\.${SITEEMAILTLD}\/${RCFOLDER}';/g" /var/www/email/postfixadmin/config.inc.php
