#!/bin/bash
#inkVerbSerf! verb.ink


# This creates and sets the serve.NAME.verb.TLD webspace to serve files needed for download
## This is run automatically by setupverb
## If no argument is made, this will only remake the directory without changing the TLD or its URI.

# How to use:
## ./setserve [ TLD - optional ]

# Eg:
## ./setserve  # Do this if you only want to change the download directory's name, a good idea for security.
## ./setserve email
## ./setserve ink


# Set the variables
. /opt/verb/conf/sitenameip
if [ -z "${1}" ]; then
  vTLD="${SITESERVE}"
else
  vTLD="${1}"
fi
sDIR="$(pwgen -s -1 128)"
nServeURI="${vTLD}URI"
CHECKtld="VERB${vTLD}"

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitetldstatus

# Check and set the configs
if [ "${!CHECKtld}" != true ]; then
echo "Not an acceptable TLD, chose a valid TLD."; exit 0; fi

# Remove the old settings
rm -f /etc/apache2/sites-available/${serveURI}.conf
sed -i "s/ ${serveURI}//g" /opt/verb/conf/inkcert/cli-ini/cli.*

sed -i "s/SITESERVE=.*/SITESERVE=\"${vTLD}\"/" /opt/verb/conf/sitenameip
sed -i "s/SERVEDIR=.*/SERVEDIR=\"${sDIR}\"/" /opt/verb/conf/sitenameip
sed -i "s/SERVEPATH=.*/SERVEPATH=\"serve\.${!nServeURI}\/${sDIR}\"/" /opt/verb/conf/sitenameip
sed -i "s/serveURI=.*/serveURI=\"serve\.${!nServeURI}\"/" /opt/verb/conf/siteurilist
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Apache
cp /opt/verb/conf/site-files/conf/serve.conf /etc/apache2/sites-available/${serveURI}.conf
sed -i "s/serveURI286/${serveURI}/g" /etc/apache2/sites-available/${serveURI}.conf
sed -i "s/serveTLD286/${vTLD}/g" /etc/apache2/sites-available/${serveURI}.conf
a2ensite ${serveURI}
systemctl reload apache2

# inkCert
## Ensure that you don't get double entries
sed -i "s/ ${serveURI}//g" /opt/verb/conf/inkcert/cli-ini/cli.${!nServeURI}.ini
## Add it to the cli-ini
sed -i "/^domains =/ s/$/${serveURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${!nServeURI}.ini

# Create the serve dir
rm -rf /var/www/html/${vTLD}.serve
mkdir -p /var/www/html/${vTLD}.serve/${sDIR}
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${nameURI}\"); die(); ?>" > /var/www/html/${vTLD}.serve/index.php
chmod -R 750 /var/www/html/${vTLD}.serve

# Create cron to delete download directories
echo "#!/bin/sh
# inkNet cron, verb.ink
find /var/www/html/${vTLD}.serve/${sDIR}/* -type d -mmin +30 -exec rm -rf {} \;
" > /opt/verb/conf/inknet/rmdldirs.sh
chmod 750 /opt/verb/conf/inknet/rmdldirs.sh
echo '14,44 * * * * root /opt/verb/conf/inknet/rmdldirs.sh > /dev/null 2>&1' > /etc/cron.d/rmdldirs
chmod 0644 /etc/cron.d/rmdldirs

# DNS
echo "; Subdomain Records Added by inkDNS ${serveURI}" >> /opt/verb/conf/inkdns/zones/db.${!nServeURI}
echo "${serveURI}\tIN  A\t\t${SITEIP}" >> /opt/verb/conf/inkdns/zones/db.${!nServeURI}
echo "${serveURI}\tIN  AAAA\t\t${SITEIPV6}" >> /opt/verb/conf/inkdns/zones/db.${!nServeURI}
## Set the Serial No
/opt/verb/serfs/inkdnsserial ${!nServeURI}

# Finish
echo "Service download files set to: https://${SERVEPATH}"
