#!/bin/sh
#inkVerbSerf! verb.ink

# This sets the symlink for a vapp from the html/ folder to the vapps/ folder

# How to use:
## ./setvapplinkon [vapp name]


# Include the config file
. /opt/verb/conf/siteport
. /opt/verb/conf/siteurilist

VAPPNAME=$1

case ${VAPPNAME} in

ampache)
/bin/rm -rf /var/www/html/kiwi.ampache
/bin/ln -s /var/www/vapps/${VAPPNAME} /var/www/html/kiwi.ampache
/bin/echo "${VAPPNAME} symlink is set."
;;

fossil)
/bin/rm -rf /var/www/html/vip.fossil
/bin/ln -sfn /var/www/vip/${VAPPNAME} /var/www/html/vip.fossil
/bin/echo "${VAPPNAME} symlink is set."
;;

mediawiki)
/bin/rm -rf /var/www/html/ink.wiki
/bin/ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/ink.wiki
/bin/echo "${VAPPNAME} symlink is set."
;;

net2ftp)
/bin/rm -rf /var/www/html/vip.net2ftp
/bin/ln -s /var/www/vapps/${VAPPNAME} /var/www/html/vip.net2ftp
/bin/echo "${VAPPNAME} symlink is set."
;;

nextcloud)
/bin/rm -rf /var/www/html/blue.nc
/bin/ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/blue.nc
/bin/echo "${VAPPNAME} symlink is set."
;;

orangehrm)
/bin/rm -rf /var/www/html/red.hrm
/bin/ln -s /var/www/vapps/${VAPPNAME} /var/www/html/red.hrm
/bin/echo "${VAPPNAME} symlink is set."
;;

owa)
/bin/rm -rf /var/www/html/red.owa
/bin/ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/red.owa
/bin/echo "${VAPPNAME} symlink is set."
;;

owncloud)
/bin/rm -rf /var/www/html/blue.owncloud
/bin/ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/blue.owncloud
/bin/echo "${VAPPNAME} symlink is set."
;;

suitecrm)
/bin/rm -rf red.crm
/bin/ln -s /var/www/vapps/${VAPPNAME} /var/www/html/red.crm
/bin/echo "${VAPPNAME} symlink is set."
;;

october.inkblog)
/bin/rm -rf /var/www/html/ink.blog
/bin/ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/ink.blog
/bin/echo "${VAPPNAME} symlink is set."
;;

wp.inkbb)
/bin/rm -rf /var/www/html/ink.bb
/bin/ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/ink.bb
/bin/echo "${VAPPNAME} symlink is set."
;;

wp.inkblog)
/bin/rm -rf /var/www/html/ink.blog
/bin/ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/ink.blog
/bin/echo "${VAPPNAME} symlink is set."
;;

esac

