#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This sets the symlink for a vapp from the html/ folder to the vapps/ folder

# How to use:
## ./setvapplinkon [vapp name]


# Include the config file
. /opt/verb/conf/siteport
. /opt/verb/conf/siteurilist

VAPPNAME=$1

case ${VAPPNAME} in

ampache)
rm -rf /var/www/html/kiwi.ampache
ln -s /var/www/vapps/${VAPPNAME} /var/www/html/kiwi.ampache
echo "${VAPPNAME} symlink is set."
;;

fossil)
rm -rf /var/www/html/vip.fossil
ln -sfn /var/www/vip/${VAPPNAME} /var/www/html/vip.fossil
echo "${VAPPNAME} symlink is set."
;;

mediawiki)
rm -rf /var/www/html/ink.wiki
ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/ink.wiki
echo "${VAPPNAME} symlink is set."
;;

net2ftp)
rm -rf /var/www/html/vip.net2ftp
ln -s /var/www/vapps/${VAPPNAME} /var/www/html/vip.net2ftp
echo "${VAPPNAME} symlink is set."
;;

nextcloud)
rm -rf /var/www/html/blue.nc
ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/blue.nc
echo "${VAPPNAME} symlink is set."
;;

orangehrm)
rm -rf /var/www/html/red.hrm
ln -s /var/www/vapps/${VAPPNAME} /var/www/html/red.hrm
echo "${VAPPNAME} symlink is set."
;;

owncloud)
rm -rf /var/www/html/blue.owncloud
ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/blue.owncloud
echo "${VAPPNAME} symlink is set."
;;

suitecrm)
rm -rf red.crm
ln -s /var/www/vapps/${VAPPNAME} /var/www/html/red.crm
echo "${VAPPNAME} symlink is set."
;;

october.inkblog)
rm -rf /var/www/html/ink.blog
ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/ink.blog
echo "${VAPPNAME} symlink is set."
;;

wp.inkbb)
rm -rf /var/www/html/ink.bb
ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/ink.bb
echo "${VAPPNAME} symlink is set."
;;

wp.inkblog)
rm -rf /var/www/html/ink.blog
ln -sfn /var/www/vapps/${VAPPNAME} /var/www/html/ink.blog
echo "${VAPPNAME} symlink is set."
;;

esac

