#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This sets the vapp MySQL vbak cron job

# How to use:
## ./setvappmysqlvbakon

echo '15 1 * * * root /opt/verb/donjon/vapp.mysql.vbak.sh' > /etc/cron.d/vappmysql-vbak
chmod 0644 /etc/cron.d/vappmysql-vbak
