#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This displays the inkDKIM information in OpenDKIM for a specific domain so it can be added to an opendkim txt record in the DNS file
## inkDKIM is the inkVerb method of handling OpenDKIM keys

# How to use:
## ./showinkdkim [domain.tld]


DOMAIN=$1

cat /etc/opendkim/keys/${DOMAIN}/inkdkim.txt

