#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This displays the settings and info for this Verber
## This is useful for many things, including Clients that need name and IP to connect to it

# How to use:
## ./showverber


# Include the config
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/sitemailpath

# Display info
echo "Here you go. This Verber's info...
IP: ${SITEIP}
Namespace: ${SITENAME}
Primary TLD: ${SITETLD}
Primary URI: ${SITENAME}.verb.${SITETLD}
Host: ${SITEHOST}
Timezone: ${SITETIMECITY}, ${SITETIMEREGION}

Email
Email URI: ${SITENAME}.verb.${SITEEMAILTLD}
Status: ${SITEMAILSTATUS}
Snail: ${SITESNAIL}
RC path: ${SITERCPATH}
PFA path: ${SITEPFAPATH}
"

