#!/bin/sh
# inkVerb config-serf, verb.ink

# This is a serf-config hybrid, which contains a list of Drupal distros and install URLs
## It is meant as a config file within the installdrupal serf, but running it will show a list of Drupal distros and the namespace to use for them

# Main Drupal distro
echo "
Drupal 8 Core - d8 (default if empty)
 https://www.drupal.org/project/drupal"
d8="drupal-8.3.2"

echo "
Drupal 7 Core - d7
 https://www.drupal.org/project/drupal/releases/7.51"
d7="drupal-7.54"

echo "
Commerce Kickstart - commerce_kickstart
 https://www.drupal.org/project/commerce_kickstart"
commerce_kickstart="commerce_kickstart-7.x-2.39-core"

echo "
Panopoly - panopoly
 https://www.drupal.org/project/panopoly"
panopoly="panopoly-7.x-1.40-core"

echo "
Open Atrium - openatrium
 https://www.drupal.org/project/openatrium"
openatrium="openatrium-7.x-2.68-core"

echo "
Opigno LMS - opigno_lms
 https://www.drupal.org/project/opigno_lms"
opigno_lms="opigno_lms-7.x-1.23-core"

echo "
Drupal Commons - commons
 https://www.drupal.org/project/commons"
commons="commons-7.x-3.39-core"

echo "
Zircon Profile - zircon_profile
 https://www.drupal.org/project/zircon_profile"
zircon_profile="zircon_profile-8.x-1.x-dev"

echo "
OpenChurch - openchurch
 https://www.drupal.org/project/openchurch"
openchurch="openchurch-7.x-2.2-core"

echo "
Lightning - lightning
 https://www.drupal.org/project/lightning"
lightning="lightning-8.x-1.06-core"

echo "
Open Outreach - openoutreach
 https://www.drupal.org/project/openoutreach"
openoutreach="openoutreach-7.x-1.33-core"

echo "
OpenPublic - openpublic
 https://www.drupal.org/project/openpublic"
openpublic="openpublic-7.x-1.10-core"

echo "
Drupalife Store - drupalife_store
 https://www.drupal.org/project/drupalife_store"
drupalife_store="drupalife_store-7.x-1.0-beta3-core"

echo "
OpenPublish - openpublish
 https://www.drupal.org/project/openpublish"
openpublish="openpublish-7.x-1.0-beta9-core"

echo "
Multipurpose Corporate Profile - multipurpose_corporate_profile
 https://www.drupal.org/project/multipurpose_corporate_profile"
multipurpose_corporate_profile="multipurpose_corporate_profile-7.x-1.9-core"

echo "
Bear - bear
 https://www.drupal.org/project/bear"
bear="bear-7.x-2.0-core"

echo "
Easy booking - easy_booking
 https://www.drupal.org/project/easy_booking"
easy_booking="easy_booking-7.x-2.4-core"

echo "
Conference Organizing Distribution - cod
 https://www.drupal.org/project/cod"
cod="cod-7.x-1.4-core"

echo "
Commerce Profile - commerce_profile
 https://www.drupal.org/project/commerce_profile"
commerce_profile="commerce_profile-7.x-1.7-core"

echo "
OpenFolio - openfolio
 https://www.drupal.org/project/openfolio"
openfolio="openfolio-7.x-1.3-core"

echo "
Restaurant - restaurant
 https://www.drupal.org/project/restaurant"
restaurant="restaurant-7.x-1.13-core"

echo "
Corporate profile - corporate_profile
 https://www.drupal.org/project/corporate_profile"
DRUPALCRPFL="corporate_profile-7.x-1.2-core"

echo "
OpenAid - openaid
 https://www.drupal.org/project/openaid"
DRUPALOAD="openaid-7.x-2.8-core"

echo "
Brainstorm profile - brainstorm_profile
 https://www.drupal.org/project/brainstorm_profile"
brainstorm_profile="brainstorm_profile-8.x-1.0-beta1-core"

echo "
Open Social - social
 https://www.drupal.org/project/social"
social="social-8.x-1.0-beta2-core"

echo "
farmOS - farm
 https://www.drupal.org/project/farm"
farm="farm-7.x-1.0-beta12-core"

echo "
BigVideo Installation Profile - bigvideo_profile
 https://www.drupal.org/project/bigvideo_profile"
bigvideo_profile="bigvideo_profile-7.x-1.3-core"

echo "
ERPAL for Service Providers - erpal
 https://www.drupal.org/project/erpal"
erpal="erpal-7.x-2.3-core"

echo "
ERPAL Platform - Flexible business applications - erpal_platform
 https://www.drupal.org/project/erpal_platform"
erpal_platform="erpal_platform-7.x-3.0-beta3-core"

echo "
OpenideaL - idea management system - idea
 https://www.drupal.org/project/idea"
idea="idea-7.x-2.8-core"

echo "
Thunder - thunder
 https://www.drupal.org/project/thunder"
thunder="thunder-8.x-1.0-rc1-core"

echo "
Classified advertising - classified_advertising
 https://www.drupal.org/project/classified_advertising"
classified_advertising="classified_advertising-7.x-1.x-dev-core"

echo "
Recruiter - recruiter
 https://www.drupal.org/project/recruiter"
recruiter="recruiter-7.x-1.10-core"

echo "
DruStack (Drupal 8) - drustack
 https://www.drupal.org/project/drustack"
drustack="drustack-8.x-1.6"

echo "
DruStack (Drupal 7) - drustack7
 https://www.drupal.org/project/drustack-7"
drustack7="drustack-7.x-50.4"

echo "
Sportsleague - sportsleague
 https://www.drupal.org/project/sportsleague"
sportsleague="sportsleague-8.x-1.1"

echo "
Responsive blog theme installation profile - responsive_blog_theme_installation_profile
 https://www.drupal.org/project/responsive_blog_theme_installation_profile"
responsive_blog_theme_installation_profile="responsive_blog_theme_installation_profile-7.x-1.1-core"

echo "
Browse an overview of Drupal distros here: https://www.drupal.org/project/project_distribution
"

