#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This displays the inkDNS DNS zone file for a specific domain on this Verber
## inkDNS is the inkVerb method of handling DNS zone records for domains hosted on its server

# How to use:
## ./showinkdns [domain.tld]


DOMAIN=$1

echo "Zone file:"
cat /opt/verb/conf/inkdns/zones/db.${DOMAIN}
echo "#######"
echo "Inverse lookup file:"
cat /opt/verb/conf/inkdns/zones/nv.${DOMAIN}
