#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This displays the inkDNS DNS zone file for a specific domain on this Verber
## inkDNS is the inkVerb method of handling DNS zone records for domains hosted on its server

# How to use:
## ./showinkdns [domain.tld]


DOMAIN=$1

cat /var/local/verb/configs/inkdns/zones/${DOMAIN}.db

