#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This displays the Inker information that this Verber is connected to.
## This could be useful to retrieve names for setting up this Verber as a Client to the CA Inker

# How to use:
## ./showinker


# Check the config
if [ ! -f /opt/verb/conf/inknet/inker.client.cnf ]; then
echo "This is not yet connected to an Inker via inkNet."
exit 0
fi

# Include the config
. /opt/verb/conf/inknet/inker.client.cnf

# Display info
echo "Here you go. This Verber's Inker info...
IP: ${CAVERBERIP}
Name: ${CAVERBERNAME}
URI: ${CAVERBERURI}
"

