#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This uninstalls the inkSplat Dovecot utility, moving marked spapm to the Junk folder and learning spam

# How to use:
## ./uninstallinksplat



# Check status
. /opt/verb/conf/sitemailpath
if [ ${INKSPLAT} != "INSTALLED" ]; then
  echo "inkSplat not installed. Doing nothing."
exit 0;fi

# Install Sieve & the Pigeonhole package (on Debian it is: managesieved, https://wiki2.dovecot.org/Pigeonhole/Installation)
apt remove dovecot-sieve dovecot-managesieved -y
apt purge dovecot-sieve dovecot-managesieved -y

# Setup the plugins and their files
rm -rf /etc/dovecot/sieve
rm -rf /usr/lib/dovecot/sieve
rm -f /etc/dovecot/inksplat.conf
sed -i '/# inkSplat utility set/d' /etc/dovecot/dovecot.conf
sed -i '/!include_try inksplat.conf/d' /etc/dovecot/dovecot.conf

# Restart
systemctl restart dovecot

# Finished
sed -i "s/INKSPLAT=.*/INKSPLAT=\"NOT_INSTALLED\"/" /opt/verb/conf/sitemailpath
echo "inkSplat email tagging & filtering for Dovecot uninstalled."
