#!/bin/sh
#inkVerbSerf! verb.ink

# This uninstalls the inkSplat Dovecot utility, moving marked spapm to the Junk folder and learning spam

# How to use:
## ./uninstallinksplat



# Check status
. /opt/verb/conf/sitemailpath
if [ ${INKSPLAT} != "INSTALLED" ]; then
  /bin/echo "inkSplat not installed. Doing nothing."
exit 0;fi

# Install Sieve & the Pigeonhole package (on Debian it is: managesieved, https://wiki2.dovecot.org/Pigeonhole/Installation)
/usr/bin/apt-get remove dovecot-sieve dovecot-managesieved -y
/usr/bin/apt-get purge dovecot-sieve dovecot-managesieved -y

# Setup the plugins and their files
/bin/rm -rf /etc/dovecot/sieve
/bin/rm -rf /usr/lib/dovecot/sieve
/bin/rm -f /etc/dovecot/inksplat.conf
/bin/sed -i '/# inkSplat utility set/d' /etc/dovecot/dovecot.conf
/bin/sed -i '/!include_try inksplat.conf/d' /etc/dovecot/dovecot.conf

# Restart
/bin/systemctl restart dovecot

# Finished
/bin/sed -i "s/INKSPLAT=.*/INKSPLAT=\"NOT_INSTALLED\"/" /opt/verb/conf/sitemailpath
/bin/echo "inkSplat email tagging & filtering for Dovecot uninstalled."
