#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This removes the Roundcube backup generated when updating Roundcube
# Prereq: Roundcube was updated via updaterc and is functioning properly

# How to use:
## ./updatercrmvbak


rm -rf /var/www/email/roundcube.vbak

echo "
Roudcube update backup removed.
"

