#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and updates the Verber™ core files, including serfs and inklists
## This also runs scripts that make other changes that may affect the Verber

# How to use:
## ./updateverber


# Download the latest checked version from GitHub
cd /var/local/verb/
git clone https://github.com/inkverb/verb-update

# Run the update script
chmod +x /var/local/verb/verb-update/update
/var/local/verb/verb-update/update

# Remove the entire updater
rm -rf /var/local/verb/verb-update

