#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This removes the Postfix Admin backup generated when updating Postfix Admin
# Prereq: Postfix Admin was updated via updaterc and is functioning properly

# How to use:
## ./updatepfarmvbak


rm -rf /var/www/email/postfixadmin.vbak

echo "
Postfix Admin update backup removed.
"

