#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This copies all original verb folders to www/html if they don't exist
## This is used by killvapp and others
## This is used by make-verber
## This does not change ownership of folders to www-data, which must be done separately on a production server.

# How to use:
## ./updatehtmlverbs


# Include the config
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Make the commute to where we will work
cd /var/www/html

# Remove broken links
find -L . -name . -o -type d -prune -o -type l -exec rm {} +

# Initial sites
rm -rf 0sitedefaultInProgress
cp -r /opt/verb/conf/lab/html/0sitedefaultInProgress .
chmod -R 750 0sitedefaultInProgress
rm -rf vsslsitedefault
cp -r 0sitedefaultInProgress vsslsitedefault
rm -rf 0ne
mkdir 0ne
echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/0ne/index.php
chmod -R 750 0ne

# Block web folder listing
echo "Options -Indexes" >> /var/www/html/.htaccess
echo "Options -Indexes" >> /var/www/html/0ne/.htaccess
echo "Options -Indexes" >> /var/www/html/0sitedefaultInProgress/.htaccess

# Verb sites
if [ ! -e ink ]; then cp -r 0sitedefaultInProgress ink; fi
if [ ! -e email ]; then cp -r 0ne email; fi
if [ ! -e city ]; then cp -r 0ne city; fi
if [ ! -e city.center ]; then cp -r 0ne city.center; fi
if [ ! -e city.console ]; then cp -r 0ne city.console; fi
if [ ! -e city.ctr ]; then mkdir -p city.ctr && echo "<?php header(\"Location: http://center.${cityURI}\"); die(); ?>" > /var/www/html/city.ctr/index.php; fi
if [ ! -e city.cnl ]; then mkdir -p city.cnl && echo "<?php header(\"Location: http://console.${cityURI}\"); die(); ?>" > /var/www/html/city.cnl/index.php; fi
if [ ! -e one ]; then cp -r 0ne one
echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/one/index-one.php
echo "<?php header(\"Location: http://newonesub.${oneURI}\"); die(); ?>" > /var/www/html/one/index-newonesub.php
fi
if [ ! -e ink.ask ]; then cp -r 0ne ink.ask; fi
if [ ! -e ink.bb ]; then cp -r 0ne ink.bb; fi
if [ ! -e ink.blog ]; then cp -r 0ne ink.blog; fi
if [ ! -e ink.code ]; then cp -r 0ne ink.code; fi
if [ ! -e ink.home ]; then cp -r 0ne ink.home; fi
if [ ! -e ink.pen ]; then cp -r 0ne ink.pen; fi
if [ ! -e ink.shop ]; then cp -r 0ne ink.shop; fi
if [ ! -e ink.sn ]; then cp -r 0ne ink.sn; fi
if [ ! -e ink.wiki ]; then cp -r 0ne ink.wiki; fi
if [ ! -e blue ]; then cp -r 0ne blue
echo "<?php header(\"Location: http://caldav.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-caldav.php
echo "<?php header(\"Location: http://carddav.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-carddav.php
echo "<?php header(\"Location: http://chat.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-chat.php
echo "<?php header(\"Location: http://collabora.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-collabora.php
echo "<?php header(\"Location: http://dav.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-dav.php
echo "<?php header(\"Location: http://nc.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-nc.php
echo "<?php header(\"Location: http://owncloud.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-owncloud.php
echo "<?php header(\"Location: http://seafile.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-seafile.php
echo "<?php header(\"Location: http://webdav.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-webdav.php
echo "<?php header(\"Location: http://xmpp.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-xmpp.php
echo "<?php header(\"Location: http://${blueURI}\"); die(); ?>" > /var/www/html/blue/index-blue.php
fi
if [ ! -e blue.ccaldavalda ]; then cp -r 0ne blue.caldav; fi
if [ ! -e blue.carddav ]; then cp -r 0ne blue.carddav; fi
if [ ! -e blue.chat ]; then cp -r 0ne blue.chat; fi
if [ ! -e blue.collabora ]; then cp -r 0ne blue.collabora; fi
if [ ! -e blue.dav ]; then cp -r 0ne blue.dav; fi
if [ ! -e blue.nc ]; then cp -r 0ne blue.nc; fi
if [ ! -e blue.owncloud ]; then cp -r 0ne blue.owncloud; fi
if [ ! -e blue.seafile ]; then cp -r 0ne blue.seafile; fi
if [ ! -e blue.webdav ]; then cp -r 0ne blue.webdav; fi
if [ ! -e blue.xmpp ]; then cp -r 0ne blue.xmpp; fi
if [ ! -e vip ]; then cp -r 0ne vip
echo "<?php header(\"Location: http://hrm.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-vip.php
echo "<?php header(\"Location: http://newvipsub.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-newvipsub.php
echo "<?php header(\"Location: http://cgi.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-cgi.php
echo "<?php header(\"Location: http://ftp.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-ftp.php
echo "<?php header(\"Location: http://files.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-files.php
echo "<?php header(\"Location: http://fossil.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-fossil.php
echo "<?php header(\"Location: http://ldap.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-ldap.php
echo "<?php header(\"Location: http://net2ftp.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-net2ftp.php
echo "<?php header(\"Location: http://repo.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-repo.php
echo "<?php header(\"Location: http://sql.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-sql.php
fi
if [ ! -e vip.cgi ]; then cp -r 0ne vip.cgi; fi
if [ ! -e vip.ftp ]; then cp -r 0ne vip.ftp; fi
if [ ! -e vip.files ]; then cp -r 0ne vip.files; fi
if [ ! -e vip.fossil ]; then cp -r 0ne vip.fossil; fi
if [ ! -e vip.ldap ]; then cp -r 0ne vip.ldap; fi
if [ ! -e vip.net2ftp ]; then cp -r 0ne vip.net2ftp; fi
if [ ! -e vip.repo ]; then cp -r 0ne vip.repo; fi
if [ ! -e vip.sql ]; then cp -r 0ne vip.sql; fi
if [ ! -e kiwi ]; then cp -r 0ne kiwi
echo "<?php header(\"Location: http://ampache.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-ampache.php
echo "<?php header(\"Location: http://art.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-art.php
echo "<?php header(\"Location: http://ejabberd.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-ejabberd.php
echo "<?php header(\"Location: http://gallery.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-gallery.php
echo "<?php header(\"Location: http://media.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-media.php
echo "<?php header(\"Location: http://podcast.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-podcast.php
echo "<?php header(\"Location: http://prosody.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-prosody.php
echo "<?php header(\"Location: http://studio.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-studio.php
echo "<?php header(\"Location: http://voip.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-voip.php
echo "<?php header(\"Location: http://webrtc.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-webrtc.php
echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/kiwi/index-kiwi.php
fi
if [ ! -e kiwi.ampache ]; then cp -r 0ne kiwi.ampache; fi
if [ ! -e kiwi.art ]; then cp -r 0ne kiwi.art; fi
if [ ! -e kiwi.ejabberd ]; then cp -r 0ne kiwi.ejabberd; fi
if [ ! -e kiwi.gallery ]; then cp -r 0ne kiwi.gallery; fi
if [ ! -e kiwi.media ]; then cp -r 0ne kiwi.media; fi
if [ ! -e kiwi.podcast ]; then cp -r 0ne kiwi.podcast; fi
if [ ! -e kiwi.prosody ]; then cp -r 0ne kiwi.prosody; fi
if [ ! -e kiwi.studio ]; then cp -r 0ne kiwi.studio; fi
if [ ! -e kiwi.voip ]; then cp -r 0ne kiwi.voip; fi
if [ ! -e kiwi.webrtc ]; then cp -r 0ne kiwi.webrtc; fi
if [ ! -e cash ]; then cp -r 0ne cash
echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/cash/index-cash.php
fi
if [ ! -e pink ]; then cp -r 0ne pink
echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/pink/index-pink.php
fi
if [ ! -e red ]; then cp -r 0ne red
echo "<?php header(\"Location: http://act.${redURI}\"); die(); ?>" > /var/www/html/red/index-act.php
echo "<?php header(\"Location: http://crm.${redURI}\"); die(); ?>" > /var/www/html/red/index-crm.php
echo "<?php header(\"Location: http://erp.${redURI}\"); die(); ?>" > /var/www/html/red/index-erp.php
echo "<?php header(\"Location: http://hrm.${redURI}\"); die(); ?>" > /var/www/html/red/index-hrm.php
echo "<?php header(\"Location: http://odoo.${redURI}\"); die(); ?>" > /var/www/html/red/index-odoo.php
echo "<?php header(\"Location: http://scm.${redURI}\"); die(); ?>" > /var/www/html/red/index-scm.php
echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/red/index-red.php
fi
if [ ! -e red.act ]; then cp -r 0ne red.act; fi
if [ ! -e red.crm ]; then cp -r 0ne red.crm; fi
if [ ! -e red.erp ]; then cp -r 0ne red.erp; fi
if [ ! -e red.hrm ]; then cp -r 0ne red.hrm; fi
if [ ! -e red.odoo ]; then cp -r 0ne red.odoo; fi
if [ ! -e red.scm ]; then cp -r 0ne red.scm; fi
if [ ! -e rocks ]; then cp -r 0ne rocks
echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/rocks/index-rocks.php
fi

# Verb point defaults
if [ ! -e email.email ]; then
mkdir email.email
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${emailURI}\"); die(); ?>" > /var/www/html/email.email/index.php
fi
if [ ! -e city.city ]; then
mkdir city.city
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${cityURI}\"); die(); ?>" > /var/www/html/city.city/index.php
fi
if [ ! -e one.one ]; then
mkdir one.one
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${oneURI}\"); die(); ?>" > /var/www/html/one.one/index.php
fi
if [ ! -e ink.ink ]; then
mkdir ink.ink
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/ink.ink/index.php
fi
if [ ! -e blue.blue ]; then
mkdir blue.blue
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${blueURI}\"); die(); ?>" > /var/www/html/blue.blue/index.php
fi
if [ ! -e vip.vip ]; then
mkdir vip.vip
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${vipURI}\"); die(); ?>" > /var/www/html/vip.vip/index.php
fi
if [ ! -e kiwi.kiwi ]; then
mkdir kiwi.kiwi
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi.kiwi/index.php
fi
if [ ! -e cash.cash ]; then
mkdir cash.cash
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${cashURI}\"); die(); ?>" > /var/www/html/cash.cash/index.php
fi
if [ ! -e pink.pink ]; then
mkdir pink.pink
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${pinkURI}\"); die(); ?>" > /var/www/html/pink.pink/index.php
fi
if [ ! -e red.red ]; then
mkdir red.red
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${redURI}\"); die(); ?>" > /var/www/html/red.red/index.php
fi
if [ ! -e rocks.rocks ]; then
mkdir rocks.rocks
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${rocksURI}\"); die(); ?>" > /var/www/html/rocks.rocks/index.php
fi

# Serve URI
rm -rf /var/www/html/${SITESERVE}.serve
mkdir -p ${SITESERVE}.serve/${SERVEDIR}
echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${nameURI}\"); die(); ?>" > /var/www/html/${SITETLD}.serve/index.php

# Own
chown -R www-data:www-data /var/www/html
chmod -R 750 email*
chmod -R 750 city*
chmod -R 750 one*
chmod -R 750 ink*
chmod -R 750 blue*
chmod -R 750 vip*
chmod -R 750 kiwi*
chmod -R 750 cash*
chmod -R 750 pink*
chmod -R 750 red*
chmod -R 750 rocks*

# Finish
echo "Done. Except for any installed apps, Verber html folders have been set to original setup state."
