#!/bin/sh
#inkVerbSerf! verb.ink

# This copies all original verb folders to www/html if they don't exist
## This is used by killvapp and others
## This is used by make-verber
## This does not change ownership of folders to www-data, which must be done separately on a production server.

# How to use:
## ./updatehtmlverbs


# Include the config
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Make the commute to where we will work
cd /var/www/html

# Remove broken links
find -L . -name . -o -type d -prune -o -type l -exec rm {} +

# Initial sites
/bin/rm -rf 0sitedefaultInProgress
/bin/cp -r /opt/verb/conf/lab/html/0sitedefaultInProgress .
/bin/chmod -R 750 0sitedefaultInProgress
/bin/rm -rf vsslsitedefault
/bin/cp -r 0sitedefaultInProgress vsslsitedefault
/bin/rm -rf 0ne
/bin/mkdir 0ne
/bin/echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/0ne/index.php
/bin/chmod -R 750 0ne

# Block web folder listing
/bin/echo "Options -Indexes" >> /var/www/html/.htaccess
/bin/echo "Options -Indexes" >> /var/www/html/0ne/.htaccess
/bin/echo "Options -Indexes" >> /var/www/html/0sitedefaultInProgress/.htaccess

# Verb sites
if [ ! -e ink ]; then cp -r 0sitedefaultInProgress ink; fi
if [ ! -e email ]; then cp -r 0ne email; fi
if [ ! -e one ]; then cp -r 0ne one
/bin/echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/one/index-one.php
/bin/echo "<?php header(\"Location: http://newonesub.${oneURI}\"); die(); ?>" > /var/www/html/one/index-newonesub.php
fi
if [ ! -e ink.ask ]; then cp -r 0ne ink.ask; fi
if [ ! -e ink.bb ]; then cp -r 0ne ink.bb; fi
if [ ! -e ink.blog ]; then cp -r 0ne ink.blog; fi
if [ ! -e ink.code ]; then cp -r 0ne ink.code; fi
if [ ! -e ink.home ]; then cp -r 0ne ink.home; fi
if [ ! -e ink.pen ]; then cp -r 0ne ink.pen; fi
if [ ! -e ink.shop ]; then cp -r 0ne ink.shop; fi
if [ ! -e ink.sn ]; then cp -r 0ne ink.sn; fi
if [ ! -e ink.wiki ]; then cp -r 0ne ink.wiki; fi
if [ ! -e blue ]; then cp -r 0ne blue
/bin/echo "<?php header(\"Location: http://caldav.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-caldav.php
/bin/echo "<?php header(\"Location: http://carddav.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-carddav.php
/bin/echo "<?php header(\"Location: http://chat.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-chat.php
/bin/echo "<?php header(\"Location: http://collabora.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-collabora.php
/bin/echo "<?php header(\"Location: http://dav.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-dav.php
/bin/echo "<?php header(\"Location: http://nc.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-nc.php
/bin/echo "<?php header(\"Location: http://owncloud.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-owncloud.php
/bin/echo "<?php header(\"Location: http://seafile.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-seafile.php
/bin/echo "<?php header(\"Location: http://webdav.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-webdav.php
/bin/echo "<?php header(\"Location: http://xmpp.${blueURI}\"); die(); ?>" > /var/www/html/blue/index-xmpp.php
/bin/echo "<?php header(\"Location: http://${blueURI}\"); die(); ?>" > /var/www/html/blue/index-blue.php
fi
if [ ! -e blue.ccaldavalda ]; then cp -r 0ne blue.caldav; fi
if [ ! -e blue.carddav ]; then cp -r 0ne blue.carddav; fi
if [ ! -e blue.chat ]; then cp -r 0ne blue.chat; fi
if [ ! -e blue.collabora ]; then cp -r 0ne blue.collabora; fi
if [ ! -e blue.dav ]; then cp -r 0ne blue.dav; fi
if [ ! -e blue.nc ]; then cp -r 0ne blue.nc; fi
if [ ! -e blue.owncloud ]; then cp -r 0ne blue.owncloud; fi
if [ ! -e blue.seafile ]; then cp -r 0ne blue.seafile; fi
if [ ! -e blue.webdav ]; then cp -r 0ne blue.webdav; fi
if [ ! -e blue.xmpp ]; then cp -r 0ne blue.xmpp; fi
if [ ! -e vip ]; then cp -r 0ne vip
/bin/echo "<?php header(\"Location: http://hrm.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-vip.php
/bin/echo "<?php header(\"Location: http://newvipsub.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-newvipsub.php
/bin/echo "<?php header(\"Location: http://cgi.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-cgi.php
/bin/echo "<?php header(\"Location: http://ftp.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-ftp.php
/bin/echo "<?php header(\"Location: http://files.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-files.php
/bin/echo "<?php header(\"Location: http://fossil.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-fossil.php
/bin/echo "<?php header(\"Location: http://ldap.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-ldap.php
/bin/echo "<?php header(\"Location: http://net2ftp.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-net2ftp.php
/bin/echo "<?php header(\"Location: http://repo.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-repo.php
/bin/echo "<?php header(\"Location: http://sql.${vipURI}\"); die(); ?>" > /var/www/html/vip/index-sql.php
fi
if [ ! -e vip.cgi ]; then cp -r 0ne vip.cgi; fi
if [ ! -e vip.ftp ]; then cp -r 0ne vip.ftp; fi
if [ ! -e vip.files ]; then cp -r 0ne vip.files; fi
if [ ! -e vip.fossil ]; then cp -r 0ne vip.fossil; fi
if [ ! -e vip.ldap ]; then cp -r 0ne vip.ldap; fi
if [ ! -e vip.net2ftp ]; then cp -r 0ne vip.net2ftp; fi
if [ ! -e vip.repo ]; then cp -r 0ne vip.repo; fi
if [ ! -e vip.sql ]; then cp -r 0ne vip.sql; fi
if [ ! -e kiwi ]; then cp -r 0ne kiwi
/bin/echo "<?php header(\"Location: http://ampache.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-ampache.php
/bin/echo "<?php header(\"Location: http://art.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-art.php
/bin/echo "<?php header(\"Location: http://ejabberd.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-ejabberd.php
/bin/echo "<?php header(\"Location: http://gallery.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-gallery.php
/bin/echo "<?php header(\"Location: http://media.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-media.php
/bin/echo "<?php header(\"Location: http://podcast.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-podcast.php
/bin/echo "<?php header(\"Location: http://prosody.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-prosody.php
/bin/echo "<?php header(\"Location: http://studio.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-studio.php
/bin/echo "<?php header(\"Location: http://voip.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-voip.php
/bin/echo "<?php header(\"Location: http://webrtc.${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi/index-webrtc.php
/bin/echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/kiwi/index-kiwi.php
fi
if [ ! -e kiwi.ampache ]; then cp -r 0ne kiwi.ampache; fi
if [ ! -e kiwi.art ]; then cp -r 0ne kiwi.art; fi
if [ ! -e kiwi.ejabberd ]; then cp -r 0ne kiwi.ejabberd; fi
if [ ! -e kiwi.gallery ]; then cp -r 0ne kiwi.gallery; fi
if [ ! -e kiwi.media ]; then cp -r 0ne kiwi.media; fi
if [ ! -e kiwi.podcast ]; then cp -r 0ne kiwi.podcast; fi
if [ ! -e kiwi.prosody ]; then cp -r 0ne kiwi.prosody; fi
if [ ! -e kiwi.studio ]; then cp -r 0ne kiwi.studio; fi
if [ ! -e kiwi.voip ]; then cp -r 0ne kiwi.voip; fi
if [ ! -e kiwi.webrtc ]; then cp -r 0ne kiwi.webrtc; fi
if [ ! -e red ]; then cp -r 0ne red
/bin/echo "<?php header(\"Location: http://act.${redURI}\"); die(); ?>" > /var/www/html/red/index-act.php
/bin/echo "<?php header(\"Location: http://crm.${redURI}\"); die(); ?>" > /var/www/html/red/index-crm.php
/bin/echo "<?php header(\"Location: http://erp.${redURI}\"); die(); ?>" > /var/www/html/red/index-erp.php
/bin/echo "<?php header(\"Location: http://hrm.${redURI}\"); die(); ?>" > /var/www/html/red/index-hrm.php
/bin/echo "<?php header(\"Location: http://odoo.${redURI}\"); die(); ?>" > /var/www/html/red/index-odoo.php
/bin/echo "<?php header(\"Location: http://owa.${redURI}\"); die(); ?>" > /var/www/html/red/index-owa.php
/bin/echo "<?php header(\"Location: http://scm.${redURI}\"); die(); ?>" > /var/www/html/red/index-scm.php
/bin/echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/red/index-red.php
fi
if [ ! -e red.act ]; then cp -r 0ne red.act; fi
if [ ! -e red.crm ]; then cp -r 0ne red.crm; fi
if [ ! -e red.erp ]; then cp -r 0ne red.erp; fi
if [ ! -e red.hrm ]; then cp -r 0ne red.hrm; fi
if [ ! -e red.odoo ]; then cp -r 0ne red.odoo; fi
if [ ! -e red.owa ]; then cp -r 0ne red.owa; fi
if [ ! -e red.scm ]; then cp -r 0ne red.scm; fi


# Verb point defaults
if [ ! -e email.email ]; then
/bin/mkdir email.email
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${emailURI}\"); die(); ?>" > /var/www/html/email.email/index.php
fi
if [ ! -e one.one ]; then
/bin/mkdir one.one
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${oneURI}\"); die(); ?>" > /var/www/html/one.one/index.php
fi
if [ ! -e ink.ink ]; then
/bin/mkdir ink.ink
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${inkURI}\"); die(); ?>" > /var/www/html/ink.ink/index.php
fi
if [ ! -e blue.blue ]; then
/bin/mkdir blue.blue
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${blueURI}\"); die(); ?>" > /var/www/html/blue.blue/index.php
fi
if [ ! -e vip.vip ]; then
/bin/mkdir vip.vip
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${vipURI}\"); die(); ?>" > /var/www/html/vip.vip/index.php
fi
if [ ! -e kiwi.kiwi ]; then
/bin/mkdir kiwi.kiwi
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${kiwiURI}\"); die(); ?>" > /var/www/html/kiwi.kiwi/index.php
fi
if [ ! -e red.red ]; then
/bin/mkdir red.red
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${redURI}\"); die(); ?>" > /var/www/html/red.red/index.php
fi

# Serve URI
/bin/rm -rf /var/www/html/${SITESERVE}.serve
/bin/mkdir -p /var/www/html/${SITESERVE}.serve/${SERVEDIR}
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${nameURI}\"); die(); ?>" > /var/www/html/${SITESERVE}.serve/index.php

# Own
/bin/chown -R www-data:www-data /var/www/html
/bin/chmod -R 750 email*
/bin/chmod -R 750 one*
/bin/chmod -R 750 ink*
/bin/chmod -R 750 blue*
/bin/chmod -R 750 vip*
/bin/chmod -R 750 kiwi*
/bin/chmod -R 750 red*

# Finish
/bin/echo "Done. Except for any installed apps, Verber html folders have been set to original setup state."
