#!/bin/sh
#inkVerbSerf! verb.ink

# This runs the basic updater for apt and includes bugfixes
## Dialogs menues will still appear, so this should be run while being monitored

# How to use:
## ./updateapt


apt update
apt upgrade -y
dpkg --configure -a
apt autoremove -y
