#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This updates an existing Roundcube installation once it has been updated in the inkVerb repo
## After, ensure that Roundcube works correctly, then run updatercrmvbak

# How to use:
## ./updaterc


# Include the config file
. /var/local/verb/configs/sitenameip

# Download and unzip
cd /var/www
## Remove any existing roundcube folder
if [ -d roundcube ]; then
rm -rf roundcube ; fi
## Get the update
/var/local/verb/serfs/inkget roundcube.current
unzip roundcube.current.zip
rm -f roundcube.current.zip
if [ -d /var/www/email/roundcube.vbak ]; then
rm -rf /var/www/email/roundcube.vbak; fi
cp -R /var/www/email/roundcube /var/www/email/roundcube.vbak
cd roundcube
./bin/installto.sh /var/www/email/roundcube
## Disable the installer
sed -i "s/\$config\['enable_installer'\].*/\$config\['enable_installer'\] = false;/g" /var/www/email/roundcube/config/config.inc.php
## Remove the updater
cd /var/www
rm -rf /var/www/roundcube

# Forwarding plugin
cp /var/www/email/roundcube/plugins/forward/config.inc.php.dist /var/www/email/roundcube/plugins/forward/config.inc.php
sed -i "s/\$rcmail_config\['forward_sql_dsn'\].*/\$rcmail_config\['forward_sql_dsn'\] = 'mysql:\/\/mail:mailpass${SITEMAILPASSAPG}@localhost\/mail';/g" /var/www/email/roundcube/plugins/forward/config.inc.php

# Copy the branding files
cp /var/local/verb/configs/conflab/email/roundcube/roundcubepics/skins/larry/images/verbink_logo.png /var/www/email/roundcube/skins/larry/images/
cp /var/local/verb/configs/conflab/email/roundcube/roundcubepics/verbink_logo.png /var/www/email/roundcube/
cp /var/local/verb/configs/conflab/email/roundcube/roundcubepics/skins/larry/images/watermark.jpg /var/www/email/roundcube/skins/larry/images/
cp /var/local/verb/configs/conflab/email/roundcube/roundcubepics/skins/larry/images/favicon.ico /var/www/email/roundcube/skins/larry/images/
cp /var/local/verb/configs/conflab/email/roundcube/roundcubepics/favicon.ico /var/www/email/roundcube/

# Notify status
echo "
RoudCube update complete.

If all works well, you may delete the backup wtih updatercrmvbak before updating again.

Now updating plugins with Composer. Hold your breath and think good thoughts...
"

# Composer Plugins update
cd /var/www/email/roundcube
php composer.phar update -n

# Finish
echo "
All done. :-)
"

