#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This turns off a tld of the verb sites, such as verb.red, but not the other verb.tld sites, all are on before running this
## This removes the symlink in apache2/sites-enabled

# How to use:
## ./verboff [tld]

# Eg:
## ./verboff kiwi


SITEOFF=$1

rm -f /etc/apache2/sites-enabled/*.verb.${SITEOFF}.conf
sed -i "s/VERB${SITEOFF}=.*/VERB${SITEOFF}=false/g" /var/local/verb/configs/sitetldstatus
service apache2 reload

