#!/bin/sh
#inkVerbKnight! verb.ink
#set -e

# This displays the current Verber version number

# How to use:
## ./inkver

. /opt/verb/conf/inklists/verberverno
. /opt/verb/conf/sitenameip
echo "${SITEUPDATEREPO} ${VERNO}"

