#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This changes the Tesseract theme's "Follow Us On" social icon Title prefix to what you set. It can be left null for simple social media titles
## This only applies to the home.your-name.ink WordPress installation

# How to use:
## ./wpfixtessfollowhome [replaced contend]


sed -i "s/Follow Us on/${CONTENT}/g" /var/www/html/ink.home/wp-content/themes/TESSERACT/inc/customizer-frontend-functions.php
sed -i "s/Follow Us on/${CONTENT}/g" /var/www/html/ink.home/wp-content/themes/TESSERACT/languages/tesseract.pot
