#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This changes the Tesseract theme's "Follow Us On" social icon Title prefix to what you set. It can be left null for simple social media titles
## This only applies to a specific domain

# How to use:
## ./wpfixtessfollow [wordpress domain] [replaced contend]


WPSITE=$1
CONTENT=$2

sed -i "s/Follow Us on/${CONTENT}/g" /var/www/html/${WPSITE}/wp-content/themes/TESSERACT/inc/customizer-frontend-functions.php
sed -i "s/Follow Us on/${CONTENT}/g" /var/www/html/${WPSITE}/wp-content/themes/TESSERACT/languages/tesseract.pot

