#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This sets up a WordPress vapp for multisite
## Specifically, this adds the multisite declarations in wp-config.php necessary for multisite to function
## Prerequesite: wpmuseton, install the "Network" from the dashboard
## This must also be run with wpmuhtaccess

# How to use:
## ./wpmusetconfig [domain.tld] [optional - "dir"]

# Eg:
## ./wpmusetconfig inkisaverb.com                  # will install to inkisaverb.com as the base, using subdomains of inkisaverb.com
## ./wpmusetconfig mysubsite.inkisaverb.com        # will install to mysubsite.inkisaverb.com as the base, using subdomains of mysubsite.inkisaverb.com
## ./wpmusetconfig inkisaverb.com dir              # will install to inkisaverb.com as the base, using directories of inkisaverb.com
## ./wpmusetconfig mysubsite.inkisaverb.com dir    # will install to mysubsite.inkisaverb.com as the base, using directories of mysubsite.inkisaverb.com


WPDOMAIN=$1
INSTTYPE=$2

# Set the default setting
if [ "${INSTTYPE}" != "dir" ]; then
INSTTYPE="sub"; fi

# Check the configs are ready
if grep -Fq "define( 'WP_ALLOW_MULTISITE', true );" /var/www/html/${WPDOMAIN}/wp-config.php; then
echo "Proceeding..."; else
echo "Multisite must be allowed first. Run: wpmuseton"
exit 8; fi

# Check if already set
if grep -Fq "define('MULTISITE', true);" /var/www/html/${WPDOMAIN}/wp-config.php; then
echo "Multisite is already set. To change or set it again, first unset it with: wpmuunsetconfig"
exit 8; fi

# We've got to fenagle this around in order to make the code readable while also doing this properly
## Cleanup the initial install
/opt/verb/serfs/wpmusetoff ${WPDOMAIN}
## Make a content file to work with
cp /var/www/html/${WPDOMAIN}/wp-config.php /var/www/html/${WPDOMAIN}/wp-config.php.Vmu
## Sanitize the content file
sed -i "/<?php/d" /var/www/html/${WPDOMAIN}/wp-config.php.Vmu
## Start stacking the new file
echo "<?php
/* Multisite via inkVerb */
define( 'WP_ALLOW_MULTISITE', true );" > /var/www/html/${WPDOMAIN}/wp-config.php.NEW

## Add the settings

### Subdomain install
if [ "${INSTTYPE}" = "sub" ]; then
echo "Using subdomains for the WP Multisite..."
echo "
/* Multisite Settings via inkVerb */
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true);
define('DOMAIN_CURRENT_SITE', '${WPDOMAIN}');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
/* Multisite inkVerb End */" >> /var/www/html/${WPDOMAIN}/wp-config.php.NEW
fi

### Directory install
if [ "${INSTTYPE}" = "dir" ]; then
echo "Using directories for the WP Multisite..."
echo "
/* Multisite Settings via inkVerb */
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
define('DOMAIN_CURRENT_SITE', '${WPDOMAIN}');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
/* Multisite inkVerb End */" >> /var/www/html/${WPDOMAIN}/wp-config.php.NEW
fi

## Add the original content
cat /var/www/html/${WPDOMAIN}/wp-config.php.Vmu >> /var/www/html/${WPDOMAIN}/wp-config.php.NEW
## Check that the universe is in working order
if [ ! -e "/var/www/html/${WPDOMAIN}/wp-config.php.Vmu" ]; then
echo "Something is very not right."
exit 6; fi
## Remove & replace the original
rm -f /var/www/html/${WPDOMAIN}/wp-config.php
mv /var/www/html/${WPDOMAIN}/wp-config.php.NEW /var/www/html/${WPDOMAIN}/wp-config.php
## Cleanup
rm -f /var/www/html/${WPDOMAIN}/wp-config.php.Vmu
## Finish
echo "http://${WPDOMAIN} now ready for WP Multisite. Log in again."
