#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This turns off a WordPress vapp from being able to use multisite
## Specifically, this adds the multisite settings in wp-config.php necessary to begin the installation from the WordPress dashboard

# How to use:
## ./wpmusetoff [domain.tld]

# Eg:
## ./wpmusetoff inkisaverb.com
## ./wpmusetoff mysubsite.inkisaverb.com


WPDOMAIN=$1

# Check if already set
if grep -Fq "define( 'WP_ALLOW_MULTISITE', true );" /var/www/html/${WPDOMAIN}/wp-config.php; then
echo "Proceeding..."; else
echo "Multisite isn't even set, dufis. Set it on with: wpmuseton"
exit 8; fi

# Delete the lines
sed -i "/* Multisite via inkVerb */d" /var/www/html/${WPDOMAIN}/wp-config.php
sed -i "/define( 'WP_ALLOW_MULTISITE', true );/d" /var/www/html/${WPDOMAIN}/wp-config.php

# Finish
echo "WP Multisite for http://${WPDOMAIN} is now disabled."

