#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This adds/updates the Ryuki child theme of Ryu to an existing WordPress installation

# How to use:
## ./wpthemeryuki [domain.tld or folder]


DOMAIN=$1


# Check if installed
if [ ! -d /var/www/html/${DOMAIN}/wp-content ]; then
 if [ ! -d /var/www/html/${DOMAIN} ]; then
 echo "${DOMAIN} is not even installed. That domain needs to be installed and have WordPress. Do those, then try again."
 exit 22
 else
 echo "${DOMAIN} is installed, but does not have WordPress. Install WordPress to that domain, then try again."
 exit 22
 fi
fi

# Do the Git clone
cd /var/www/html/${DOMAIN}/wp-content/themes
git clone https://github.com/cfinke/Ryuki.git

# Finish
echo "Ryuki theme installed and updated."

