#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This backs up all wordpress vapps into the vip folder

# How to use:
## ./wpvappbackupall


cd /var/www/vapps
for vapp in wp.*; do
/opt/verb/serfs/backup $vapp 123 -nl
done

