#!/bin/sh
## This is a config file for the status of inkVPN installations

INKVPNINSTALLED="NOT_YET"
INKVPNCOUNTR="US"
INKVPNPROVIN="CA"
INKVPNCITY="SanFrancisco"
INKVPNORG="inkVerb"
INKVPNCLIENTEMAIL="NOT_SET"
INKVPNOU="Internal-VPN"
INKVPNPORT="1194"
