#!/bin/sh
# inkVerb Verber™ version information config, verb.ink

# This contains IP addresses used by Odoo instances.
## This is useful for webmaster reference and required for automated install script calculations.


