#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This creates an IVapp spoof user, mainly to login to other machines with no password, based on settings, but does not add any credentials of the module
## Prerequisite: installivapp (a dragon in the donjon)

# How to use:
## ./ivappaddsailor [user name] [/path/to/ivapp/user/group-profile.conf]

## DEV:
## Add a section with this:
### Follow these instructions https://www.cyberciti.biz/open-source/command-line-hacks/linux-run-command-as-different-user/ or probably not these instructions https://stackoverflow.com/questions/40668512/how-to-switch-to-different-user-inside-a-shell-script-and-execute-some-command-w


# Check variables
## Entered
if [ -z $2 ]; then
echo "You must enter a username, and config profile like this:
./inknetaddivappuser [user name] [/path/to/ivapp/user/group-profile.conf]"
exit 55; fi
## Exists
if [ ! -f "$2" ]; then
echo "That settings file does not exist."
exit 22; fi

CONF=$2

# Include configs
. ${CONF}
. ${IVAPPCONFLOC}

# Check status
if [ -f "${STATUSFILE}" ]; then
. ${STATUSFILE}
 if [ "${IVAPPSTATUS}" != "INSTALLED" ]; then
echo "${MODULENAME} is not installed. Do that first."; exit 22
 fi
else
echo "${MODULENAME} is not installed. Do that first."; exit 22
fi

INPUTUSERNAME=$1
ADDIVAPPUSERNAME=$(echo $INPUTUSERNAME | cut -c1-18)

# Check and include the config
adduser ${ADDIVAPPUSERNAME} --gecos ",,," --disabled-password
## Add him to the IVapp group
usermod -a -G ${IVAPPUSERGROUP} ${ADDIVAPPUSERNAME}
## Move his home
usermod -m -d ${IVAPPBASE}/${IVAPPDIR}/${IVAPPGROUPDIR}/${ADDIVAPPUSERNAME} ${ADDIVAPPUSERNAME}
## Give him necessary permissions limits
echo "Setting permissions, this may take a moment..."
### Note: we add " > /dev/null 2>&1" because this may kick output errors that don't matter and filibuster other important messages.
/var/local/verb/donjon/ivappsetpermissions.sh ${CONF} ${ADDIVAPPUSERNAME}

# Finish
echo "The ${MODULENAME} user ${ADDIVAPPUSERNAME} has been added."

