#!/bin/sh
#inkVerbMaker! verb.ink
## THIS IS THE BIG ONE! THIS INSTALLS THE NAME AND SETS THE SERVER INTO PRODUCTION ##

# This initially sets the server to the specific namespace at verb.ink etc.
## The SSL email is for registering with Letsencrypt.
## Domains are added to the server after this
## This changes the SSH login port, to keep it the same use 22
## This creates a sudo user with login AND a MySQL superuser by the same name and password

# How to use:
## ./setupverb [host - should be namespace or FQDN tld, unless you want to be strange] [inkVerb namespace (purchased)] [FQDN tld, should be 'ink' except multiple servers for namespace] [server IP] [SSL email - used for Letsencrypt and the like] [php file upload limit] [php upload size in MB] [php timezone region] [php timezone city] [new port number for ssh/terminal login] [new "boss" sudo user] [boss user password]
# Simple how to use:
## ./setupverb [host] [namespace] [tld] [serverIP] [SSLemail] [php.file-limit] [php.up-size] [php.region] [php.city] [new-port] [new-boss] [boss-pass]

# Eg:
## ./setupverb ink johnny ink 56.22.108.77 johnny@emaildomain.com 100 1000 America Detroit 22 boss bosspassword
## ./setupverb johnny johnny ink 56.22.108.77 johnny@emaildomain.com 100 1000 America Detroit 867 boss bosspassword
## ./setupverb ikick johnny ink 56.22.108.77 johnny@emaildomain.com 100 1000 America Detroit 5290 boss bosspassword

## PHP timezone can't use third option of state or country such as America/Argentina/San_Juan or America/Indiana/Knox, only such as America/Chicago
## Get PHP timezone list at: http://php.net/manual/en/timezones.php


HNAME=$1
VNAME=$2
SERVERTLD=$3
SERVERIP=$4
SSLEMAIL=$5
PHPLIMIT=$6
PHPSIZE=$7
PHPREGION=$8
PHPCITY=$9
NEWPORT=${10}
NEWBOSS=${11}
NEWBOSSPASS=${12}
#GREATERTHANNINE=${10}

# Locale (incase a VPS deleted it after make-verber-preserver)
echo "LANG="en_US.UTF-8"
LANGUAGE="en_US:en"
LC_ALL="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
" > /etc/default/locale

# Re-do Snakeoil pair
make-ssl-cert generate-default-snakeoil --force-overwrite

# Re-do the Diffie-Helman Group security file
rm -f /etc/ssl/private/dhparams.pem
openssl dhparam -out /etc/ssl/private/dhparams.pem 2048
chmod 600 /etc/ssl/private/dhparams.pem

# inkVerb site configs
cp -R /var/local/verb/inst/configs /var/local/verb/configs
mv /var/local/verb/inst/mysqlrootpassword /var/local/verb/configs/
mv /var/local/verb/inst/mysqlboss.cnf /var/local/verb/configs/
mv /var/local/verb/configs/verbcrontab286 /var/local/verb/configs/verbcrontab
mv /var/local/verb/configs/sitenameip286 /var/local/verb/configs/sitenameip
mv /var/local/verb/configs/siteport286 /var/local/verb/configs/siteport
mv /var/local/verb/configs/siteinkget286 /var/local/verb/configs/siteinkget
mv /var/local/verb/configs/sitetldstatus286 /var/local/verb/configs/sitetldstatus
mv /var/local/verb/configs/siteinstallstatus286 /var/local/verb/configs/siteinstallstatus
sed -i "s/host286/${HNAME}/g" /var/local/verb/configs/sitenameip
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/sitenameip
sed -i "s/tld286/${SERVERTLD}/g" /var/local/verb/configs/sitenameip
sed -i "s/ip286/${SERVERIP}/g" /var/local/verb/configs/sitenameip
sed -i "s/timeregion286/${PHPREGION}/g" /var/local/verb/configs/sitenameip
sed -i "s/timecity286/${PHPCITY}/g" /var/local/verb/configs/sitenameip
sed -i "s/inkcertemail286/${SSLEMAIL}/g" /var/local/verb/configs/inkcert/inkcertstatus
## Copy other config files with pre-install status
mv /var/local/verb/configs/sitemailpath286 /var/local/verb/configs/sitemailpath
mv /var/local/verb/configs/sitemailpass286 /var/local/verb/configs/sitemailpass
mv /var/local/verb/configs/siteufwip286 /var/local/verb/configs/siteufwip

# Start the Verber crontab for future apps, even though it is empty now
crontab /var/local/verb/configs/verbcrontab
## Add inkCertLE's auto updater to the crontab
echo "3 3 * * * root /var/local/verb/configs/inkcert/inkcertle-renew-all.sh" >> /var/local/verb/configs/verbcrontab
## Set crontab to run the verbcrontab
crontab /var/local/verb/configs/verbcrontab

# PHP ini file
mv /var/local/verb/configs/php.name286.ini /var/local/verb/configs/php.${VNAME}.ini
sed -i "s/phplimit286/${PHPLIMIT}/g" /var/local/verb/configs/php.${VNAME}.ini
sed -i "s/phpsize286M/${PHPSIZE}M/g" /var/local/verb/configs/php.${VNAME}.ini
sed -i "s/phptimeregion286/${PHPREGION}/g" /var/local/verb/configs/php.${VNAME}.ini
sed -i "s/phptimecity286/${PHPCITY}/g" /var/local/verb/configs/php.${VNAME}.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/php.${VNAME}.ini
mv /etc/php/7.0/apache2/php.ini /etc/php/7.0/apache2/php.original.ini
ln -sfn /var/local/verb/configs/php.${VNAME}.ini /etc/php/7.0/apache2/php.ini

# sites-available
cp /var/local/verb/inst/config/etc/apache2/sites-available/* /etc/apache2/sites-available/
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/000-default.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/default-ssl.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.email.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/email.name286.verb.email.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/mail.name286.verb.email.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/boxes.name286.verb.email.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/rc.name286.verb.email.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.one.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/one.name286.verb.one.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/ink.name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/ask.name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/code.name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/bb.name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/blog.name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/home.name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/pen.name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/shop.name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/sn.name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/wiki.name286.verb.ink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.blue.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/blue.name286.verb.blue.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/owncloud.name286.verb.blue.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/pydio.name286.verb.blue.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/seafile.name286.verb.blue.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.guru.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/guru.name286.verb.guru.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/cgi.name286.verb.guru.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/ftp.name286.verb.guru.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/files.name286.verb.guru.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/fossil.name286.verb.guru.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/mysql.name286.verb.guru.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/net2ftp.name286.verb.guru.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/repo.name286.verb.guru.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.kiwi.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/kiwi.name286.verb.kiwi.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/ampache.name286.verb.kiwi.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/art.name286.verb.kiwi.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/gallery.name286.verb.kiwi.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/media.name286.verb.kiwi.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/podcast.name286.verb.kiwi.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/studio.name286.verb.kiwi.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.pink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/pink.name286.verb.pink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.red.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/red.name286.verb.red.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/act.name286.verb.red.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/crm.name286.verb.red.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/erp.name286.verb.red.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/hrm.name286.verb.red.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/odoo.name286.verb.red.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/scm.name286.verb.red.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.pink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/pink.name286.verb.pink.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.rocks.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/rocks.name286.verb.rocks.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/name286.verb.uno.conf
sed -i "s/name286/${VNAME}/g" /etc/apache2/sites-available/uno.name286.verb.uno.conf
mv /etc/apache2/sites-available/name286.verb.email.conf /etc/apache2/sites-available/${VNAME}.verb.email.conf
mv /etc/apache2/sites-available/email.name286.verb.email.conf /etc/apache2/sites-available/email.${VNAME}.verb.email.conf
mv /etc/apache2/sites-available/mail.name286.verb.email.conf /etc/apache2/sites-available/mail.${VNAME}.verb.email.conf
mv /etc/apache2/sites-available/boxes.name286.verb.email.conf /etc/apache2/sites-available/boxes.${VNAME}.verb.email.conf
mv /etc/apache2/sites-available/rc.name286.verb.email.conf /etc/apache2/sites-available/rc.${VNAME}.verb.email.conf
mv /etc/apache2/sites-available/name286.verb.one.conf /etc/apache2/sites-available/${VNAME}.verb.one.conf
mv /etc/apache2/sites-available/one.name286.verb.one.conf /etc/apache2/sites-available/one.${VNAME}.verb.one.conf
mv /etc/apache2/sites-available/name286.verb.ink.conf /etc/apache2/sites-available/${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/ink.name286.verb.ink.conf /etc/apache2/sites-available/ink.${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/ask.name286.verb.ink.conf /etc/apache2/sites-available/ask.${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/code.name286.verb.ink.conf /etc/apache2/sites-available/code.${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/bb.name286.verb.ink.conf /etc/apache2/sites-available/bb.${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/blog.name286.verb.ink.conf /etc/apache2/sites-available/blog.${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/home.name286.verb.ink.conf /etc/apache2/sites-available/home.${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/pen.name286.verb.ink.conf /etc/apache2/sites-available/pen.${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/shop.name286.verb.ink.conf /etc/apache2/sites-available/shop.${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/sn.name286.verb.ink.conf /etc/apache2/sites-available/sn.${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/wiki.name286.verb.ink.conf /etc/apache2/sites-available/wiki.${VNAME}.verb.ink.conf
mv /etc/apache2/sites-available/name286.verb.blue.conf /etc/apache2/sites-available/${VNAME}.verb.blue.conf
mv /etc/apache2/sites-available/blue.name286.verb.blue.conf /etc/apache2/sites-available/blue.${VNAME}.verb.blue.conf
mv /etc/apache2/sites-available/owncloud.name286.verb.blue.conf /etc/apache2/sites-available/owncloud.${VNAME}.verb.blue.conf
mv /etc/apache2/sites-available/pydio.name286.verb.blue.conf /etc/apache2/sites-available/pydio.${VNAME}.verb.blue.conf
mv /etc/apache2/sites-available/seafile.name286.verb.blue.conf /etc/apache2/sites-available/seafile.${VNAME}.verb.blue.conf
mv /etc/apache2/sites-available/name286.verb.guru.conf /etc/apache2/sites-available/${VNAME}.verb.guru.conf
mv /etc/apache2/sites-available/guru.name286.verb.guru.conf /etc/apache2/sites-available/guru.${VNAME}.verb.guru.conf
mv /etc/apache2/sites-available/cgi.name286.verb.guru.conf /etc/apache2/sites-available/cgi.${VNAME}.verb.guru.conf
mv /etc/apache2/sites-available/ftp.name286.verb.guru.conf /etc/apache2/sites-available/ftp.${VNAME}.verb.guru.conf
mv /etc/apache2/sites-available/files.name286.verb.guru.conf /etc/apache2/sites-available/files.${VNAME}.verb.guru.conf
mv /etc/apache2/sites-available/fossil.name286.verb.guru.conf /etc/apache2/sites-available/fossil.${VNAME}.verb.guru.conf
mv /etc/apache2/sites-available/mysql.name286.verb.guru.conf /etc/apache2/sites-available/mysql.${VNAME}.verb.guru.conf
mv /etc/apache2/sites-available/net2ftp.name286.verb.guru.conf /etc/apache2/sites-available/net2ftp.${VNAME}.verb.guru.conf
mv /etc/apache2/sites-available/repo.name286.verb.guru.conf /etc/apache2/sites-available/repo.${VNAME}.verb.guru.conf
mv /etc/apache2/sites-available/name286.verb.kiwi.conf /etc/apache2/sites-available/${VNAME}.verb.kiwi.conf
mv /etc/apache2/sites-available/kiwi.name286.verb.kiwi.conf /etc/apache2/sites-available/kiwi.${VNAME}.verb.kiwi.conf
mv /etc/apache2/sites-available/ampache.name286.verb.kiwi.conf /etc/apache2/sites-available/ampache.${VNAME}.verb.kiwi.conf
mv /etc/apache2/sites-available/art.name286.verb.kiwi.conf /etc/apache2/sites-available/art.${VNAME}.verb.kiwi.conf
mv /etc/apache2/sites-available/gallery.name286.verb.kiwi.conf /etc/apache2/sites-available/gallery.${VNAME}.verb.kiwi.conf
mv /etc/apache2/sites-available/media.name286.verb.kiwi.conf /etc/apache2/sites-available/media.${VNAME}.verb.kiwi.conf
mv /etc/apache2/sites-available/podcast.name286.verb.kiwi.conf /etc/apache2/sites-available/podcast.${VNAME}.verb.kiwi.conf
mv /etc/apache2/sites-available/studio.name286.verb.kiwi.conf /etc/apache2/sites-available/studio.${VNAME}.verb.kiwi.conf
mv /etc/apache2/sites-available/name286.verb.pink.conf /etc/apache2/sites-available/${VNAME}.verb.pink.conf
mv /etc/apache2/sites-available/pink.name286.verb.pink.conf /etc/apache2/sites-available/pink.${VNAME}.verb.pink.conf
mv /etc/apache2/sites-available/name286.verb.red.conf /etc/apache2/sites-available/${VNAME}.verb.red.conf
mv /etc/apache2/sites-available/red.name286.verb.red.conf /etc/apache2/sites-available/red.${VNAME}.verb.red.conf
mv /etc/apache2/sites-available/act.name286.verb.red.conf /etc/apache2/sites-available/act.${VNAME}.verb.red.conf
mv /etc/apache2/sites-available/crm.name286.verb.red.conf /etc/apache2/sites-available/crm.${VNAME}.verb.red.conf
mv /etc/apache2/sites-available/erp.name286.verb.red.conf /etc/apache2/sites-available/erp.${VNAME}.verb.red.conf
mv /etc/apache2/sites-available/hrm.name286.verb.red.conf /etc/apache2/sites-available/hrm.${VNAME}.verb.red.conf
mv /etc/apache2/sites-available/odoo.name286.verb.red.conf /etc/apache2/sites-available/odoo.${VNAME}.verb.red.conf
mv /etc/apache2/sites-available/scm.name286.verb.red.conf /etc/apache2/sites-available/scm.${VNAME}.verb.red.conf
mv /etc/apache2/sites-available/name286.verb.rocks.conf /etc/apache2/sites-available/${VNAME}.verb.rocks.conf
mv /etc/apache2/sites-available/rocks.name286.verb.rocks.conf /etc/apache2/sites-available/rocks.${VNAME}.verb.rocks.conf
mv /etc/apache2/sites-available/name286.verb.uno.conf /etc/apache2/sites-available/${VNAME}.verb.uno.conf
mv /etc/apache2/sites-available/uno.name286.verb.uno.conf /etc/apache2/sites-available/uno.${VNAME}.verb.uno.conf
# www start indexes
/var/local/verb/serfs/updatehtmlverbs
######## REMOVE BELOW IF updatehtmlverbs (above) completes the installation successfully #############
#sed -i "s/name286/${VNAME}/g" /var/www/html/0ne/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/email/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/email.email/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/one/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/one.one/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink.ink/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink.ask/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink.code/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink.bb/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink.blog/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink.home/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink.pen/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink.shop/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink.sn/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/ink.wiki/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/blue/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/blue.blue/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/blue.owncloud/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/blue.pydio/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/blue.seafile/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru.guru/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru.cgi/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru.ftp/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru.files/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru.fossil/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru.mysql/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru.net2ftp/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru.repo/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi.kiwi/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi.ampache/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi.art/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi.gallery/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi.media/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi.podcast/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi.studio/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/pink/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/pink.pink/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red.red/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red.act/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red.crm/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red.erp/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red.hrm/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red.odoo/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red.scm/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/rocks/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/rocks.rocks/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/uno/index.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/uno.uno/index.php
### pointink, pointone, pointguru, and pointuno indexes
#sed -i "s/name286/${VNAME}/g" /var/www/html/one/index-one.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/one/index-newonesub.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/blue/index-blue.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/blue/index-owncloud.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/blue/index-pydio.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/blue/index-seafile.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru/index-guru.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru/index-newgurusub.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru/index-cgi.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru/index-ftp.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru/index-files.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru/index-fossil.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru/index-mysql.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru/index-net2ftp.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/guru/index-repo.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi/index-kiwi.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi/index-ampache.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi/index-art.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi/index-gallery.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi/index-media.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi/index-podcast.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/kiwi/index-studio.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red/index-red.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red/index-scm.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red/index-odoo.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red/index-hrm.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red/index-erp.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red/index-crm.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/red/index-act.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/rocks/index-rocks.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/uno/index-uno.php
#sed -i "s/name286/${VNAME}/g" /var/www/html/uno/index-newunosub.php
###################### REMOVE ABOVE IF INSTALLATION WORKS ####################

# Enable sites (future uses if exists statements for sites-on config settings)
a2ensite ${VNAME}.verb.email email.${VNAME}.verb.email
a2ensite ${VNAME}.verb.ink ink.${VNAME}.verb.ink ask.${VNAME}.verb.ink bb.${VNAME}.verb.ink blog.${VNAME}.verb.ink code.${VNAME}.verb.ink home.${VNAME}.verb.ink pen.${VNAME}.verb.ink shop.${VNAME}.verb.ink sn.${VNAME}.verb.ink wiki.${VNAME}.verb.ink
a2ensite ${VNAME}.verb.one one.${VNAME}.verb.one
a2ensite ${VNAME}.verb.blue blue.${VNAME}.verb.blue owncloud.${VNAME}.verb.blue pydio.${VNAME}.verb.blue seafile.${VNAME}.verb.blue
a2ensite ${VNAME}.verb.guru guru.${VNAME}.verb.guru cgi.${VNAME}.verb.guru ftp.${VNAME}.verb.guru files.${VNAME}.verb.guru fossil.${VNAME}.verb.guru mysql.${VNAME}.verb.guru net2ftp.${VNAME}.verb.guru repo.${VNAME}.verb.guru
a2ensite ${VNAME}.verb.kiwi kiwi.${VNAME}.verb.kiwi ampache.${VNAME}.verb.kiwi art.${VNAME}.verb.kiwi gallery.${VNAME}.verb.kiwi media.${VNAME}.verb.kiwi podcast.${VNAME}.verb.kiwi studio.${VNAME}.verb.kiwi
a2ensite ${VNAME}.verb.pink pink.${VNAME}.verb.pink
a2ensite ${VNAME}.verb.red red.${VNAME}.verb.red act.${VNAME}.verb.red crm.${VNAME}.verb.red erp.${VNAME}.verb.red hrm.${VNAME}.verb.red odoo.${VNAME}.verb.red scm.${VNAME}.verb.red
a2ensite ${VNAME}.verb.rocks rocks.${VNAME}.verb.rocks
a2ensite ${VNAME}.verb.uno uno.${VNAME}.verb.uno
service apache2 reload

# New site configs
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/newonesub.conf
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/newgurusub.conf
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/newonesubcgi.conf
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/newgurusubcgi.conf
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/newghostsite.conf
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/newodoosite.conf
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/sub286.name286.verb.tld286.conf
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/odoo.name286.verb.red.conf-odoo
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/blog.name286.verb.ink.conf-ghost
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/bb.name286.verb.ink.conf-wpbb
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/blog.name286.verb.ink.conf-wpblg
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/blog.name286.verb.ink.conf-drupal
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/site-files/blog.name286.verb.ink.conf-october
mv /var/local/verb/configs/site-files/sub286.name286.verb.tld286.conf /var/local/verb/configs/site-files/sub286.${VNAME}.verb.tld286.conf
mv /var/local/verb/configs/site-files/odoo.name286.verb.red.conf-odoo /var/local/verb/configs/site-files/odoo.${VNAME}.verb.red.conf-odoo
mv /var/local/verb/configs/site-files/blog.name286.verb.ink.conf-ghost /var/local/verb/configs/site-files/blog.${VNAME}.verb.ink.conf-ghost
mv /var/local/verb/configs/site-files/bb.name286.verb.ink.conf-wpbb /var/local/verb/configs/site-files/bb.${VNAME}.verb.ink.conf-wpbb
mv /var/local/verb/configs/site-files/blog.name286.verb.ink.conf-wpblg /var/local/verb/configs/site-files/blog.${VNAME}.verb.ink.conf-wpblg
mv /var/local/verb/configs/site-files/blog.name286.verb.ink.conf-drupal /var/local/verb/configs/site-files/blog.${VNAME}.verb.ink.conf-drupal
mv /var/local/verb/configs/site-files/blog.name286.verb.ink.conf-october /var/local/verb/configs/site-files/blog.${VNAME}.verb.ink.conf-october

# Host name
hostname ${HNAME}.${VNAME}.verb.${SERVERTLD}
## Set /etc/hostname
echo "${HNAME}.${VNAME}.verb.${SERVERTLD}" > /etc/hostname
## Set /etc/hosts
sed -i "s/127\.0\.1\.1.*/127\.0\.1\.1 ${HNAME}.${VNAME}.verb.${SERVERTLD} ${VNAME}/g" /etc/hosts
sed -i "s/127\.0\.1\.1.*/127\.0\.1\.1 ${HNAME}.${VNAME}.verb.${SERVERTLD} ${VNAME}\n${SERVERIP} ${HNAME}.${VNAME}.verb.${SERVERTLD} ${HNAME}/g" /etc/hosts
sed -i "s/127\.0\.0\.1.*/127\.0\.0\.1 localhost.localdomain localhost/g" /etc/hosts

# inkCert ini and crontab files
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/verber-openssl.cnf
sed -i "s/tld286/${SERVERTLD}/g" /var/local/verb/configs/inkcert/verber-openssl.cnf
sed -i "s/SSLEMAIL/${SSLEMAIL}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.email.ini
sed -i "s/SSLEMAIL/${SSLEMAIL}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.one.ini
sed -i "s/SSLEMAIL/${SSLEMAIL}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.ink.ini
sed -i "s/SSLEMAIL/${SSLEMAIL}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.blue.ini
sed -i "s/SSLEMAIL/${SSLEMAIL}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.guru.ini
sed -i "s/SSLEMAIL/${SSLEMAIL}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.kiwi.ini
sed -i "s/SSLEMAIL/${SSLEMAIL}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.red.ini
sed -i "s/SSLEMAIL/${SSLEMAIL}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.rocks.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.email.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.one.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.ink.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.blue.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.guru.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.kiwi.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.pink.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.red.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.rocks.ini
sed -i "s/name286/${VNAME}/g" /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.uno.ini
mv /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.email.ini /var/local/verb/configs/inkcert/cli-ini/cli.${VNAME}.verb.email.ini
mv /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.one.ini /var/local/verb/configs/inkcert/cli-ini/cli.${VNAME}.verb.one.ini
mv /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.ink.ini /var/local/verb/configs/inkcert/cli-ini/cli.${VNAME}.verb.ink.ini
mv /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.blue.ini /var/local/verb/configs/inkcert/cli-ini/cli.${VNAME}.verb.blue.ini
mv /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.guru.ini /var/local/verb/configs/inkcert/cli-ini/cli.${VNAME}.verb.guru.ini
mv /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.kiwi.ini /var/local/verb/configs/inkcert/cli-ini/cli.${VNAME}.verb.kiwi.ini
mv /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.red.ini /var/local/verb/configs/inkcert/cli-ini/cli.${VNAME}.verb.red.ini
mv /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.rocks.ini /var/local/verb/configs/inkcert/cli-ini/cli.${VNAME}.verb.rocks.ini
mv /var/local/verb/configs/inkcert/cli-ini/cli.name286.verb.uno.ini /var/local/verb/configs/inkcert/cli-ini/cli.${VNAME}.verb.uno.ini
mv /var/local/verb/configs/inkcert/cli-ini/siteinkcert.name286.verb.email /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${VNAME}.verb.email
mv /var/local/verb/configs/inkcert/cli-ini/siteinkcert.name286.verb.one /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${VNAME}.verb.one
mv /var/local/verb/configs/inkcert/cli-ini/siteinkcert.name286.verb.ink /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${VNAME}.verb.ink
mv /var/local/verb/configs/inkcert/cli-ini/siteinkcert.name286.verb.blue /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${VNAME}.verb.blue
mv /var/local/verb/configs/inkcert/cli-ini/siteinkcert.name286.verb.guru /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${VNAME}.verb.guru
mv /var/local/verb/configs/inkcert/cli-ini/siteinkcert.name286.verb.kiwi /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${VNAME}.verb.kiwi
mv /var/local/verb/configs/inkcert/cli-ini/siteinkcert.name286.verb.pink /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${VNAME}.verb.pink
mv /var/local/verb/configs/inkcert/cli-ini/siteinkcert.name286.verb.red /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${VNAME}.verb.red
mv /var/local/verb/configs/inkcert/cli-ini/siteinkcert.name286.verb.rocks /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${VNAME}.verb.rocks
mv /var/local/verb/configs/inkcert/cli-ini/siteinkcert.name286.verb.uno /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${VNAME}.verb.uno

# Create the new boss user
adduser ${NEWBOSS} --gecos ",,," --disabled-password
echo "${NEWBOSS}:${NEWBOSSPASS}" | chpasswd
usermod -a -G sudo ${NEWBOSS}
usermod -a -G www-data ${NEWBOSS}
ln -sfn /var/local/verb/boss /home/${NEWBOSS}/
## User privilege specification
echo '# Added in inkVerb preserver setup' >> /etc/sudoers
echo '${NEWBOSS}  ALL=(ALL:ALL) ALL' >> /etc/sudoers

# New Boss MySQL root password
mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
CREATE USER ${NEWBOSS}@localhost;
SET PASSWORD FOR ${NEWBOSS}@localhost=PASSWORD('${NEWBOSSPASS}');
GRANT ALL PRIVILEGES ON *.* TO '${NEWBOSS}'@'localhost' IDENTIFIED BY '${NEWBOSSPASS}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"

# Port (set to something to avoid attacks)
sed -i "s/Port.*/Port ${NEWPORT}/g" /etc/ssh/sshd_config
ufw allow ${NEWPORT}
sed -i "s/SITEPORT.*/SITEPORT=${NEWPORT}/g"  /var/local/verb/configs/siteport

# Instructions
######################### FIX inkCert instructions #########################
echo "After 1. setting up any extra domains and subdomains, 2. turning off any unused verb domains and changing the email server setting if you choose,
- Run: doinkcert-all-verbs (or doinkcert YOURNAME.verb.TLD if not using a single server)
- Then, set up email with postfix and roundcube.

If you choose to set up email before doinkcert, you will need to make an Advanced > exception rule for these in your browser concerning security/safety/SSL, you should not need to permanently store it.

You should reboot the server now using:

sudo reboot

Then, for SSH,

login using: 'ssh root@${SERVERIP} -p ${NEWPORT}'

OR for password with the new boss user,

login using: 'ssh ${NEWBOSS}@${SERVERIP} -p ${NEWPORT}'
"

# Delete this one-time script
rm /var/local/verb/serfs/setupverb
rm /var/local/verb/inst/setupverb


